import { AdminSidebar } from "@/components/admin-sidebar";
import { Bell, CheckCircle2, CircleHelp, Clock3, FileWarning, SearchCheck, Store, XCircle } from 'lucide-react';

const claims = [
  ['MO-1048', 'Aarav Sharma', 'Flipkart', 'Luma X5 5G Smartphone', '28 Aug 2026', '₹350 expected cashback', 'Evidence required', 'Open'],
  ['MO-1047', 'Nisha Patel', 'Myntra', 'Stride Runner 2', '27 Aug 2026', 'Up to 8% cashback', 'Merchant reference supplied', 'In review'],
  ['MO-1046', 'Meera Iyer', 'Nykaa', 'Silk Glow Vitamin C Serum', '25 Aug 2026', '₹50 expected cashback', 'Cancellation found', 'Resolved'],
];

export default function ReportedOrdersPage() {
  return <main className="admin-v2"><AdminSidebar/><section className="admin-main"><header className="admin-top"><FileWarning size={21} /><b>Reported Orders</b><span className="dashboard-date">Missing-order claims · preview mode</span><Bell size={19} /><span className="avatar">SR</span></header><main className="admin-content"><div className="admin-title"><div><p>EXCEPTION MANAGEMENT</p><h1>Reported Orders</h1><span>Review customer claims when an eligible merchant conversion does not appear automatically.</span></div><button className="add-store" disabled>Review next claim</button></div><p className="preview-note">These are mock cases. A real claim requires an authenticated customer, click reference, merchant order reference and secure review permissions.</p><section className="admin-stats"><article><FileWarning /><div><small>Open claims</small><b>1</b><em>Needs evidence</em></div></article><article><Clock3 /><div><small>In review</small><b>1</b><em>Provider / merchant lookup</em></div></article><article><CheckCircle2 /><div><small>Resolved</small><b>1</b><em>Decision recorded</em></div></article><article><CircleHelp /><div><small>Average review</small><b>4 days</b><em>Future service target</em></div></article><article><XCircle /><div><small>Rejected</small><b>0</b><em>Mock queue</em></div></article></section><section className="admin-grid"><article className="store-table"><div className="table-head"><div><a className="current">All claims</a><a>Open</a><a>In review</a><a>Resolved</a></div></div><div className="table-scroll"><table><thead><tr><th>CLAIM</th><th>SHOPPER</th><th>MERCHANT / PRODUCT</th><th>PURCHASE DATE</th><th>EXPECTED BENEFIT</th><th>EVIDENCE</th><th>STATUS</th></tr></thead><tbody>{claims.map((claim) => <tr key={claim[0]}><td><strong>{claim[0]}</strong></td><td>{claim[1]}</td><td><span><strong>{claim[2]}</strong><small>{claim[3]}</small></span></td><td>{claim[4]}</td><td>{claim[5]}</td><td>{claim[6]}</td><td><em className={claim[7] === 'Resolved' ? 'status-active' : 'status-paused'}>{claim[7]}</em></td></tr>)}</tbody></table></div><footer>Claim decisions must be auditable. A confirmation can credit only the cashback amount defined by the original eligible offer.</footer></article><aside className="admin-right"><article><h2>Claim workflow</h2><p>1. Match redirect <span>Required</span></p><p>2. Verify merchant order <span>Required</span></p><p>3. Confirm eligibility <span>Required</span></p><p>4. Credit cashback <span>Locked</span></p></article><article><h2>Evidence policy</h2><p className="activity">Order reference or invoice<small>Customer submission requirement</small></p><p className="activity">Provider response / report<small>Required for final decision</small></p></article></aside></section></main></section></main>;
}
