'use client';

import { useState, useTransition } from 'react';
import { Activity, Bell, Bot, Check, ChevronRight, CircleAlert, FileText, Globe2, LockKeyhole, Package, Pause, Play, Save, ShieldCheck, Store, Workflow } from 'lucide-react';
import { saveGlobalSettings, type SettingsPayload, type SettingsSaveResult } from './actions';

export type GlobalSettings = SettingsPayload & { id?: number; updated_at?: string | null };
export type SettingsHealth = { ai_available: boolean; ai_enabled: number; ai_total: number; ai_failed_recent: number; feeds_available: boolean; feeds_active: number; feeds_total: number; campaigns_available: boolean; campaigns_live: number; campaigns_total: number; templates_available: boolean; templates_active: number; templates_total: number };
const tabs = [
  ['identity', 'Identity', Globe2], ['rules', 'Global Rules', FileText], ['controls', 'Work Controls', Workflow], ['safety', 'Safety & Approvals', ShieldCheck], ['status', 'System Status', Activity],
] as const;
type Tab = typeof tabs[number][0];

export function SettingsWorkspace({ initial, health, connected }: { initial: GlobalSettings; health: SettingsHealth; connected: boolean }) {
  const [tab, setTab] = useState<Tab>('identity');
  const [draft, setDraft] = useState<GlobalSettings>(initial);
  const [saved, setSaved] = useState<GlobalSettings>(initial);
  const [notice, setNotice] = useState<SettingsSaveResult | null>(null);
  const [pending, startTransition] = useTransition();
  const dirty = JSON.stringify(draft) !== JSON.stringify(saved);
  const patch = <K extends keyof GlobalSettings>(key: K, value: GlobalSettings[K]) => setDraft((current) => ({ ...current, [key]: value }));
  const control = (key: keyof GlobalSettings['work_controls'], value: boolean) => patch('work_controls', { ...draft.work_controls, [key]: value });
  const save = () => startTransition(async () => {
    setNotice(null);
    const result = await saveGlobalSettings(draft);
    setNotice(result);
    if (result.ok) setSaved(draft);
  });
  const stateLabel = (on: boolean) => on ? 'On' : 'Stopped';
  const Toggle = ({ checked, label, onChange, disabled = false }: { checked: boolean; label: string; onChange: (value: boolean) => void; disabled?: boolean }) => <button type="button" role="switch" aria-checked={checked} aria-label={label} disabled={disabled} className={`settings-switch ${checked ? 'on' : ''}`} onClick={() => onChange(!checked)}><span/></button>;
  const controlRows: { key: keyof GlobalSettings['work_controls']; title: string; description: string; icon: typeof Package }[] = [
    { key: 'product_intake', title: 'Automated product intake', description: 'Allow AI discovery and approved feed runs to start.', icon: Package },
    { key: 'scheduled_promotions', title: 'Promotion publishing', description: 'Allow campaign publication from Deals & Banners. Scheduled execution needs a connected scheduler.', icon: Store },
    { key: 'nonessential_notifications', title: 'Promotional notifications', description: 'Allow deals and announcement messages; essential account, support and cashback notices remain on.', icon: Bell },
    { key: 'ai_workflows', title: 'AI workflows', description: 'Allow new AI jobs to run. Provider selection stays in AI Providers.', icon: Bot },
  ];
  return <>
    <div className="settings-heading"><div><p>GLOBAL CONTROLS</p><h1>Settings</h1><span>Set the site identity, shared rules and master start/stop controls.</span></div><span className={`settings-db-state ${connected ? 'ready' : 'missing'}`}><i/>{connected ? 'Settings source connected' : 'Database setup required'}</span></div>
    <nav className="settings-tabs" aria-label="Settings sections">{tabs.map(([key, label, Icon]) => <button type="button" key={key} onClick={() => setTab(key)} className={tab === key ? 'active' : ''} aria-current={tab === key ? 'page' : undefined}><Icon size={18}/>{label}</button>)}</nav>
    {!connected && <p className="settings-notice error" role="alert"><CircleAlert size={18}/> Global settings are unavailable to this admin session. Verify the database migration and your Owner/Admin access before saving.</p>}
    {notice && <p className={`settings-notice ${notice.ok ? 'success' : 'error'}`} role="status">{notice.ok ? <Check size={18}/> : <CircleAlert size={18}/>} {notice.ok ? 'Settings saved successfully.' : notice.error}</p>}
    {tab === 'identity' && <section className="settings-panel settings-identity"><header><Globe2/><div><h2>Website identity</h2><p>Branding and the default document language shared across Glonni.</p></div></header><div className="settings-form-grid"><label>Website name<input value={draft.site_name} maxLength={80} onChange={(event) => patch('site_name', event.target.value)}/><small>Used in the customer header and footer.</small></label><label>Logo image URL <span className="optional-label">Optional</span><input type="url" placeholder="https://…" value={draft.logo_url} onChange={(event) => patch('logo_url', event.target.value)}/><small>Use a publicly accessible HTTPS image.</small></label><label>Default language<select value={draft.default_language} onChange={(event) => patch('default_language', event.target.value)}><option value="en-IN">English (India)</option><option value="en-US">English (US)</option></select><small>Updates the document language for accessibility tools.</small></label></div><p className="settings-inline-note"><LockKeyhole size={16}/> Transaction currency is determined by each transaction/provider record; it is not changed globally here.</p></section>}
    {tab === 'rules' && <section className="settings-panel"><header><FileText/><div><h2>Global operating rules</h2><p>Shared baseline guidance supplied to AI workflows; agent-specific instructions remain in AI Agents.</p></div></header><label className="settings-full-label">Rules<textarea value={draft.global_rules} maxLength={5000} onChange={(event) => patch('global_rules', event.target.value)} placeholder={'Add shared rules, for example:\n• Never invent prices, commissions or cashback.\n• Keep every proposed change review-only until approved.\n• Use connected stores as the source for store-specific offers.'}/><small>{draft.global_rules.length}/5,000 characters · Saved rules are passed to supported AI jobs as operating context.</small></label></section>}
    {tab === 'controls' && <section className="settings-panel"><header><Workflow/><div><h2>Work controls</h2><p>Master switches for site-wide automated work. Detailed setup stays in each feature’s page.</p></div></header><div className="settings-control-list">{controlRows.map(({ key, title, description, icon: Icon }) => <article className="settings-control-row" key={key}><Icon/><span><b>{title}</b><small>{description}</small></span><strong className={draft.work_controls[key] ? 'running' : 'stopped'}>{stateLabel(draft.work_controls[key])}</strong><Toggle checked={draft.work_controls[key]} label={`Turn ${title} ${draft.work_controls[key] ? 'off' : 'on'}`} onChange={(value) => control(key, value)}/></article>)}</div><p className="settings-inline-note"><LockKeyhole size={16}/> Pausing AI workflows prevents new AI jobs from running. It does not change provider keys or assignments.</p></section>}
    {tab === 'safety' && <section className="settings-panel"><header><ShieldCheck/><div><h2>Safety & approvals</h2><p>Global guardrails for actions that can affect customers or the public site.</p></div></header><div className="settings-control-list"><article className="settings-control-row"><ShieldCheck/><span><b>Require admin approval before publishing</b><small>This is a mandatory Glonni safeguard; AI-created products and promotions remain review-only until an authorized admin approves them.</small></span><strong className="running">Required</strong><Toggle checked label="Admin approval is always required before publishing" onChange={() => {}} disabled/></article><article className="settings-control-row settings-pause-row"><Pause/><span><b>Pause all automated work</b><small>Master stop for AI jobs, promotion publishing, product intake and promotional notices. Essential account, support and cashback messages are preserved.</small></span><strong className={draft.work_controls.pause_all ? 'stopped' : 'running'}>{draft.work_controls.pause_all ? 'Paused' : 'Running'}</strong><Toggle checked={draft.work_controls.pause_all} label={draft.work_controls.pause_all ? 'Resume automated work' : 'Pause all automated work'} onChange={(value) => control('pause_all', value)}/></article></div></section>}
    {tab === 'status' && <section className="settings-panel"><header><Activity/><div><h2>System status</h2><p>Read-only summaries pulled from the existing admin data sources.</p></div></header><div className="settings-status-grid"><Status icon={Bot} title="AI agents" value={health.ai_available ? `${health.ai_enabled} of ${health.ai_total} enabled` : 'Unavailable'} detail={health.ai_available ? `${health.ai_failed_recent} failed jobs in the latest 100` : 'Could not read agent and job records'} href="/admin/ai-agents"/><Status icon={Package} title="Product feeds" value={health.feeds_available ? `${health.feeds_active} active` : 'Unavailable'} detail={health.feeds_available ? `${health.feeds_total} configured feeds` : 'Could not read feed records'} href="/admin/products?view=feeds"/><Status icon={Store} title="Promotions" value={health.campaigns_available ? `${health.campaigns_live} published` : 'Unavailable'} detail={health.campaigns_available ? `${health.campaigns_total} campaigns recorded` : 'Could not read campaign records'} href="/admin/campaigns"/><Status icon={Bell} title="Notification templates" value={health.templates_available ? `${health.templates_active} active` : 'Unavailable'} detail={health.templates_available ? `${health.templates_total} templates configured` : 'Could not read template records'} href="/admin/notifications"/></div><p className="settings-inline-note"><Activity size={16}/> These are database-recorded states, not an uptime guarantee for external providers or scheduled workers.</p></section>}
    <section className="settings-links"><div><b>Manage detailed configuration</b><small>Dedicated pages remain the source of truth for these areas.</small></div><a href="/admin/ai-providers"><Bot/>AI Providers<ChevronRight/></a><a href="/admin/ai-agents"><Workflow/>AI Agents<ChevronRight/></a><a href="/admin"><Store/>Stores &amp; Brands<ChevronRight/></a><a href="/admin/notifications"><Bell/>Notifications<ChevronRight/></a></section>
    <footer className="settings-savebar"><span className={dirty ? 'dirty' : 'clean'}><i/>{dirty ? 'Unsaved changes' : 'All changes saved'}</span><button type="button" disabled={!dirty || pending || !connected} onClick={save}><Save size={17}/>{pending ? 'Saving…' : 'Save changes'}</button></footer>
  </>;
}

function Status({ icon: Icon, title, value, detail, href }: { icon: typeof Package; title: string; value: string; detail: string; href: string }) {
  return <article className="settings-status-card"><Icon/><div><b>{title}</b><strong>{value}</strong><small>{detail}</small></div><a href={href} aria-label={`Open ${title}`}><ChevronRight/></a></article>;
}
