import Link from 'next/link';
import { AdminSidebar } from '@/components/admin-sidebar';
import { createClient } from '@/lib/supabase/server';
import { AlertTriangle, Bell, Bot, CheckCircle2, CircleDollarSign, Clock3, ExternalLink, FlaskConical, GitCompareArrows, ImageIcon, RefreshCw, ShieldCheck } from 'lucide-react';
import { rerunQualitySection, runQualityTest } from './actions';

const sectionKeys=['identity','images','taxonomy','variants','specifications','information','store_offers'] as const;
const label=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase());
const object=(value:unknown):Record<string,any>=>value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,any>:{};
const array=(value:unknown):any[]=>Array.isArray(value)?value:[];
const shown=(value:unknown)=>value===null||value===undefined||value===''?'Not available':typeof value==='string'?value:JSON.stringify(value,null,2);
const compact=(value:unknown)=>{const text=shown(value);return text.length>220?`${text.slice(0,220)}…`:text};
const savedValue=(product:any,key:string)=>({identity:{title:product?.title,brand:product?.brand,model_code:product?.manual_metadata?.model_code},images:{primary_image_url:product?.image_url,gallery_images:product?.gallery_images},taxonomy:{category_id:product?.category_id,category:product?.categories?.name},variants:product?.variants,specifications:product?.specifications,information:product?.product_information,store_offers:product?.offers}[key]);
const fetchedValue=(proposal:any,key:string)=>({identity:{title:proposal.title,brand:proposal.brand,model_code:proposal.model_code,canonical_identity:proposal.canonical_identity},images:{primary_image_url:proposal.primary_image_url,gallery_images:proposal.gallery_images,image_candidates:proposal.image_candidates},taxonomy:{category_id:proposal.category_id,reason:proposal.category_reason},variants:proposal.variations,specifications:proposal.specifications,information:proposal.product_information,store_offers:proposal.offer_candidates}[key]);

export default async function AiQualityPage({searchParams}:{searchParams:Promise<{job?:string;error?:string;success?:string}>}){
  const query=await searchParams; const supabase=await createClient();
  const [{data:products},{data:jobs}]=await Promise.all([
    supabase.from('products').select('id,title,brand').order('title').limit(500),
    supabase.from('ai_jobs').select('*').eq('job_type','product_enrichment').order('created_at',{ascending:false}).limit(30),
  ]);
  const qualityJobs=(jobs??[]).filter(job=>job.input?.quality_test===true);
  const selected=qualityJobs.find(job=>job.id===query.job)??qualityJobs[0]??null;
  const sourceProductId=String(selected?.input?.source_product_id??'');
  const {data:sourceProduct}=sourceProductId?await supabase.from('products').select('*,categories(name),offers(id,current_price,list_price,stock_status,merchant_id,provider_id,customer_rating,bank_offer,cashback_amount,cashback_percent,destination_url)').eq('id',sourceProductId).maybeSingle():{data:null};
  const proposal=object(selected?.output?.proposal??selected?.output); const metrics=object(selected?.output?.metrics); const confidence=object(proposal.section_confidence); const missing=array(proposal.missing_fields); const conflicts=array(proposal.conflicts); const duplicates=array(proposal.duplicate_candidates); const selectedSections=array(selected?.input?.sections);
  const overall=Math.round(Number(proposal.confidence)||0); const status=!selected?'No tests':selected.status==='failed'?'Failed':conflicts.length||missing.length?'Needs review':overall>=80?'Verified':'Needs review';
  const completed=qualityJobs.filter(j=>j.status==='completed'); const failed=qualityJobs.filter(j=>j.status==='failed'); const avg=completed.length?Math.round(completed.reduce((sum,j)=>sum+Number(j.output?.proposal?.confidence??j.output?.confidence??0),0)/completed.length):0;
  return <main className="admin-v2 ai-admin"><AdminSidebar/><section className="admin-main"><header className="admin-top"><FlaskConical/><b>AI Quality Control</b><span className="dashboard-date">Product enrichment validation</span><Bell/><span className="avatar">SR</span></header><main className="ai-quality-page">
    <div className="ai-command-head"><div><p>AI PRODUCT OPERATIONS</p><h1>Enrichment Quality Control</h1><span>Test, compare and approve AI product information without publishing it.</span></div><Link className="add-store" href="/admin/ai-agents/ceo-operations?agent=catalogue_merchandising&tab=approvals">Open CEO review</Link></div>
    {query.error&&<p className="qc-message error">{query.error}</p>}{query.success&&<p className="qc-message success">{query.success}</p>}
    <section className="qc-stats"><article><FlaskConical/><span><small>Quality tests</small><b>{qualityJobs.length}</b><em>Permanent run history</em></span></article><article><CheckCircle2/><span><small>Average confidence</small><b>{avg}%</b><em>Completed tests</em></span></article><article><AlertTriangle/><span><small>Needs attention</small><b>{qualityJobs.filter(j=>array(j.output?.proposal?.missing_fields??j.output?.missing_fields).length||array(j.output?.proposal?.conflicts??j.output?.conflicts).length).length}</b><em>Missing or conflicting</em></span></article><article><ShieldCheck/><span><small>Runtime failures</small><b>{failed.length}</b><em>{failed.length?'Review errors':'Healthy'}</em></span></article></section>
    <section className="qc-console"><header><div><Bot/><span><h2>Run a product quality test</h2><p>Select a saved product for comparison, or enter a new product name.</p></span></div><small>Nothing publishes automatically</small></header><form action={runQualityTest}><label>Saved product<select name="productId" defaultValue=""><option value="">No saved product — research by name</option>{(products??[]).map(product=><option key={product.id} value={product.id}>{product.title}{product.brand?` · ${product.brand}`:''}</option>)}</select></label><label>Product name<input name="query" placeholder="e.g. Apple iPhone 16 128GB"/></label><label>Test scope<select name="section" defaultValue="all"><option value="all">Complete product</option>{sectionKeys.map(key=><option value={key} key={key}>{label(key)} only</option>)}</select></label><button><FlaskConical/> Run quality test</button></form></section>
    {selected&&<><section className="qc-run-head"><div><span className={`qc-status ${status.toLowerCase().replaceAll(' ','-')}`}>{status}</span><h2>{String(selected.input?.query??'Product enrichment test')}</h2><p>{selectedSections.length?`Focused rerun: ${selectedSections.map(String).map(label).join(', ')}`:'Complete product validation'} · {selected.completed_at?new Date(selected.completed_at).toLocaleString('en-IN'):'In progress'}</p></div><div><span><Clock3/><small>Duration</small><b>{metrics.duration_ms?`${(Number(metrics.duration_ms)/1000).toFixed(1)}s`:'—'}</b></span><span><CircleDollarSign/><small>AI usage</small><b>{metrics.total_tokens?`${Number(metrics.total_tokens).toLocaleString()} tokens`:'Recorded next run'}</b></span><span><ExternalLink/><small>Sources</small><b>{array(selected.sources).length}</b></span></div></section>
    <section className="qc-alert-grid">{missing.length>0&&<article><AlertTriangle/><div><h3>Missing information</h3><p>{missing.map(String).join(' · ')}</p></div></article>}{conflicts.length>0&&<article><GitCompareArrows/><div><h3>Source conflicts</h3><p>{conflicts.map((item:any)=>String(item.field??item.summary??item)).join(' · ')}</p></div></article>}{duplicates.length>0&&<article><ImageIcon/><div><h3>Possible duplicates</h3><p>{duplicates.map((item:any)=>`${item.title??'Product'} ${item.similarity?`(${item.similarity}%)`:''}`).join(' · ')}</p></div></article>}{!missing.length&&!conflicts.length&&!duplicates.length&&selected.status==='completed'&&<article className="clear"><CheckCircle2/><div><h3>No blocking quality warning</h3><p>Review the source comparison before making the final approval decision.</p></div></article>}</section>
    <section className="qc-compare"><header><div><GitCompareArrows/><span><h2>Saved product versus AI result</h2><p>Compare every product section before accepting the AI proposal.</p></span></div><Link href={`/admin/approvals/ai/${selected.id}`}>Review individual fields →</Link></header><div className="qc-compare-labels"><b>SECTION</b><b>SAVED PRODUCT</b><b>AI-FETCHED RESULT</b><b>QUALITY</b><b>ACTION</b></div>{sectionKeys.map(key=>{const score=Math.round(Number(confidence[key])||0);const absent=missing.some(item=>String(item).toLowerCase().includes(key.replace('_',' ')));const conflict=conflicts.some((item:any)=>String(item.field??item.summary??item).toLowerCase().includes(key.replace('_',' ')));return <article key={key}><div><b>{label(key)}</b><small>{conflict?'Conflicting sources':absent?'Information missing':score>=80?'Strong match':'Admin review needed'}</small></div><pre>{compact(savedValue(sourceProduct,key))}</pre><pre>{compact(fetchedValue(proposal,key))}</pre><span className={`qc-score ${score>=80?'good':score>=60?'medium':'low'}`}><b>{score||'—'}{score?'%':''}</b><i><em style={{width:`${score}%`}}/></i></span><form action={rerunQualitySection}><input type="hidden" name="jobId" value={selected.id}/><input type="hidden" name="section" value={key}/><button disabled={selected.status!=='completed'}><RefreshCw/> Fetch again</button></form></article>})}</section></>}
    <section className="qc-history"><header><div><Clock3/><span><h2>Test history</h2><p>Results, failures, timing and review state are retained.</p></span></div><small>{qualityJobs.length} recent runs</small></header><div><table><thead><tr><th>PRODUCT</th><th>SCOPE</th><th>STATUS</th><th>CONFIDENCE</th><th>SOURCES</th><th>DURATION</th><th>REVIEW</th></tr></thead><tbody>{qualityJobs.map(job=>{const jobMetrics=object(job.output?.metrics);return <tr key={job.id}><td><b>{String(job.input?.query??'Product')}</b><small>{new Date(job.created_at).toLocaleString('en-IN')}</small></td><td>{array(job.input?.sections).length?array(job.input.sections).map(String).map(label).join(', '):'Complete product'}</td><td><em className={`job-${job.status}`}>{label(job.status)}</em>{job.latest_error&&<small>{job.latest_error}</small>}</td><td>{Math.round(Number(job.output?.proposal?.confidence??job.output?.confidence)||0)}%</td><td>{array(job.sources).length}</td><td>{jobMetrics.duration_ms?`${(Number(jobMetrics.duration_ms)/1000).toFixed(1)}s`:'—'}</td><td><Link href={job.status==='completed'?`/admin/ai-quality?job=${job.id}`:'#'}>{job.status==='completed'?'Compare':'Unavailable'}</Link></td></tr>})}{!qualityJobs.length&&<tr><td colSpan={7}>No quality tests have been run yet.</td></tr>}</tbody></table></div></section>
  </main></section></main>;
}
