import { Banknote, Bell, CheckCircle2, Clock3, Layers3, RefreshCcw, ShieldAlert, WalletCards, XCircle} from 'lucide-react';
import { AdminSidebar } from '@/components/admin-sidebar';
import { createClient } from '@/lib/supabase/server';
import { createPayoutBatch, decideWithdrawal, recordPayoutResult, setPayoutVerification } from '../payout-actions';

export const dynamic = 'force-dynamic';
const money=(n:number|string)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(n));
const label=(s:string)=>s.replaceAll('_',' ');
type Withdrawal={id:string;profile_id:string;amount:number|string;status:string;risk_level:string;risk_score:number;risk_reasons:string[];upi_id:string;reviewer_note:string|null;created_at:string;profiles:{display_name:string|null}|null;payout_verifications:{status:string;reference:string|null}|null};
type Item={id:string;amount:number|string;status:string;destination_mask:string;provider_payout_reference:string|null;failure_message:string|null;created_at:string;profiles:{display_name:string|null}|null;withdrawal_requests:{id:string}|null;payout_batches:{batch_reference:string;provider_key:string|null}|null};
type Batch={id:string;batch_reference:string;status:string;payout_count:number;total_amount:number|string;provider_key:string|null;created_at:string};

export default async function Page({searchParams}:{searchParams:Promise<{status?:string}>}){
  const params=await searchParams,active=params.status??'open',s=await createClient();
  const [{data:withdrawalData},{data:itemData},{data:batchData}]=await Promise.all([
    s.from('withdrawal_requests').select('id,profile_id,amount,status,risk_level,risk_score,risk_reasons,upi_id,reviewer_note,created_at,profiles(display_name),payout_verifications(status,reference)').order('created_at',{ascending:false}).limit(250),
    s.from('payout_items').select('id,amount,status,destination_mask,provider_payout_reference,failure_message,created_at,profiles(display_name),withdrawal_requests(id),payout_batches(batch_reference,provider_key)').order('created_at',{ascending:false}).limit(250),
    s.from('payout_batches').select('id,batch_reference,status,payout_count,total_amount,provider_key,created_at').order('created_at',{ascending:false}).limit(100),
  ]);
  const all=(withdrawalData??[])as unknown as Withdrawal[],items=(itemData??[])as unknown as Item[],batches=(batchData??[])as Batch[];
  const openStatuses=['requested','on_hold','approved'];
  const rows=all.filter(x=>active==='all'||active==='open'&&openStatuses.includes(x.status)||x.status===active);
  const approved=all.filter(x=>x.status==='approved');
  const queueTotal=all.filter(x=>openStatuses.includes(x.status)).reduce((n,x)=>n+Number(x.amount),0);
  const paidTotal=items.filter(x=>x.status==='paid').reduce((n,x)=>n+Number(x.amount),0);
  return <main className="admin-v2"><AdminSidebar/><section className="admin-main"><header className="admin-top"><WalletCards/><b>Payout Operations</b><span className="dashboard-date">Controlled approval · batches · immutable ledger</span><Bell/><span className="avatar">SR</span></header><main className="admin-content">
    <div className="admin-title"><div><p>AFFILIATE OPERATIONS · STEP 5</p><h1>Customer payouts &amp; reconciliation</h1><span>Verify customers, review withdrawal risk, create payout batches, and reconcile provider results without editing the wallet ledger.</span></div><a className="add-store" href="/admin/wallet">Wallet overview</a></div>
    <p className="preview-note">This workspace records approved payout execution. It does not send real money until an approved payout provider is connected.</p>
    <section className="admin-stats payout-stats"><article><Clock3/><div><small>Open queue</small><b>{money(queueTotal)}</b><em>{all.filter(x=>openStatuses.includes(x.status)).length} requests</em></div></article><article><CheckCircle2/><div><small>Approved</small><b>{approved.length}</b><em>Ready for batching</em></div></article><article><Layers3/><div><small>Active batches</small><b>{batches.filter(x=>['approved','processing'].includes(x.status)).length}</b><em>{batches.length} total batches</em></div></article><article><Banknote/><div><small>Paid</small><b>{money(paidTotal)}</b><em>Ledger debited</em></div></article><article><ShieldAlert/><div><small>Held / failed</small><b>{all.filter(x=>['on_hold','failed'].includes(x.status)).length}</b><em>Needs attention</em></div></article></section>

    {approved.length>0&&<form className="payout-batch-builder" action={createPayoutBatch}><header><div><h2>Create an approved payout batch</h2><p>Select verified withdrawals. Execution results are recorded after the provider run.</p></div><label>Provider / rail<select name="providerKey" defaultValue=""><option value="">Select during execution</option><option value="upi_manual">UPI — manual provider file</option><option value="razorpayx">RazorpayX</option><option value="cashfree">Cashfree Payouts</option></select></label><button>Create batch</button></header><div>{approved.map(x=><label key={x.id}><input type="checkbox" name="withdrawalId" value={x.id}/><span><b>{x.profiles?.display_name??'Customer'}</b><small>{x.payout_verifications?.status==='verified'?'KYC verified':'Verification required'} · UPI ••••{x.upi_id.slice(-4)}</small></span><strong>{money(x.amount)}</strong></label>)}</div></form>}

    <section className="finance-workspace payout-workspace"><article className="store-table finance-table payout-review-table"><div className="conversion-toolbar"><nav>{['open','requested','on_hold','approved','batched','processing','paid','failed','reversed','rejected','all'].map(x=><a key={x} className={active===x?'current':''} href={`/admin/payout-operations?status=${x}`}>{label(x)}</a>)}</nav></div><div className="table-scroll"><table><thead><tr><th>CUSTOMER</th><th>REQUEST</th><th>DESTINATION</th><th>KYC</th><th>RISK</th><th>STATUS</th><th>REVIEW NOTE</th><th>ACTION</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td><strong>{x.profiles?.display_name??'Customer'}</strong><small>{x.profile_id.slice(0,8).toUpperCase()}</small></td><td><strong>{money(x.amount)}</strong><small>{new Date(x.created_at).toLocaleString('en-IN')}</small></td><td>UPI ••••{x.upi_id.slice(-4)}</td><td><em className={x.payout_verifications?.status==='verified'?'status-active':'status-paused'}>{label(x.payout_verifications?.status??'not_started')}</em></td><td><em className={x.risk_level==='low'?'status-active':x.risk_level==='medium'?'status-paused':'status-danger'}>{label(x.risk_level)} · {x.risk_score}</em><small>{x.risk_reasons?.map(label).join(', ')||'No signals'}</small></td><td><em className={['paid'].includes(x.status)?'status-active':['failed','reversed','rejected'].includes(x.status)?'status-danger':'status-paused'}>{label(x.status)}</em></td><td>{x.reviewer_note??'—'}</td><td>{openStatuses.includes(x.status)?<details className="conversion-actions"><summary>Review</summary><div><form action={setPayoutVerification}><input type="hidden" name="profileId" value={x.profile_id}/><label>Verification reference<input name="reference" placeholder="KYC provider reference"/></label><label>Verification note<input name="note" placeholder="Review note"/></label><span className="finance-decisions"><button name="status" value="verified">Verify KYC</button><button className="danger-button" name="status" value="rejected">Reject KYC</button></span></form><form action={decideWithdrawal}><input type="hidden" name="withdrawalId" value={x.id}/><label>Decision note<input name="note" placeholder="Required for hold or reject"/></label><span className="finance-decisions"><button name="decision" value="approve">Approve</button><button name="decision" value="hold">Hold</button><button className="danger-button" name="decision" value="reject">Reject</button></span></form></div></details>:'Closed / batched'}</td></tr>):<tr><td colSpan={8}>No withdrawal requests in this state.</td></tr>}</tbody></table></div><footer>Approval requires verified payout identity and sufficient confirmed wallet balance.</footer></article>
      <aside className="admin-right"><article><h2>Required controls</h2><p>KYC / payout identity <span>Required</span></p><p>Wallet balance check <span>Automatic</span></p><p>Risk review <span>Recorded</span></p><p>2FA finance approval <span>Required</span></p></article><article><h2>Ledger guarantee</h2><p className="activity"><Banknote/>Paid result debits once<small>One immutable debit per payout item.</small></p><p className="activity"><RefreshCcw/>Reversal restores once<small>Corrections create an equal positive entry.</small></p></article></aside>
    </section>

    <section className="payout-execution"><header><div><h2>Payout batch execution</h2><p>Record provider processing, success, failure, or a later reversal.</p></div></header>{items.length?<div className="table-scroll"><table><thead><tr><th>BATCH</th><th>CUSTOMER</th><th>DESTINATION</th><th>AMOUNT</th><th>STATUS</th><th>PROVIDER REFERENCE</th><th>RESULT</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><strong>{x.payout_batches?.batch_reference??'Batch'}</strong><small>{x.payout_batches?.provider_key??'Provider not selected'}</small></td><td>{x.profiles?.display_name??'Customer'}</td><td>{x.destination_mask}</td><td><strong>{money(x.amount)}</strong></td><td><em className={x.status==='paid'?'status-active':['failed','reversed'].includes(x.status)?'status-danger':'status-paused'}>{label(x.status)}</em></td><td>{x.provider_payout_reference??'—'}{x.failure_message&&<small>{x.failure_message}</small>}</td><td>{x.status==='reversed'?'Closed':<details className="conversion-actions"><summary>Record result</summary><div><form action={recordPayoutResult}><input type="hidden" name="payoutItemId" value={x.id}/><label>Provider payout reference<input name="providerReference" defaultValue={x.provider_payout_reference??''} placeholder="Required when paid"/></label><label>Note / failure reason<input name="note" placeholder="Required for failure or reversal"/></label><span className="finance-decisions">{x.status==='queued'&&<button name="result" value="processing">Processing</button>}{['queued','processing'].includes(x.status)&&<><button name="result" value="paid">Paid</button><button className="danger-button" name="result" value="failed">Failed</button></>}{x.status==='paid'&&<button className="danger-button" name="result" value="reversed">Reverse</button>}</span></form></div></details>}</td></tr>)}</tbody></table></div>:<div className="payout-empty"><XCircle/><h3>No payout batches yet</h3><p>Approve withdrawal requests, then create the first batch above.</p></div>}</section>
  </main></section></main>;
}
