'use server';

import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';

const allowedSections=new Set(['identity','images','taxonomy','variants','specifications','information','store_offers']);
const enc=(value:string)=>encodeURIComponent(value);
async function requireAdmin(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();const {data:assurance}=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();if(!user||assurance?.currentLevel!=='aal2'||!['owner','admin'].includes(String(user.app_metadata?.admin_role)))redirect('/admin/login');return{supabase,user};}
const sections=(form:FormData)=>form.getAll('sections').map(String).filter(value=>allowedSections.has(value));

export async function saveRefreshPolicy(form:FormData){
  const {supabase,user}=await requireAdmin();const productId=String(form.get('productId')??'');const selected=sections(form);const frequency=Math.max(1,Math.min(720,Number(form.get('frequencyHours'))||24));const stale=Math.max(1,Math.min(2160,Number(form.get('staleHours'))||24));
  if(!productId||!selected.length)redirect('/admin/product-freshness?error=Choose+a+product+and+at+least+one+refresh+section.');
  const {data:product}=await supabase.from('products').select('id').eq('id',productId).maybeSingle();if(!product)redirect('/admin/product-freshness?error=The+selected+product+does+not+exist.');
  const now=new Date().toISOString();const {error}=await supabase.from('product_refresh_policies').upsert({product_id:productId,is_enabled:true,frequency_hours:frequency,stale_after_hours:stale,sections:selected,requires_review:true,next_run_at:now,created_by:user.id,updated_by:user.id,updated_at:now},{onConflict:'product_id'});
  if(error)redirect(`/admin/product-freshness?error=${enc(error.message)}`);await supabase.from('audit_events').insert({actor_id:user.id,event_type:'product_refresh_policy_saved',entity_type:'product',entity_id:productId,source:'admin',metadata:{frequency_hours:frequency,stale_after_hours:stale,sections:selected}});revalidatePath('/admin/product-freshness');redirect('/admin/product-freshness?success=Refresh+policy+saved.');
}

export async function toggleRefreshPolicy(form:FormData){const {supabase,user}=await requireAdmin();const policyId=String(form.get('policyId')??'');const enabled=String(form.get('enabled'))==='true';const {error}=await supabase.from('product_refresh_policies').update({is_enabled:enabled,updated_by:user.id,updated_at:new Date().toISOString()}).eq('id',policyId);if(error)throw new Error(error.message);revalidatePath('/admin/product-freshness');}

export async function runProductRefresh(form:FormData){
  const {supabase,user}=await requireAdmin();const productId=String(form.get('productId')??'');const policyId=String(form.get('policyId')??'')||null;const selected=sections(form);const {data:product}=await supabase.from('products').select('id,title,brand,description,category_id,image_url,gallery_images,variants,specifications,product_information,manual_metadata').eq('id',productId).single();if(!product)throw new Error('Product not found.');
  const {data:run,error:runError}=await supabase.from('product_refresh_runs').insert({policy_id:policyId,product_id:productId,trigger_type:'manual',status:'queued',sections:selected,created_by:user.id}).select('id').single();if(runError||!run)throw new Error(runError?.message??'Unable to create refresh run.');
  const {data:job,error:jobError}=await supabase.from('ai_jobs').insert({agent_key:'catalogue_merchandising',job_type:'product_enrichment',input:{query:product.title,quality_test:true,scheduled_refresh:true,refresh_run_id:run.id,source_product_id:product.id,sections:selected},created_by:user.id,dedupe_key:`refresh:${product.id}:${Date.now()}`,review_only:true}).select('id').single();if(jobError||!job){await supabase.from('product_refresh_runs').update({status:'failed',error_message:jobError?.message??'Unable to create AI job',completed_at:new Date().toISOString()}).eq('id',run.id);throw new Error(jobError?.message??'Unable to create AI job.');}
  const started=new Date().toISOString();await supabase.from('product_refresh_runs').update({ai_job_id:job.id,status:'running',started_at:started,updated_at:started}).eq('id',run.id);const {data,error}=await supabase.functions.invoke('ai-job-runner',{body:{job_id:job.id}});const finished=new Date().toISOString();
  if(error||data?.error){await supabase.from('product_refresh_runs').update({status:'failed',error_message:data?.error??error?.message??'Refresh failed',completed_at:finished,updated_at:finished}).eq('id',run.id);if(policyId)await supabase.from('product_refresh_policies').update({last_run_at:finished,consecutive_failures:1,updated_by:user.id,updated_at:finished}).eq('id',policyId);redirect(`/admin/product-freshness?error=${enc(data?.error??error?.message??'Refresh failed.')}`);}
  const {data:savedJob}=await supabase.from('ai_jobs').select('output,sources').eq('id',job.id).single();const proposal=savedJob?.output?.proposal??savedJob?.output??{};const values:Record<string,unknown>={title:proposal.title,brand:proposal.brand,description:proposal.description,category_id:proposal.category_id,image_url:proposal.primary_image_url,gallery_images:proposal.gallery_images,variants:proposal.variations,specifications:proposal.specifications,product_information:proposal.product_information,manual_metadata:{...(product.manual_metadata??{}),canonical_identity:proposal.canonical_identity??{},ai_image_candidates:proposal.image_candidates??[]},store_offers:proposal.offer_candidates};const previous:Record<string,unknown>={title:product.title,brand:product.brand,description:product.description,category_id:product.category_id,image_url:product.image_url,gallery_images:product.gallery_images,variants:product.variants,specifications:product.specifications,product_information:product.product_information,manual_metadata:product.manual_metadata,store_offers:[]};const changed=Object.entries(values).filter(([key,value])=>value!==undefined&&JSON.stringify(value)!==JSON.stringify(previous[key]));
  const {data:changeSet,error:changeError}=await supabase.from('product_change_sets').insert({refresh_run_id:run.id,product_id:product.id,ai_job_id:job.id,status:'pending_review',risk_level:changed.some(([key])=>['category_id','store_offers'].includes(key))?'high':'medium',sources:Array.isArray(savedJob?.sources)?savedJob.sources:[],summary:`${changed.length} product sections changed and require approval.`}).select('id').single();if(changeError||!changeSet)throw new Error(changeError?.message??'Unable to create the change review.');
  if(changed.length){const sourceUrls=(Array.isArray(savedJob?.sources)?savedJob.sources:[]).map((source:any)=>source?.url).filter(Boolean);const rows=changed.map(([field,value])=>({change_set_id:changeSet.id,field_key:field,previous_value:previous[field]??null,proposed_value:value??null,risk_flags:field==='store_offers'?['protected_commercial_data','separate_offer_approval_required']:field==='category_id'?['taxonomy_change']:field==='image_url'||field==='gallery_images'?['external_media_source']:[],source_urls:sourceUrls}));const {error:itemsError}=await supabase.from('product_change_items').insert(rows);if(itemsError)throw new Error(itemsError.message);}
  await supabase.from('product_refresh_runs').update({status:'review_required',summary:'AI refresh completed. Compare and approve changes before publishing.',completed_at:finished,updated_at:finished}).eq('id',run.id);if(policyId){const {data:policy}=await supabase.from('product_refresh_policies').select('frequency_hours').eq('id',policyId).single();await supabase.from('product_refresh_policies').update({last_run_at:finished,last_success_at:finished,consecutive_failures:0,next_run_at:new Date(Date.now()+Number(policy?.frequency_hours??24)*3600000).toISOString(),updated_by:user.id,updated_at:finished}).eq('id',policyId);}
  revalidatePath('/admin/product-freshness');revalidatePath('/admin/approvals');redirect(`/admin/product-changes/${changeSet.id}?success=Refresh+completed.+Review+each+change+before+applying.`);
}
