import Link from 'next/link';
import { AdminSidebar } from '@/components/admin-sidebar';
import { createClient } from '@/lib/supabase/server';
import { AlertTriangle, Bell, CheckCircle2, Clock3, DatabaseZap, PauseCircle, Play, RefreshCw, ShieldCheck } from 'lucide-react';
import { runProductRefresh, saveRefreshPolicy, toggleRefreshPolicy } from './actions';

const labels:Record<string,string>={identity:'Identity',images:'Images',taxonomy:'Category',variants:'Variations',specifications:'Specifications',information:'Product information',store_offers:'Store prices & offers'};
const arr=(value:unknown):string[]=>Array.isArray(value)?value.map(String):[];
const ago=(value?:string|null)=>value?new Intl.RelativeTimeFormat('en',{numeric:'auto'}).format(-Math.max(1,Math.round((Date.now()-new Date(value).getTime())/3600000)),'hour'):'Never';
export default async function ProductFreshnessPage({searchParams}:{searchParams:Promise<{error?:string;success?:string}>}){
 const query=await searchParams;const supabase=await createClient();const staleCutoff=new Date(Date.now()-24*3600000).toISOString();const [{data:products},{data:policies},{data:runs},{data:staleOffers}]=await Promise.all([
  supabase.from('products').select('id,title,brand,is_active').order('title').limit(500),
  supabase.from('product_refresh_policies').select('*,products(title,brand,is_active)').order('next_run_at'),
  supabase.from('product_refresh_runs').select('*,products(title,brand),ai_jobs(review_status)').order('created_at',{ascending:false}).limit(30),
  supabase.from('offers').select('id,product_id,last_checked_at,status,products(title,brand),merchants(name)').or(`last_checked_at.is.null,last_checked_at.lt.${staleCutoff}`).limit(100),
 ]);const now=Date.now();const due=(policies??[]).filter(p=>p.is_enabled&&new Date(p.next_run_at).getTime()<=now);const enabled=(policies??[]).filter(p=>p.is_enabled);const failed=(runs??[]).filter(r=>r.status==='failed');
 return <main className="admin-v2 ai-admin"><AdminSidebar/><section className="admin-main"><header className="admin-top"><RefreshCw/><b>Product Freshness</b><span className="dashboard-date">Scheduled catalogue monitoring</span><Bell/><span className="avatar">SR</span></header><main className="freshness-page"><div className="ai-command-head"><div><p>CATALOGUE AUTOMATION</p><h1>Product Freshness &amp; Refresh</h1><span>Keep prices, availability and product information current without silent publishing.</span></div><Link className="add-store" href="/admin/ai-quality">Open Quality Control</Link></div>{query.error&&<p className="qc-message error">{query.error}</p>}{query.success&&<p className="qc-message success">{query.success}</p>}
 <section className="fresh-stats"><article><DatabaseZap/><span><small>Monitored products</small><b>{enabled.length}</b><em>Active refresh policies</em></span></article><article><Clock3/><span><small>Due for refresh</small><b>{due.length}</b><em>Scheduled time reached</em></span></article><article><AlertTriangle/><span><small>Stale store offers</small><b>{staleOffers?.length??0}</b><em>Not checked within 24 hours</em></span></article><article><ShieldCheck/><span><small>Failed refreshes</small><b>{failed.length}</b><em>Require admin attention</em></span></article></section>
 <section className="fresh-policy"><header><div><RefreshCw/><span><h2>Create or update a refresh policy</h2><p>Choosing an existing product updates its policy. Every result still requires review.</p></span></div><small>Mock mode · admin initiated</small></header><form action={saveRefreshPolicy}><label>Product<select name="productId" required><option value="">Select product</option>{(products??[]).map(p=><option key={p.id} value={p.id}>{p.title}{p.brand?` · ${p.brand}`:''}</option>)}</select></label><label>Refresh frequency<select name="frequencyHours" defaultValue="24"><option value="6">Every 6 hours</option><option value="12">Every 12 hours</option><option value="24">Daily</option><option value="72">Every 3 days</option><option value="168">Weekly</option></select></label><label>Mark stale after<select name="staleHours" defaultValue="24"><option value="6">6 hours</option><option value="12">12 hours</option><option value="24">24 hours</option><option value="72">3 days</option><option value="168">7 days</option></select></label><fieldset><legend>Information to refresh</legend>{Object.entries(labels).map(([key,label])=><label key={key}><input type="checkbox" name="sections" value={key} defaultChecked={key==='store_offers'||key==='images'}/>{label}</label>)}</fieldset><button>Save refresh policy</button></form></section>
 <section className="fresh-grid"><article className="fresh-table"><header><div><Clock3/><span><h2>Refresh schedule</h2><p>Drag-free, clear product-level schedules with direct controls.</p></span></div><b>{policies?.length??0} policies</b></header><div><table><thead><tr><th>PRODUCT</th><th>REFRESH CONTENT</th><th>FREQUENCY</th><th>LAST RUN</th><th>NEXT RUN</th><th>STATUS</th><th>ACTION</th></tr></thead><tbody>{(policies??[]).map(policy=><tr key={policy.id}><td><b>{policy.products?.title??'Product'}</b><small>{policy.products?.brand??'Brand pending'}</small></td><td>{arr(policy.sections).map(x=>labels[x]??x).join(', ')}</td><td>Every {policy.frequency_hours<24?`${policy.frequency_hours} hours`:policy.frequency_hours===24?'day':`${Math.round(policy.frequency_hours/24)} days`}</td><td>{ago(policy.last_run_at)}</td><td>{new Date(policy.next_run_at).toLocaleString('en-IN')}</td><td><em className={policy.is_enabled?'active':'paused'}>{policy.is_enabled?'Active':'Paused'}</em>{policy.consecutive_failures>0&&<small>{policy.consecutive_failures} failure</small>}</td><td><div className="fresh-actions"><form action={runProductRefresh}><input type="hidden" name="productId" value={policy.product_id}/><input type="hidden" name="policyId" value={policy.id}/>{arr(policy.sections).map(section=><input key={section} type="hidden" name="sections" value={section}/>) }<button><Play/>Run now</button></form><form action={toggleRefreshPolicy}><input type="hidden" name="policyId" value={policy.id}/><input type="hidden" name="enabled" value={String(!policy.is_enabled)}/><button className="secondary">{policy.is_enabled?<><PauseCircle/>Pause</>:<><CheckCircle2/>Resume</>}</button></form></div></td></tr>)}{!policies?.length&&<tr><td colSpan={7}>No refresh policies yet. Create the first policy above.</td></tr>}</tbody></table></div></article>
 <aside className="fresh-stale"><header><AlertTriangle/><span><h2>Stale store data</h2><p>Prioritised for checking</p></span></header>{(staleOffers??[]).slice(0,8).map((offer:any)=><article key={offer.id}><div><b>{offer.products?.title??'Product'}</b><small>{offer.merchants?.name??'Store'} · checked {ago(offer.last_checked_at)}</small></div><em>{offer.status}</em></article>)}{!staleOffers?.length&&<p className="preview-note">No stale store offers detected.</p>}</aside></section>
 <section className="fresh-history"><header><div><DatabaseZap/><span><h2>Refresh history</h2><p>Every attempt remains traceable through review and approval.</p></span></div><small>{runs?.length??0} recent runs</small></header><div><table><thead><tr><th>PRODUCT</th><th>TRIGGER</th><th>SECTIONS</th><th>STATUS</th><th>STARTED</th><th>RESULT</th></tr></thead><tbody>{(runs??[]).map(run=><tr key={run.id}><td><b>{run.products?.title??'Product'}</b><small>{run.products?.brand??''}</small></td><td>{run.trigger_type}</td><td>{arr(run.sections).map(x=>labels[x]??x).join(', ')||'Complete product'}</td><td><em className={`run-${run.status}`}>{run.status.replaceAll('_',' ')}</em></td><td>{new Date(run.created_at).toLocaleString('en-IN')}</td><td>{run.ai_job_id?<Link href={`/admin/ai-quality?job=${run.ai_job_id}`}>Open comparison →</Link>:run.error_message??'Waiting'}</td></tr>)}{!runs?.length&&<tr><td colSpan={6}>No refresh run has been recorded.</td></tr>}</tbody></table></div></section>
 </main></section></main>;
}
