import { AdminSidebar } from '@/components/admin-sidebar';
import { decideAiWork } from '../ai-actions';
import { createClient } from '@/lib/supabase/server';
import { Bell, CheckCircle2, CirclePause, ClipboardCheck, ShieldAlert } from 'lucide-react';

const label = (value: string) => value.replaceAll('_', ' ');
export default async function ApprovalsPage({ searchParams }: { searchParams: Promise<{ error?: string; success?: string }> }) {
  const supabase = await createClient(); const { data: items } = await supabase.from('ai_work_items').select('*').order('created_at', { ascending: false }); const query = await searchParams;
  return <main className="admin-v2"><AdminSidebar/><section className="admin-main"><header className="admin-top"><ClipboardCheck size={21}/><b>Approval Inbox</b><span className="dashboard-date">Owner decisions · audit protected</span><Bell size={19}/><span className="avatar">SR</span></header><main className="admin-content"><div className="admin-title"><div><p>AI COMPANY</p><h1>Approval Inbox</h1><span>One place for critical AI recommendations, campaigns, policy changes and financial exceptions.</span></div></div>{query.error && <p className="preview-note">{query.error}</p>}{query.success && <p className="preview-note">{query.success}</p>}<section className="admin-stats"><article><ClipboardCheck/><div><small>Pending decisions</small><b>{items?.filter(x=>x.status==='pending_approval').length ?? 0}</b><em>Owner action required</em></div></article><article><CheckCircle2/><div><small>Approved</small><b>{items?.filter(x=>x.status==='approved').length ?? 0}</b><em>Audited decisions</em></div></article><article><CirclePause/><div><small>On hold</small><b>{items?.filter(x=>x.status==='on_hold').length ?? 0}</b><em>Awaiting direction</em></div></article><article><ShieldAlert/><div><small>High risk</small><b>{items?.filter(x=>['high','critical'].includes(x.risk_level)).length ?? 0}</b><em>Review carefully</em></div></article></section><section className="admin-grid"><article className="store-table"><div className="table-head"><div><a className="current">All decisions</a><a>Pending</a><a>Completed</a></div></div><div className="table-scroll"><table><thead><tr><th>RECOMMENDATION</th><th>AREA</th><th>RISK</th><th>STATUS</th><th>OWNER ACTION</th></tr></thead><tbody>{(items ?? []).map(item=><tr key={item.id}><td><span><strong>{item.title}</strong><small>{item.proposed_by} · {item.summary}</small></span></td><td>{label(item.area)}</td><td>{item.risk_level}</td><td><em className={item.status==='approved'?'status-active':'status-paused'}>{label(item.status)}</em></td><td>{item.status==='pending_approval' ? <form action={decideAiWork} className="approval-actions"><input type="hidden" name="workItemId" value={item.id}/><button name="decision" value="approved">Approve</button><button name="decision" value="on_hold">Hold</button><button name="decision" value="rejected">Reject</button></form> : item.decision_note || 'Decision recorded'}</td></tr>)}</tbody></table></div><footer>Every decision is recorded with the owner identity, time, decision and note. Approval alone does not connect an account, spend money or publish content.</footer></article><aside className="admin-right"><article><h2>Decision rules</h2><p>Campaign spend <span>Owner only</span></p><p>Social publishing <span>Owner only</span></p><p>Provider policy changes <span>Owner only</span></p><p>Cashback exceptions <span>Owner only</span></p></article></aside></section></main></section></main>;
}
