'use server';
import { revalidatePath } from 'next/cache'; import { createClient } from '@/lib/supabase/server';
const assertAdminMutationsEnabled=()=>{if(process.env.ADMIN_MUTATIONS_ENABLED!=='true')throw new Error('Admin changes are locked until secure owner authentication is restored.');};
const slug=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');const refresh=()=>{revalidatePath('/admin');revalidatePath('/');revalidatePath('/deals');};
const audit=async(s:Awaited<ReturnType<typeof createClient>>,event_type:string,entity_type:string,entity_id:string|null,metadata:Record<string,unknown>)=>{await s.from('audit_events').insert({event_type,entity_type,entity_id,source:'admin_preview',metadata});};
export async function addCategory(f:FormData){assertAdminMutationsEnabled();const name=String(f.get('name')??'').trim();if(name){const s=await createClient();const {data}=await s.from('categories').insert({name,slug:slug(name),display_order:99,is_active:true}).select('id').single();if(data)await audit(s,'created','category',data.id,{name});refresh();}}
export async function addStore(f:FormData){assertAdminMutationsEnabled();const name=String(f.get('name')??''),url=String(f.get('url')??'');if(name&&url){const s=await createClient();const {data}=await s.from('merchants').insert({name,slug:slug(name),storefront_url:url,homepage_position:99,is_active:true}).select('id').single();if(data)await audit(s,'created','merchant',data.id,{name});refresh();}}
export async function addProvider(f:FormData){assertAdminMutationsEnabled();const name=String(f.get('name')??'').trim(),adapter_key=slug(String(f.get('adapterKey')??name));const mode=String(f.get('mode')??'manual');if(name&&adapter_key&&['manual','approval_required','automatic'].includes(mode)){const s=await createClient();const {data}=await s.from('affiliate_providers').insert({name,adapter_key,integration_mode:mode,is_active:false,config:{preview_only:true}}).select('id').single();if(data)await audit(s,'created','affiliate_provider',data.id,{name,adapter_key,mode});refresh();}}
export async function addProduct(f:FormData){assertAdminMutationsEnabled();const title=String(f.get('title')??'');if(title){const s=await createClient();const {data}=await s.from('products').insert({title,slug:slug(title),brand:String(f.get('brand')??''),description:String(f.get('description')??'')||null,image_url:String(f.get('image')??'')||null,category_id:String(f.get('category')??'')||null,is_active:true}).select('id').single();if(data)await audit(s,'created','product',data.id,{title});refresh();}}
export async function addOffer(f:FormData){assertAdminMutationsEnabled();const product_id=String(f.get('product')??''),merchant_id=String(f.get('merchant')??''),destination_url=String(f.get('url')??''),reward_type=String(f.get('rewardType')??'none');const valid=['none','fixed_cashback','percentage_cashback','coupon','merchant_promotion'];if(product_id&&merchant_id&&destination_url&&valid.includes(reward_type)){const s=await createClient();const cashback=reward_type==='fixed_cashback'?Number(f.get('cashback'))||null:null;const percent=reward_type==='percentage_cashback'?Number(f.get('cashbackPercent'))||null:null;const {data}=await s.from('offers').insert({product_id,merchant_id,provider_id:String(f.get('provider')??'')||null,destination_url,current_price:Number(f.get('price')),list_price:Number(f.get('listPrice'))||null,reward_type,cashback_amount:cashback,cashback_percent:percent,cashback_cap:percent?Number(f.get('cashbackCap'))||null:null,coupon_code:reward_type==='coupon'?String(f.get('couponCode')??'').trim()||null:null,reward_terms:String(f.get('rewardTerms')??'').trim()||null,cashback_tracking_supported:['fixed_cashback','percentage_cashback'].includes(reward_type),reward_funding_source:['fixed_cashback','percentage_cashback'].includes(reward_type)?String(f.get('fundingSource')??'provider'):'none',status:'active'}).select('id').single();if(data)await audit(s,'created','offer',data.id,{reward_type,provider_id:String(f.get('provider')??'')||null});refresh();}}
export async function removeItem(f:FormData){assertAdminMutationsEnabled();const table=String(f.get('table')),id=String(f.get('id'));if(['categories','merchants','products','offers','affiliate_providers'].includes(table)&&id){const s=await createClient();const {error}=await s.from(table).delete().eq('id',id);if(!error)await audit(s,'removed',table,id,{});refresh();}}
