'use server';
import { revalidatePath } from 'next/cache'; import { redirect } from 'next/navigation'; import { createClient } from '@/lib/supabase/server';
const slug=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');const refresh=()=>{revalidatePath('/admin');revalidatePath('/');revalidatePath('/deals');};
const audit=async(s:Awaited<ReturnType<typeof createClient>>,event_type:string,entity_type:string,entity_id:string|null,metadata:Record<string,unknown>)=>{await s.from('audit_events').insert({event_type,entity_type,entity_id,source:'admin_preview',metadata});};
async function requireAdminMutation(){const s=await createClient();const [{data:{user}},{data:assurance}]=await Promise.all([s.auth.getUser(),s.auth.mfa.getAuthenticatorAssuranceLevel()]);if(!user)redirect('/admin/login');const[{data:profile},{data:employee}]=await Promise.all([s.from('profiles').select('role').eq('id',user.id).single(),s.from('employees').select('status').eq('profile_id',user.id).single()]);if(!profile||!['owner','admin'].includes(profile.role)||!employee||employee.status!=='active'||assurance?.currentLevel!=='aal2')throw new Error('A verified owner or administrator 2FA session is required.');return{s,user};}
async function storeOperator(approval=false){const{s,user}=await requireAdminMutation();const{data:profile}=await s.from('profiles').select('role').eq('id',user.id).single();const allowed=approval?['owner','admin']:['owner','admin','editor'];if(!profile||!allowed.includes(profile.role))throw new Error('You do not have permission to change stores.');return{s,user};}
const storeRefresh=(slug?:string)=>{refresh();revalidatePath('/admin/dashboard');if(slug)revalidatePath(`/admin/stores/${slug}`);};
export async function createStore(f:FormData){const {s,user}=await storeOperator();const name=String(f.get('name')??'').trim(),url=String(f.get('url')??'').trim();if(!name||!/^https?:\/\//.test(url))throw new Error('Enter a store name and a valid https URL.');const handle=slug(name);const {data,error}=await s.from('merchants').insert({name,slug:handle,storefront_url:url,homepage_position:Number(f.get('homepagePosition'))||99,is_active:false,approval_status:'draft'}).select('id,slug').single();if(error)throw new Error(error.message);await audit(s,'created','merchant',data.id,{name,status:'draft',actor_id:user.id});storeRefresh(data.slug);redirect(`/admin/stores/${data.slug}?success=Store%20created%20as%20draft`);}
export async function updateStore(f:FormData){const {s,user}=await storeOperator();const id=String(f.get('id')??''),slugValue=String(f.get('slug')??''),name=String(f.get('name')??'').trim(),url=String(f.get('url')??'').trim();if(!id||!name||!/^https?:\/\//.test(url))throw new Error('Store name and a valid https URL are required.');const {error}=await s.from('merchants').update({name,storefront_url:url,homepage_position:Number(f.get('homepagePosition'))||99,review_notes:String(f.get('reviewNotes')??'').trim()||null,updated_at:new Date().toISOString()}).eq('id',id);if(error)throw new Error(error.message);await audit(s,'updated','merchant',id,{name,actor_id:user.id});storeRefresh(slugValue);redirect(`/admin/stores/${slugValue}?success=Store%20details%20saved`);}
export async function changeStoreStatus(f:FormData){const action=String(f.get('action')??'');const {s,user}=await storeOperator(['approve','reject'].includes(action));const id=String(f.get('id')??''),slugValue=String(f.get('slug')??'');const values=action==='approve'?{approval_status:'approved',is_active:true,reviewed_at:new Date().toISOString(),reviewed_by:user.id}:action==='pause'?{approval_status:'paused',is_active:false}:action==='resume'?{approval_status:'approved',is_active:true}:action==='submit'?{approval_status:'pending',is_active:false}:action==='reject'?{approval_status:'rejected',is_active:false,reviewed_at:new Date().toISOString(),reviewed_by:user.id}:null;if(!id||!values)throw new Error('Invalid store workflow action.');const {error}=await s.from('merchants').update({...values,updated_at:new Date().toISOString()}).eq('id',id);if(error)throw new Error(error.message);await audit(s,`store_${action}`,'merchant',id,{actor_id:user.id});storeRefresh(slugValue);redirect(`/admin/stores/${slugValue}?success=Store%20status%20updated`);}
export async function addCategory(f:FormData){const{s}=await requireAdminMutation();const name=String(f.get('name')??'').trim();if(name){const {data}=await s.from('categories').insert({name,slug:slug(name),display_order:99,is_active:true}).select('id').single();if(data)await audit(s,'created','category',data.id,{name});refresh();}}
export async function addStore(f:FormData){const{s}=await requireAdminMutation();const name=String(f.get('name')??''),url=String(f.get('url')??'');if(name&&url){const {data}=await s.from('merchants').insert({name,slug:slug(name),storefront_url:url,homepage_position:99,is_active:true}).select('id').single();if(data)await audit(s,'created','merchant',data.id,{name});refresh();}}
export async function addProvider(f:FormData){const{s}=await requireAdminMutation();const name=String(f.get('name')??'').trim(),adapter_key=slug(String(f.get('adapterKey')??name));const mode=String(f.get('mode')??'manual');if(name&&adapter_key&&['manual','approval_required','automatic'].includes(mode)){const {data}=await s.from('affiliate_providers').insert({name,adapter_key,integration_mode:mode,is_active:false,config:{preview_only:true}}).select('id').single();if(data)await audit(s,'created','affiliate_provider',data.id,{name,adapter_key,mode});refresh();}}
export async function addProduct(f:FormData){const{s}=await requireAdminMutation();const title=String(f.get('title')??'');if(title){const {data}=await s.from('products').insert({title,slug:slug(title),brand:String(f.get('brand')??''),description:String(f.get('description')??'')||null,image_url:String(f.get('image')??'')||null,category_id:String(f.get('category')??'')||null,is_active:true}).select('id').single();if(data)await audit(s,'created','product',data.id,{title});refresh();}}
export async function addOffer(f:FormData){const{s}=await requireAdminMutation();const product_id=String(f.get('product')??''),merchant_id=String(f.get('merchant')??''),destination_url=String(f.get('url')??''),reward_type=String(f.get('rewardType')??'none');const valid=['none','fixed_cashback','percentage_cashback','coupon','merchant_promotion'];if(product_id&&merchant_id&&destination_url&&valid.includes(reward_type)){const cashback=reward_type==='fixed_cashback'?Number(f.get('cashback'))||null:null;const percent=reward_type==='percentage_cashback'?Number(f.get('cashbackPercent'))||null:null;const {data}=await s.from('offers').insert({product_id,merchant_id,provider_id:String(f.get('provider')??'')||null,destination_url,current_price:Number(f.get('price')),list_price:Number(f.get('listPrice'))||null,reward_type,cashback_amount:cashback,cashback_percent:percent,cashback_cap:percent?Number(f.get('cashbackCap'))||null:null,coupon_code:reward_type==='coupon'?String(f.get('couponCode')??'').trim()||null:null,reward_terms:String(f.get('rewardTerms')??'').trim()||null,cashback_tracking_supported:['fixed_cashback','percentage_cashback'].includes(reward_type),reward_funding_source:['fixed_cashback','percentage_cashback'].includes(reward_type)?String(f.get('fundingSource')??'provider'):'none',status:'active'}).select('id').single();if(data)await audit(s,'created','offer',data.id,{reward_type,provider_id:String(f.get('provider')??'')||null});refresh();}}
export async function removeItem(f:FormData){const{s}=await requireAdminMutation();const table=String(f.get('table')),id=String(f.get('id'));if(['categories','merchants','products','offers','affiliate_providers'].includes(table)&&id){const {error}=await s.from(table).delete().eq('id',id);if(!error)await audit(s,'removed',table,id,{});refresh();}}
