import { Bell, Bot, CheckCircle2, ClipboardList, FileClock, FileSearch, Search, ShieldAlert, Users } from 'lucide-react';
import { AdminSidebar } from '@/components/admin-sidebar';
import { createClient } from '@/lib/supabase/server';

type Props = { searchParams: Promise<{ tab?: string; q?: string; surface?: string; status?: string }> };
type EventRow = { id: string; occurred_at: string; actor_id: string | null; actor_role: string | null; surface: string | null; event_type: string; endpoint: string | null; http_method: string | null; request_status: number | null; response_time_ms: number | null; ip_address: string | null; session_id: string | null; device_id: string | null; error_details: string | null; metadata: Record<string, unknown> | null; profiles: { display_name?: string } | null };
const tabs = [['activity', 'Activity', 'Everyday operational events', FileClock], ['audit', 'Audit trail', 'Permanent admin accountability', FileSearch], ['ai', 'AI actions', 'Agent work and recommendations', Bot], ['changes', 'Approvals & changes', 'Proposed and reviewed changes', CheckCircle2], ['security', 'Security events', 'Access and security signals', ShieldAlert]] as const;
const time = (value: string) => new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));
const label = (value: string | null | undefined) => (value || '—').replaceAll('_', ' ');
const queryHref = (values: Record<string, string | undefined>) => `/admin/activity?${new URLSearchParams(values as Record<string, string>).toString()}`;
function eventMatchesTab(event: EventRow, tab: string) { const type = event.event_type.toLowerCase(); if (tab === 'ai') return event.surface === 'ai' || type.includes('ai') || type.includes('agent'); if (tab === 'security') return type.includes('auth') || type.includes('login') || type.includes('permission') || type.includes('mfa') || type.includes('security') || Boolean(event.error_details); if (tab === 'changes') return type.includes('approval') || type.includes('change') || type.includes('publish') || type.includes('reject') || type.includes('resolve'); if (tab === 'audit') return event.surface === 'admin' || type.includes('admin') || type.includes('update') || type.includes('delete') || type.includes('create'); return !['ai', 'security', 'changes'].includes(tab); }

export default async function ActivityPage({ searchParams }: Props) {
  const params = await searchParams; const tab = tabs.some(([key]) => key === params.tab) ? params.tab! : 'activity'; const supabase = await createClient();
  const { data } = await supabase.from('activity_events').select('id,occurred_at,actor_id,actor_role,surface,event_type,endpoint,http_method,request_status,response_time_ms,ip_address,session_id,device_id,error_details,metadata,profiles(display_name)').order('occurred_at', { ascending: false }).limit(250);
  const allEvents = (data ?? []) as unknown as EventRow[]; const search = (params.q || '').trim().toLowerCase();
  const events = allEvents.filter((event) => { if (!eventMatchesTab(event, tab)) return false; if (params.surface && event.surface !== params.surface) return false; if (params.status === 'errors' && (event.request_status ?? 200) < 400) return false; if (!search) return true; return [event.event_type, event.endpoint, event.surface, event.actor_role, event.error_details, event.profiles?.display_name].some((value) => String(value || '').toLowerCase().includes(search)); });
  const errors = allEvents.filter((event) => (event.request_status ?? 0) >= 400).length; const uniqueActors = new Set(allEvents.map((event) => event.actor_id).filter(Boolean)).size; const tabCounts = Object.fromEntries(tabs.map(([key]) => [key, allEvents.filter((event) => eventMatchesTab(event, key)).length]));
  return <main className="admin-v2"><AdminSidebar/><section className="admin-main"><header className="admin-top"><FileClock size={21}/><b>Activity &amp; Audit Log</b><span className="dashboard-date">Traceable workspace activity</span><Bell size={19}/><span className="avatar">SR</span></header><main className="admin-content activity-workspace">
    <div className="admin-title"><div><p>SECURITY &amp; OBSERVABILITY</p><h1>Activity &amp; Audit Log</h1><span>Review what happened, who triggered it, and the related record—without editing the history itself.</span></div><a className="activity-export" href="/api/activity">Export data</a></div><p className="preview-note">Logs are read-only. You can open related records and investigate eligible changes, but the original record cannot be edited or deleted.</p>
    <section className="admin-stats activity-stats"><article><FileClock/><div><small>Visible records</small><b>{events.length}</b><em>{tabCounts[tab] ?? 0} in this view</em></div></article><article><Users/><div><small>Unique actors</small><b>{uniqueActors}</b><em>Customers and staff</em></div></article><article><ShieldAlert/><div><small>Errors</small><b>{errors}</b><em>HTTP 4xx / 5xx</em></div></article><article><ClipboardList/><div><small>Retention</small><b>180 days</b><em>Operational history</em></div></article></section>
    <nav className="activity-tabs" aria-label="Log views">{tabs.map(([key, title, description, Icon]) => <a className={tab === key ? 'active' : ''} href={queryHref({ tab: key, q: params.q, surface: params.surface, status: params.status })} key={key}><Icon size={17}/><span><b>{title}</b><small>{description}</small></span><em>{tabCounts[key]}</em></a>)}</nav>
    <form className="activity-filters" method="get"><input type="hidden" name="tab" value={tab}/><label><Search size={17}/><input name="q" defaultValue={params.q || ''} placeholder="Search user, action, store, product or ticket"/></label><select name="surface" defaultValue={params.surface || ''}><option value="">All modules</option><option value="customer">Customer</option><option value="admin">Admin</option><option value="api">API</option><option value="ai">AI</option></select><select name="status" defaultValue={params.status || ''}><option value="">All statuses</option><option value="errors">Errors only</option></select><button type="submit">Apply filters</button><a href={`/admin/activity?tab=${tab}`}>Clear</a></form>
    <section className="activity-panel"><div className="activity-panel-head"><div><h2>{tabs.find(([key]) => key === tab)?.[1]}</h2><p>{tabs.find(([key]) => key === tab)?.[2]}. Select a row to see the complete event context.</p></div><span>{events.length} records</span></div><div className="activity-list">{events.length ? events.map((event) => { const profile = event.profiles; const status = event.request_status ?? 200; return <details className="activity-row" key={event.id}><summary><span className="activity-time">{time(event.occurred_at)}</span><span className="activity-actor"><strong>{profile?.display_name || (event.actor_id ? 'Account user' : 'Anonymous visitor')}</strong><small>{label(event.actor_role)} · {label(event.surface)}</small></span><span className="activity-action"><strong>{label(event.event_type)}</strong><small>{event.http_method || 'EVENT'} {event.endpoint || 'Internal action'}</small></span><span className={status >= 400 ? 'event-badge danger' : 'event-badge'}>{status >= 400 ? 'Error' : 'Recorded'}</span><span className="activity-chevron">View details</span></summary><div className="activity-detail"><div><b>Event context</b><p>{label(event.event_type)} was recorded at {time(event.occurred_at)}.</p></div><div><b>Request</b><p>{event.http_method || '—'} {event.endpoint || 'Internal action'} · {event.response_time_ms ?? 0}ms</p></div><div><b>Trace</b><p>Session {event.session_id?.slice(0, 12) || '—'} · Device {event.device_id?.slice(0, 12) || '—'}</p></div><div><b>Identifiers</b><p>{event.ip_address || 'Restricted'}{event.error_details ? ` · ${event.error_details}` : ''}</p></div>{event.metadata && <div><b>Metadata</b><p>{Object.entries(event.metadata).map(([key, value]) => `${key}: ${String(value)}`).join(' · ') || 'No additional metadata'}</p></div>}<div className="activity-detail-actions"><a href={`/admin/search?q=${encodeURIComponent(event.event_type)}`}>Open related records</a>{tab === 'changes' && <button type="button" disabled title="Revert is enabled only for eligible approved changes">Revert eligible change</button>}</div></div></details>}) : <div className="activity-empty"><FileSearch size={28}/><h3>No records in this view</h3><p>New events will appear here when this workflow records activity.</p></div>}</div><footer>History is immutable. IP and device identifiers are restricted to authorised admin access; passwords, payment details, and request bodies are never stored.</footer></section>
  </main></section></main>;
}
