'use server';
import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
const toSlug=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
async function contentAdmin(){const s=await createClient();const[{data:{user}},{data:assurance}]=await Promise.all([s.auth.getUser(),s.auth.mfa.getAuthenticatorAssuranceLevel()]);if(!user)redirect('/admin/login');const[{data:profile},{data:employee}]=await Promise.all([s.from('profiles').select('role').eq('id',user.id).single(),s.from('employees').select('status').eq('profile_id',user.id).single()]);if(!profile||!['owner','admin','editor'].includes(profile.role)||employee?.status!=='active'||assurance?.currentLevel!=='aal2')throw new Error('An active 2FA-protected content-admin session is required.');return{s,user,role:profile.role};}
export async function createBuilderPage(f:FormData){const{s,user}=await contentAdmin();const title=String(f.get('title')??'').trim(),slug=toSlug(String(f.get('slug')??title));if(title.length<2||!slug)throw new Error('Enter a page title and URL handle.');const{data,error}=await s.from('site_pages').insert({title,slug,description:String(f.get('description')??'').trim()||null,seo_title:String(f.get('seoTitle')??'').trim()||null,seo_description:String(f.get('seoDescription')??'').trim()||null,device_visibility:String(f.get('device')??'all'),created_by:user.id}).select('id').single();if(error)throw new Error(error.message);await s.from('site_page_versions').insert({page_id:data.id,version_number:1,snapshot:{title,slug,blocks:[]},change_note:'Page created',created_by:user.id});await s.from('audit_events').insert({actor_id:user.id,event_type:'site_page_created',entity_type:'site_page',entity_id:data.id,source:'admin',metadata:{slug}});revalidatePath('/admin/cms');}
export async function addBuilderBlock(f:FormData){const{s,user}=await contentAdmin();const pageId=String(f.get('pageId')??''),type=String(f.get('type')??''),title=String(f.get('title')??'').trim(),body=String(f.get('body')??'').trim();if(!pageId||!['hero','banner','text','cta','faq','product_rail','store_rail','category_grid','trust_strip'].includes(type))throw new Error('Choose a page and approved block type.');const{data,error}=await s.from('site_page_blocks').insert({page_id:pageId,block_type:type,title:title||null,body:body||null,cta_label:String(f.get('ctaLabel')??'').trim()||null,cta_href:String(f.get('ctaHref')??'').trim()||null,image_url:String(f.get('imageUrl')??'').trim()||null,display_order:Number(f.get('displayOrder'))||100,device_visibility:String(f.get('device')??'all')}).select('id').single();if(error)throw new Error(error.message);await s.from('audit_events').insert({actor_id:user.id,event_type:'site_block_added',entity_type:'site_page_block',entity_id:data.id,source:'admin',metadata:{page_id:pageId,type}});revalidatePath('/admin/cms');}
export async function setBuilderPageStatus(f:FormData){const{s,user,role}=await contentAdmin();const id=String(f.get('id')??''),action=String(f.get('action')??'');const status=action==='submit'?'pending':action==='publish'?'published':action==='pause'?'paused':'draft';if(['publish','pause'].includes(action)&&!['owner','admin'].includes(role))throw new Error('Only an owner or admin can publish or pause a page.');const values=status==='published'?{status,published_at:new Date().toISOString(),approved_by:user.id,approved_at:new Date().toISOString(),updated_at:new Date().toISOString()}:{status,updated_at:new Date().toISOString()};const{data,error}=await s.from('site_pages').update(values).eq('id',id).select('id,title,slug').single();if(error||!data)throw new Error(error?.message||'Page not found.');const{data:blocks}=await s.from('site_page_blocks').select('*').eq('page_id',id).order('display_order');const{count}=await s.from('site_page_versions').select('*',{count:'exact',head:true}).eq('page_id',id);await s.from('site_page_versions').insert({page_id:id,version_number:(count??0)+1,snapshot:{page:data,blocks},change_note:`Status changed to ${status}`,created_by:user.id});await s.from('audit_events').insert({actor_id:user.id,event_type:`site_page_${status}`,entity_type:'site_page',entity_id:id,source:'admin',metadata:{slug:data.slug}});revalidatePath('/admin/cms');revalidatePath(`/pages/${data.slug}`);}
export async function createBuilderPopup(f:FormData){const{s,user}=await contentAdmin();const name=String(f.get('name')??'').trim(),title=String(f.get('title')??'').trim();if(name.length<2||title.length<2)throw new Error('Enter a popup name and title.');const{data,error}=await s.from('site_popups').insert({name,title,body:String(f.get('body')??'').trim()||null,cta_label:String(f.get('ctaLabel')??'').trim()||null,cta_href:String(f.get('ctaHref')??'').trim()||null,trigger_type:String(f.get('trigger')??'page_load'),target_scope:String(f.get('scope')??'all_pages'),device_visibility:String(f.get('device')??'all'),created_by:user.id}).select('id').single();if(error)throw new Error(error.message);await s.from('audit_events').insert({actor_id:user.id,event_type:'site_popup_created',entity_type:'site_popup',entity_id:data.id,source:'admin'});revalidatePath('/admin/cms');}
