import { AdminSidebar } from '@/components/admin-sidebar';
import { createClient } from '@/lib/supabase/server';
import { AlertTriangle, ArrowRight, Bell, Bot, CheckCircle2, CircleDollarSign, FileSearch, ListChecks, Megaphone, PackageSearch, ShieldCheck, Store, UsersRound } from 'lucide-react';

const agents = {
  'ceo-operations': { key: 'ceo_operations', name: 'CEO & Operations Manager', description: 'Owner guidance, approvals, risks and workflow oversight.', icon: Bot, pages: [['AI Agent Control Centre', '/admin/ai-agents'], ['Approval Inbox', '/admin/approvals'], ['Dashboard', '/admin/dashboard']], responsibilities: ['Summarise what needs your attention', 'Coordinate escalations across all AI managers', 'Keep publishing and financial actions approval-controlled'] },
  'affiliate-partnerships': { key: 'affiliate_partnerships', name: 'Affiliate Partnerships & Provider Manager', description: 'Provider onboarding, merchant relationships and connection readiness.', icon: Store, pages: [['Affiliate Providers', '/admin/providers'], ['Stores & Brands', '/admin'], ['API Integrations', '/admin/integrations'], ['Tracking Operations', '/admin/analytics']], responsibilities: ['Monitor provider and store connection readiness', 'Coordinate merchant and affiliate-source setup', 'Flag missing tracking or attribution configuration'] },
  'provider-compliance': { key: 'provider_compliance', name: 'Provider Policy & Compliance Manager', description: 'Provider policy monitoring and compliance recommendations.', icon: FileSearch, pages: [['Affiliate Providers', '/admin/providers'], ['Offers & Rewards', '/admin/offers'], ['Store Policies', '/admin']], responsibilities: ['Review provider terms and restrictions', 'Flag policy conflicts in offers and cashback rules', 'Prepare compliance recommendations for approval'] },
  'catalogue-merchandising': { key: 'catalogue_merchandising', name: 'Catalogue & Merchandising Manager', description: 'Product enrichment, catalogue quality and merchandising proposals.', icon: PackageSearch, pages: [['Products', '/admin/products'], ['Categories', '/admin/categories'], ['Approval Queue', '/admin/products?tab=approval'], ['Product Freshness', '/admin/product-freshness']], responsibilities: ['Classify products into the correct category path', 'Score duplicates, completeness and merchandising quality', 'Prepare products for the admin approval queue'] },
  'content-experience': { key: 'content_experience', name: 'Content & Experience Manager', description: 'Customer-facing content and creative recommendations.', icon: ListChecks, pages: [['Deals & Banners', '/admin/campaigns'], ['Products', '/admin/products'], ['Stores & Brands', '/admin']], responsibilities: ['Recommend products and offers for customer placement', 'Prepare customer-facing content requests', 'Keep approved content aligned with store and product rules'] },
  marketing: { key: 'marketing', name: 'Marketing Manager', description: 'Campaign and distribution recommendations.', icon: Megaphone, pages: [['Campaigns', '/admin/campaigns'], ['Ads Manager', '/admin/ads'], ['Ad Platforms', '/admin/ad-platforms'], ['Social Analytics', '/admin/social-analytics']], responsibilities: ['Score deals for paid and organic promotion', 'Recommend channel, audience and campaign priority', 'Prepare campaigns for admin approval before publishing'] },
  'finance-cashback-risk': { key: 'finance_cashback_risk', name: 'Finance, Cashback & Risk Manager', description: 'Commission, cashback, dispute and withdrawal analysis.', icon: CircleDollarSign, pages: [['Cashback Operations', '/admin/cashback-operations'], ['Financial Validation', '/admin/reconciliation'], ['Wallet & Payouts', '/admin/wallet'], ['Payout Operations', '/admin/payout-operations']], responsibilities: ['Flag cashback and commission exceptions', 'Score financial and payout risk for review', 'Never change balances or execute payouts directly'] },
  'fraud-security': { key: 'fraud_security', name: 'Fraud & Security Manager', description: 'Suspicious activity and affiliate abuse monitoring.', icon: ShieldCheck, pages: [['Access Reviews', '/admin/access-reviews'], ['Activity & Audit Log', '/admin/activity'], ['Reported Orders', '/admin/reported-orders']], responsibilities: ['Identify suspicious patterns and unusual activity', 'Prioritise cases for human investigation', 'Recommend holds without directly blocking money or accounts'] },
  'customer-operations': { key: 'customer_operations', name: 'Customer Operations & Trust Manager', description: 'Support triage and missing-order workflow recommendations.', icon: UsersRound, pages: [['Users', '/admin/users'], ['Orders & Earnings', '/admin/orders'], ['Support Centre', '/admin/support'], ['Notifications', '/admin/notifications']], responsibilities: ['Classify customer requests and route them correctly', 'Prioritise missing cashback and order issues', 'Escalate sensitive cases to the support team'] },
} as const;

const statusLabel = (status?: string | null) => status === 'not_connected' ? 'Not connected' : status === 'failed' ? 'Needs attention' : status === 'running' ? 'Running' : 'Idle';
const formatTime = (value?: string | null) => value ? new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Never run';

export default async function AiAgentPage({ params }: { params: Promise<{ agent: string }> }) {
  const slug = (await params).agent as keyof typeof agents;
  const config = agents[slug] ?? agents['ceo-operations'];
  const supabase = await createClient();
  const [{ data: agent }, { data: jobs }, { data: work }] = await Promise.all([
    supabase.from('ai_agents').select('*').eq('key', config.key).maybeSingle(),
    supabase.from('ai_jobs').select('id,job_type,status,created_at,latest_error,output').eq('agent_key', config.key).order('created_at', { ascending: false }).limit(6),
    supabase.from('ai_work_items').select('id,title,summary,risk_level,status,created_at').eq('status', 'pending_approval').order('created_at', { ascending: false }).limit(5),
  ]);
  const Icon = config.icon;
  const runtime = agent?.runtime_status ?? 'not_connected';
  return <main className="admin-v2 ai-admin"><AdminSidebar/><section className="admin-main"><header className="admin-top"><Bot size={21}/><b>AI Company</b><span className="dashboard-date">Agent workspace</span><Bell size={19}/><span className="avatar">SR</span></header><main className="ai-command agent-detail">
    <a className="agent-back" href="/admin/ai-agents">← Back to AI Agent Control Centre</a>
    <div className="agent-detail-head"><div><p>AI AGENT WORKSPACE</p><h1><Icon/> {config.name}</h1><span>{config.description}</span></div><span className={`agent-detail-status ${runtime}`}><i/>{statusLabel(runtime)}</span></div>
    <section className="agent-detail-grid"><article className="agent-detail-panel agent-purpose"><header><div><b>What this agent does</b><span>Its responsibilities inside Glonni</span></div></header><ul>{config.responsibilities.map(item=><li key={item}><CheckCircle2/>{item}</li>)}</ul></article><article className="agent-detail-panel"><header><div><b>Runtime status</b><span>Live status from the agent database</span></div></header><dl className="agent-detail-metrics"><div><dt>Last run</dt><dd>{formatTime(agent?.last_run_at)}</dd></div><div><dt>Success rate</dt><dd>{agent && Number(agent.success_count) + Number(agent.failure_count) > 0 ? `${Math.round(Number(agent.success_count) / (Number(agent.success_count) + Number(agent.failure_count)) * 100)}%` : 'No runs'}</dd></div><div><dt>Capability</dt><dd>{agent?.capability_status ? agent.capability_status.replaceAll('_', ' ') : 'Not connected'}</dd></div></dl>{agent?.latest_error && <p className="agent-detail-error"><AlertTriangle/> {agent.latest_error}</p>}</article></section>
    <section className="agent-detail-grid"><article className="agent-detail-panel"><header><div><b>Connected admin pages</b><span>Open the areas this agent monitors or prepares work for</span></div></header><div className="agent-page-links">{config.pages.map(([label, href])=><a href={href} key={href}><span>{label}</span><ArrowRight/></a>)}</div></article><article className="agent-detail-panel"><header><div><b>Agent workflow</b><span>Every action remains controlled by Glonni</span></div></header><div className="agent-flow"><span>Data received</span><ArrowRight/><span>Agent recommendation</span><ArrowRight/><span>Admin approval</span><ArrowRight/><span>Backend action</span></div><p className="agent-detail-note">This agent can recommend and prepare work. It cannot publish, change money or modify protected records without the configured approval flow.</p></article></section>
    <article className="agent-detail-panel agent-detail-jobs"><header><div><b>Recent work</b><span>Jobs and approval items handled by this agent</span></div><a href="/admin/ai-agents">View all activity →</a></header>{work?.length ? <div className="agent-work-list">{work.map(item=><div key={item.id}><span><b>{item.title}</b><small>{item.summary}</small></span><em>{item.risk_level} risk</em><a href="/admin/approvals">Review</a></div>)}</div> : jobs?.length ? <div className="agent-work-list">{jobs.map(job=><div key={job.id}><span><b>{job.job_type.replaceAll('_', ' ')}</b><small>{job.latest_error ?? job.output?.summary ?? 'Completed workflow run'}</small></span><em className={`job-${job.status}`}>{job.status}</em><small>{formatTime(job.created_at)}</small></div>)}</div> : <p className="agent-empty">No work has been recorded for this agent yet.</p>}</article>
  </main></section></main>;
}
