'use server';

import { createHash } from 'node:crypto';
import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';

async function requireAdmin(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();const {data:assurance}=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();if(!user||assurance?.currentLevel!=='aal2'||!['owner','admin'].includes(String(user.app_metadata?.admin_role)))redirect('/admin/login');return{supabase,user};}
const slugify=(value:string)=>value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');

export async function runProductDiscovery(form:FormData){
  const {supabase,user}=await requireAdmin();const query=String(form.get('query')??'').trim();const merchantId=String(form.get('merchantId')??'');const categoryId=String(form.get('categoryId')??'');const requestedReturn=String(form.get('returnTo')??'');const returnTo=requestedReturn.startsWith('/admin/stores/')?requestedReturn:'/admin/products?view=ai';const {data:globalSettings}=await supabase.from('platform_settings').select('work_controls').eq('id',1).maybeSingle();if(globalSettings?.work_controls?.pause_all===true||globalSettings?.work_controls?.ai_workflows===false)redirect(`${returnTo}${returnTo.includes('?')?'&':'?'}error=AI+workflows+are+paused+in+global+Settings.`);if(globalSettings?.work_controls?.product_intake===false)redirect(`${returnTo}${returnTo.includes('?')?'&':'?'}error=Automated+product+intake+is+stopped+in+global+Settings.`);if(query.length<5)redirect(`${returnTo}${returnTo.includes('?')?'&':'?'}error=Enter+a+clear+discovery+request.`);
  if(merchantId){const {data:merchant}=await supabase.from('merchants').select('id').eq('id',merchantId).maybeSingle();if(!merchant)redirect(`${returnTo}${returnTo.includes('?')?'&':'?'}error=Select+a+valid+connected+store.`);}
  const dedupeKey=createHash('sha256').update(`discovery:${query.toLowerCase()}:${merchantId}:${Math.floor(Date.now()/300000)}`).digest('hex');
  const {data:job,error}=await supabase.from('ai_jobs').insert({agent_key:'catalogue_merchandising',job_type:'product_discovery',input:{query,merchant_id:merchantId||null,category_id:categoryId||null},created_by:user.id,dedupe_key:dedupeKey,review_only:true}).select('id').single();if(error||!job)redirect(`${returnTo}${returnTo.includes('?')?'&':'?'}error=${encodeURIComponent(error?.code==='23505'?'The same discovery is already running.':error?.message??'Unable to create discovery job.')}`);
  const {data,error:invokeError}=await supabase.functions.invoke('ai-job-runner',{body:{job_id:job.id}});revalidatePath('/admin/products');revalidatePath('/admin/approvals');
  if(invokeError||data?.error)redirect(`${returnTo}${returnTo.includes('?')?'&':'?'}job=${job.id}&error=${encodeURIComponent(data?.error??invokeError?.message??'Discovery failed.')}`);
  redirect(`${returnTo}${returnTo.includes('?')?'&':'?'}job=${job.id}&success=Discovery+completed.+Review+every+candidate+before+creating+drafts.`);
}

export async function reviewDiscoveryCandidates(form:FormData){
  const {supabase,user}=await requireAdmin();const jobId=String(form.get('jobId')??'');const decision=String(form.get('decision')??'');const ids=form.getAll('candidateId').map(String).filter(Boolean);const note=String(form.get('note')??'').trim();const requestedReturn=String(form.get('returnTo')??'');const returnTo=requestedReturn.startsWith('/admin/stores/')?requestedReturn:`/admin/products?view=ai&job=${jobId}`;if(!ids.length)redirect(`${returnTo}${returnTo.includes('?')?'&':'?'}error=Select+at+least+one+candidate.`);if(!['approve','reject','research'].includes(decision))throw new Error('Invalid candidate decision.');
  const [{data:candidates},{data:job}]=await Promise.all([supabase.from('ai_discovery_candidates').select('*').eq('job_id',jobId).in('id',ids),supabase.from('ai_jobs').select('input').eq('id',jobId).maybeSingle()]);if((candidates??[]).length!==ids.length)throw new Error('One or more candidates are unavailable.');
  for(const candidate of candidates??[]){let productDraftId=candidate.product_draft_id;if(decision==='approve'&&!productDraftId){const preferredCategory=String(job?.input?.category_id??candidate.category_id??'')||null;let existingQuery=supabase.from('products').select('id').ilike('title',candidate.title).limit(1);if(candidate.brand)existingQuery=existingQuery.ilike('brand',candidate.brand);const {data:existing}=await existingQuery;productDraftId=existing?.[0]?.id??null;if(!productDraftId){const {data:product,error}=await supabase.from('products').insert({title:candidate.title,slug:`${slugify(candidate.title)||'discovered-product'}-${crypto.randomUUID().slice(0,8)}`,brand:candidate.brand||null,category_id:preferredCategory,image_url:candidate.image_url||null,is_active:false,manual_metadata:{source:'ai_discovery',discovery_job_id:jobId,discovery_candidate_id:candidate.id,merchant_id:job?.input?.merchant_id??null,model_code:candidate.model_code,source_urls:candidate.source_urls,matched_stores:candidate.matched_stores,missing_fields:candidate.missing_fields,workflow_step:'basic'}}).select('id').single();if(error||!product)throw new Error(error?.message??'Unable to create product draft.');productDraftId=product.id;}const merchantId=String(job?.input?.merchant_id??'');const destination=Array.isArray(candidate.source_urls)?String(candidate.source_urls[0]??''):'';if(merchantId&&destination.startsWith('http')){const {data:existingOffer}=await supabase.from('offers').select('id').eq('product_id',productDraftId).eq('merchant_id',merchantId).limit(1);if(!existingOffer?.length){const raw=candidate.raw_candidate&&typeof candidate.raw_candidate==='object'?candidate.raw_candidate:{};await supabase.from('offers').insert({product_id:productDraftId,merchant_id:merchantId,destination_url:destination,current_price:Number(raw.current_price??raw.price)||null,list_price:Number(raw.list_price)||null,status:'draft'});}}}
    const status=decision==='approve'?'approved_to_draft':decision==='reject'?'rejected':'needs_research';const now=new Date().toISOString();const {error}=await supabase.from('ai_discovery_candidates').update({status,reviewer_note:note||null,reviewed_by:user.id,reviewed_at:now,product_draft_id:productDraftId,updated_at:now}).eq('id',candidate.id).eq('job_id',jobId);if(error)throw new Error(error.message);
    await supabase.from('audit_events').insert({actor_id:user.id,event_type:`ai_discovery_candidate_${status}`,entity_type:'ai_discovery_candidate',entity_id:candidate.id,source:'admin',metadata:{job_id:jobId,product_draft_id:productDraftId}});
  }
  revalidatePath('/admin/products');revalidatePath('/admin/approvals');redirect(`${returnTo}${returnTo.includes('?')?'&':'?'}success=${decision==='approve'?'Selected+candidates+were+created+as+global+inactive+product+drafts.':'Candidate+decisions+were+recorded.'}`);
}
