import { AdminSidebar } from "@/components/admin-sidebar";
import { Bell, Boxes, CheckCircle2, FolderTree, Store, Tag } from 'lucide-react';
import { createClient } from '@/lib/supabase/server';

export const dynamic = 'force-dynamic';

export default async function ProductsPage() {
  const supabase = await createClient();
  const { data: productData } = await supabase.from('products').select('id,title,slug,brand,is_active,categories(name)').order('title');
  const products = productData ?? [];
  const { count: offerCount } = await supabase.from('offers').select('*', { count: 'exact', head: true }).eq('status', 'active');

  return <main className="admin-v2"><AdminSidebar/><section className="admin-main"><header className="admin-top"><Boxes size={21} /><b>Products</b><span className="dashboard-date">Normalized product catalogue · preview mode</span><Bell size={19} /><span className="avatar">SR</span></header><main className="admin-content"><div className="admin-title"><div><p>CATALOGUE MANAGEMENT</p><h1>Products</h1><span>One product record can hold offers from multiple merchants and providers.</span></div><button className="add-store" disabled>＋ Add product</button></div><p className="preview-note">Product creation is intentionally locked until secure admin roles return. Existing products and offers are live preview data only.</p><section className="admin-stats"><article><Boxes /><div><small>Products</small><b>{products.length}</b><em>Normalized records</em></div></article><article><Tag /><div><small>Active offers</small><b>{offerCount ?? 0}</b><em>Across merchants</em></div></article><article><Store /><div><small>Multi-store ready</small><b>Yes</b><em>Product → offers model</em></div></article><article><FolderTree /><div><small>Categories</small><b>Mapped</b><em>Discovery-ready</em></div></article><article><CheckCircle2 /><div><small>Quality review</small><b>Ready</b><em>Before publishing</em></div></article></section><section className="admin-grid"><article className="store-table"><div className="table-head"><div><a className="current">All products</a><a>Active</a><a>Missing offer</a></div></div><div className="table-scroll"><table><thead><tr><th>PRODUCT</th><th>BRAND</th><th>CATEGORY</th><th>URL HANDLE</th><th>OFFER MODEL</th><th>STATUS</th></tr></thead><tbody>{products.map((product) => <tr key={product.id}><td><span><strong>{product.title}</strong><small>Images, description &amp; specifications</small></span></td><td>{product.brand || 'Unbranded'}</td><td>{(product.categories as { name?: string } | null)?.name || 'Uncategorised'}</td><td>/product/{product.slug}</td><td>Compare merchant offers</td><td><em className={product.is_active ? 'status-active' : 'status-paused'}>{product.is_active ? 'Active' : 'Inactive'}</em></td></tr>)}</tbody></table></div><footer>Products remain provider-neutral. Merchant price, coupon and cashback belong to individual offers.</footer></article><aside className="admin-right"><article><h2>Product completeness</h2><p>Core record <span>Ready</span></p><p>Offer comparisons <span>Enabled</span></p><p>Image coverage <span>Mock assets</span></p></article><article><h2>Publishing checks</h2><p className="activity">No duplicate product warning<small>Normalised product model</small></p><p className="activity">Affiliate details stay on offers<small>Correct separation of responsibilities</small></p></article></aside></section></main></section></main>;
}
