import type { Metadata } from 'next';
import { SiteFooter } from '@/components/site-footer';
import { AdminMockMode } from '@/components/admin-mock-mode';
import { ActivityTracker } from '@/components/activity-tracker';
import './globals.css';
import './admin-sidebar.css';
import './admin-theme.css';
import './admin-stores.css';
import './admin-categories.css';
import './ai-command.css';
import './auth.css';
import './product-page.css';
import './admin-products.css';
import './admin-products-cleanup.css';
import './admin-product-detail.css';
import './admin-interactions.css';
import './customer-states.css';
import './customer-accessibility.css';
import './admin-dashstack-theme.css';
import './admin-support.css';
export const metadata: Metadata = { title: 'Glonni | Discover better deals', description: 'Provider-neutral product discovery and deals.' };
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) { return <html lang="en"><body><ActivityTracker/><AdminMockMode>{children}</AdminMockMode><SiteFooter/></body></html>; }
