'use client';
import { useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';

export function AdminMfaEnroll({ next = '/admin/dashboard' }: { next?: string }) {
  const started = useRef(false); const router = useRouter(); const [factorId,setFactorId]=useState(''); const [qr,setQr]=useState(''); const [secret,setSecret]=useState(''); const [code,setCode]=useState(''); const [error,setError]=useState('');
  useEffect(()=>{if(started.current)return;started.current=true;(async()=>{const supabase=createClient();const {data:list}=await supabase.auth.mfa.listFactors();if(list?.totp.some(f=>f.status==='verified')){router.replace(`/admin/mfa/challenge?next=${encodeURIComponent(next)}`);return;}for(const factor of list?.totp??[]){if(factor.status==='unverified')await supabase.auth.mfa.unenroll({factorId:factor.id});}const {data,error}=await supabase.auth.mfa.enroll({factorType:'totp',friendlyName:'Glonni Admin'});if(error){setError(error.message);return;}setFactorId(data.id);setQr(data.totp.qr_code);setSecret(data.totp.secret);})();},[next,router]);
  async function verify(e:React.FormEvent){e.preventDefault();setError('');const supabase=createClient();const challenge=await supabase.auth.mfa.challenge({factorId});if(challenge.error){setError(challenge.error.message);return;}const result=await supabase.auth.mfa.verify({factorId,challengeId:challenge.data.id,code});if(result.error){setError('The code is incorrect. Wait for a new code and try again.');return;}await supabase.auth.refreshSession();await supabase.functions.invoke('admin-invite-user',{body:{mode:'complete_onboarding'}});router.replace(next);router.refresh();}
  return <section className="admin-auth-card mfa-card"><p className="eyebrow">MANDATORY 2FA</p><h1>Connect Google Authenticator</h1><ol><li>Open Google Authenticator or another TOTP app.</li><li>Scan this QR code.</li><li>Enter the current six-digit code.</li></ol>{error&&<div className="auth-notice error">{error}</div>}{qr?<><img className="mfa-qr" src={qr} alt="Authenticator QR code"/><details><summary>Cannot scan?</summary><code>{secret}</code></details><form onSubmit={verify} className="auth-form"><label>Six-digit code<input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" pattern="[0-9]{6}" autoComplete="one-time-code" required/></label><button disabled={code.length!==6}>Verify and enter Admin</button></form></>:<p>Preparing secure enrollment…</p>}</section>;
}
