"use client";

import { useMemo, useState } from "react";
import { AlertTriangle, Check, ChevronLeft, ChevronRight, ExternalLink, Filter, ImageOff, Search, Sparkles, Store } from "lucide-react";

type Merchant = { id: string; name: string; logo_url?: string | null };
type Category = { id: string; name: string; treePath?: string };
type Candidate = { id: number; name: string; audience: string; model: string; price: number; cashback: string; confidence: number; complete: number; status: string; tone: string; stores: number };
const names = ["Classic Clog", "Bayaband Clog", "Crocband Clog", "LiteRide 360 Clog", "Classic Sandal 2.0", "Brooklyn Low Wedge", "Kids Classic Clog", "Kids Bayaband Clog", "Mellow Recovery Clog", "Echo Clog", "Classic Platform Clog", "Baya Clog", "Swiftwater Sandal", "Getaway Platform Flip", "Miami Toe Loop Sandal", "Crush Clog", "Duet Max II Clog", "All-Terrain Clog", "Classic Cozzzy Sandal", "Electro Kids Clog", "Cutie Clog", "Tulum Sandal", "LiteRide 360 Sandal", "Off Court Clog", "Handle It Rain Boot"];
const candidates: Candidate[] = names.map((name, index) => ({ id: index + 1, name, model: `CR-${String(20100 + index)}`, audience: index % 3 === 0 ? "Men" : index % 3 === 1 ? "Women" : "Kids", price: 1795 + (index % 7) * 300, cashback: `Up to ${5 + (index % 4)}%`, confidence: 72 + (index * 7) % 27, complete: 68 + (index * 9) % 31, status: index % 7 === 4 ? "Missing image" : index % 5 === 2 ? "Review category" : index % 4 === 3 ? "Verify offer" : "Ready to publish", tone: ["black", "navy", "white", "pink", "sand", "blue"][index % 6], stores: 2 + index % 5 }));
const money = (value: number) => `₹${value.toLocaleString("en-IN")}`;

export function AiDiscoveryWorkspace({ merchants, categories }: { merchants: Merchant[]; categories: Category[] }) {
  const [command, setCommand] = useState("Fetch the crocs sandals and its models from available affiliate sources in our website. only top 25 models for men, women, kids.");
  const [ran, setRan] = useState(true), [audience, setAudience] = useState("All"), [status, setStatus] = useState("All"), [query, setQuery] = useState("");
  const [selected, setSelected] = useState<number[]>([1, 2, 4, 6, 9, 10]), [review, setReview] = useState<Candidate>(candidates[0]);
  const rows = useMemo(() => candidates.filter((item) => (audience === "All" || item.audience === audience) && (status === "All" || item.status === status) && (!query || `${item.name} ${item.model}`.toLowerCase().includes(query.toLowerCase()))), [audience, status, query]);
  const toggle = (id: number) => setSelected((current) => current.includes(id) ? current.filter((x) => x !== id) : [...current, id]);
  const category = categories.find((item) => /footwear|sandal/i.test(item.treePath || item.name));
  return <section className="ai-discovery-shell">
    <header className="ai-discovery-heading"><div><p>AI DISCOVERY</p><h2>Discover products with AI</h2><span>Find products from connected sources, verify every match, then choose what enters your catalogue.</span></div><button type="button">Discovery history</button></header>
    <div className="ai-command-bar"><Sparkles/><input value={command} onChange={(e)=>setCommand(e.target.value)} aria-label="AI discovery command"/><select aria-label="Affiliate source"><option>All connected sources</option>{merchants.map((item)=><option key={item.id}>{item.name}</option>)}</select><button type="button" onClick={()=>setRan(true)} disabled={!command.trim()}><Check/>{ran ? "Fetch complete" : "Fetch products"}</button></div>
    {ran && <>
      <div className="ai-discovery-kpis"><article><b>25</b><span>Products found</span></article><article><b>18</b><span>Exact matches</span></article><article className="warn"><b>7</b><span>Need review</span></article><article><b>{Math.max(merchants.length, 3)}</b><span>Connected stores</span></article></div>
      <nav className="ai-audience-tabs">{["All","Men","Women","Kids"].map((item)=><button className={audience===item?"active":""} onClick={()=>setAudience(item)} key={item}>{item} <b>{item==="All"?25:candidates.filter(x=>x.audience===item).length}</b></button>)}<button className={status==="Review category"?"active":""} onClick={()=>setStatus(status==="Review category"?"All":"Review category")}>Needs review <b>7</b></button></nav>
      <div className="ai-discovery-filters"><label><Search/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search products or models…"/></label><select><option>All categories</option>{categories.map((item)=><option key={item.id}>{item.treePath || item.name}</option>)}</select><select><option>All stores</option>{merchants.map((item)=><option key={item.id}>{item.name}</option>)}</select><select><option>All confidence levels</option><option>High confidence</option><option>Medium confidence</option></select><select value={status} onChange={(e)=>setStatus(e.target.value)}><option value="All">Any information status</option><option>Missing image</option><option>Review category</option><option>Verify offer</option><option>Ready to publish</option></select><button><Filter/>Filters</button></div>
      <div className="ai-discovery-body"><article className="ai-results-card"><div className="ai-results-scroll"><table><thead><tr><th><input type="checkbox" checked={rows.length>0&&rows.every(x=>selected.includes(x.id))} onChange={()=>setSelected(rows.every(x=>selected.includes(x.id))?selected.filter(id=>!rows.some(x=>x.id===id)):[...new Set([...selected,...rows.map(x=>x.id)])])}/></th><th>PRODUCT & MODEL</th><th>AUDIENCE</th><th>CONNECTED STORES</th><th>BEST PRICE</th><th>CASHBACK</th><th>MATCH</th><th>COMPLETENESS</th><th>STATUS</th><th>ACTION</th></tr></thead><tbody>{rows.map((item)=><tr className={selected.includes(item.id)?"selected":""} key={item.id}><td><input type="checkbox" checked={selected.includes(item.id)} onChange={()=>toggle(item.id)}/></td><td><span className={`ai-croc-thumb ${item.tone}`}>◒</span><span><b>{item.name}</b><small>{item.model}</small></span></td><td>{item.audience}</td><td><span className="ai-store-stack">{merchants.slice(0,Math.min(3,item.stores)).map((store)=><i title={store.name} key={store.id}>{store.logo_url?<img src={store.logo_url} alt=""/>:store.name[0]}</i>)}{item.stores>3&&<em>+{item.stores-3}</em>}</span></td><td><b>{money(item.price)}</b></td><td>{item.cashback}</td><td><span className={item.confidence>84?"ai-high":"ai-medium"}>{item.confidence>84?"High":"Medium"} · {item.confidence}%</span></td><td><span className="ai-complete"><b>{item.complete}%</b><i><span style={{width:`${item.complete}%`}}/></i></span></td><td><span className={`ai-candidate-status ${item.status.toLowerCase().replaceAll(" ","-")}`}>{item.status}</span></td><td><button type="button" onClick={()=>setReview(item)}>Review</button></td></tr>)}</tbody></table></div><footer><span>Showing {rows.length} of 25 candidates</span><span><button><ChevronLeft/></button>1–25 of 25<button><ChevronRight/></button></span></footer></article>
      <aside className="ai-review-drawer"><header><div><small>PRODUCT REVIEW</small><h3>{review.name}</h3><p>{review.model} · Crocs</p></div><span className="ai-high">High match confidence</span></header><div className={`ai-review-image ${review.tone}`}>◒</div><section><h4>Assigned catalogue path <button>Edit</button></h4><p>{category?.treePath || "Fashion › Footwear › Sandals & Clogs"}</p></section><section><h4>Variants <button>View all</button></h4><div className="ai-variant-row">{["Black","White","Navy","Slate grey","Pink"].map((x)=><span key={x}><i className={x.toLowerCase().replace(" ","")}/><small>{x}</small></span>)}</div></section><section><h4>Matched offers <small><i/> Verified affiliate offer</small></h4><div className="ai-matched-offers">{merchants.slice(0,3).map((store,index)=><p key={store.id}><Store/><b>{store.name}</b><em>Verified</em><span>{money(review.price+index*105)}</span><span>{review.cashback}</span><span>In stock</span><ExternalLink/></p>)}</div></section><section className="ai-source-confidence"><h4>Source confidence <b>{review.confidence}%</b></h4><i><span style={{width:`${review.confidence}%`}}/></i></section>{review.status!=="Ready to publish"&&<div className="ai-review-warning"><AlertTriangle/><span><b>{review.status}</b><small>Review this information before publishing.</small></span></div>}<footer><button>Edit details</button><button className="approve">Approve & publish</button><button className="reject">Reject</button></footer></aside></div>
      {selected.length>0&&<footer className="ai-bulk-bar"><b>{selected.length} products selected</b><span/><button>Reject</button><button>Send for editing</button><button className="approve">Approve & publish {selected.length}</button></footer>}
    </>}
  </section>;
}
