'use client';
import {FormEvent,useMemo,useState,useTransition} from 'react';
import {useRouter} from 'next/navigation';
import {ChevronDown,ChevronLeft,ChevronRight,Copy,Eye,GripVertical,LayoutTemplate,LockKeyhole,Monitor,MoreHorizontal,Plus,Save,Smartphone,Tablet,Trash2} from 'lucide-react';
import {addBuilderBlock,createBuilderPage,deleteBuilderPage,duplicateBuilderPage,reorderBuilderBlocks,setBuilderPageStatus,updateBuilderBlock,updateBuilderPage} from '@/app/admin/cms/actions';
import {systemPageDefinitions,systemPageSlug,type SystemPageDefinition} from '@/lib/system-pages';
type Page={id:string;title:string;slug:string;description:string|null;status:string;device_visibility:string;updated_at:string};
type Block={id:string;page_id:string;block_type:string;title:string|null;body:string|null;cta_label:string|null;cta_href:string|null;image_url:string|null;config:Record<string,string>|null;display_order:number;device_visibility:string;is_active:boolean};
type Popup={id:string;name:string;title:string;status:string;trigger_type:string;target_scope:string;updated_at:string};
const presets=[['hero','Hero banner'],['banner','Promotional banner'],['category_grid','Category collection'],['store_rail','Store collection'],['product_rail','Product collection'],['text','Text & image'],['trust_strip','Cashback announcement'],['cta','Call to action'],['faq','FAQs']];
const nice=(v:string)=>v.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const status=(v:string)=>v==='published'?'Published':v==='pending'?'Awaiting approval':v==='paused'?'Paused':'Draft';
export function WebsiteBuilder({pages,blocks,popups,previewRoutes={}}:{pages:Page[];blocks:Block[];popups:Popup[];previewRoutes?:Record<string,string>}){
 const router=useRouter(),[busy,startTransition]=useTransition(),[selection,setSelection]=useState('system:home'),[blockId,setBlockId]=useState<string|null>(null),[device,setDevice]=useState<'desktop'|'tablet'|'mobile'>('desktop'),[library,setLibrary]=useState(false),[libraryTab,setLibraryTab]=useState<'system'|'custom'>('system'),[create,setCreate]=useState(false),[sectionLibrary,setSectionLibrary]=useState(false),[pageSettings,setPageSettings]=useState(false),[slot,setSlot]=useState('page_end');
 const customPages=pages.filter(p=>!p.slug.startsWith('system-')),systemKey=selection.startsWith('system:')?selection.slice(7):null,systemPage=systemPageDefinitions.find(p=>p.key===systemKey)??null,page=systemPage?pages.find(p=>p.slug===systemPageSlug(systemPage.key))??null:pages.find(p=>p.id===selection)??null;
 const pageBlocks=useMemo(()=>page?blocks.filter(b=>b.page_id===page.id&&b.is_active).sort((a,b)=>a.display_order-b.display_order):[],[blocks,page]),active=pageBlocks.find(b=>b.id===blockId)??pageBlocks[0]??null,slots=systemPage?.slots??[{key:'page_end',label:'Page content'}],title=systemPage?.title??page?.title??'Choose a page',route=systemPage?(previewRoutes[systemPage.key]??systemPage.route):(page?`/pages/${page.slug}`:'/');
 const run=(fn:()=>Promise<void>)=>startTransition(async()=>{await fn();router.refresh()}),choose=(v:string)=>{setSelection(v);setBlockId(null);setLibrary(false)},openSections=()=>{setSlot(slots[0]?.key??'page_end');setSectionLibrary(true)};
 const add=(type:string)=>{const f=new FormData();if(page)f.set('pageId',page.id);if(systemPage)f.set('systemKey',systemPage.key);f.set('type',type);f.set('slot',slot);f.set('title',`${nice(type)} section`);run(async()=>{await addBuilderBlock(f);setSectionLibrary(false)})};
 const move=(id:string,d:number)=>{if(!page)return;const list=[...pageBlocks],from=list.findIndex(b=>b.id===id),to=from+d;if(to<0||to>=list.length)return;[list[from],list[to]]=[list[to],list[from]];const f=new FormData();f.set('pageId',page.id);f.set('blockIds',JSON.stringify(list.map(b=>b.id)));run(()=>reorderBuilderBlocks(f))};
 const save=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(active&&page)run(()=>updateBuilderBlock(new FormData(e.currentTarget)))},createPage=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();run(async()=>{await createBuilderPage(new FormData(e.currentTarget));setCreate(false)})},savePage=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();run(async()=>{await updateBuilderPage(new FormData(e.currentTarget));setPageSettings(false)})};
 const duplicatePage=(id:string)=>{const f=new FormData();f.set('id',id);run(()=>duplicateBuilderPage(f))},deletePage=(id:string)=>{if(!confirm('Delete this custom page and all of its sections?'))return;const f=new FormData();f.set('id',id);run(async()=>{await deleteBuilderPage(f);setSelection('system:home');setLibrary(false)})},publish=(action:string)=>{if(!page)return;const f=new FormData();f.set('id',page.id);f.set('action',action);run(()=>setBuilderPageStatus(f))};
 return <>
 <header className="builder-toolbar"><div className="builder-toolbar-title"><LayoutTemplate/><b>Page Manager</b><button className="page-switch" onClick={()=>setLibrary(true)}>{title}<ChevronDown/></button></div><div className="preview-devices">{([['desktop',Monitor],['tablet',Tablet],['mobile',Smartphone]] as const).map(([key,Icon])=><button key={key} aria-label={`${key} preview`} className={device===key?'selected':''} onClick={()=>setDevice(key)}><Icon/></button>)}</div><div className="builder-toolbar-actions">{!systemPage&&page&&<button className="page-settings-button" onClick={()=>setPageSettings(true)}>Page settings</button>}<a href={route} target="_blank" className="preview-link"><Eye/>Open page</a><button className="publish-button" disabled={!page||busy} onClick={()=>publish(page?.status==='draft'?'submit':page?.status==='pending'?'publish':page?.status==='published'?'pause':'submit')}>{busy?'Saving…':!page?'Add a section first':page.status==='published'?'Pause additions':page.status==='pending'?'Publish additions':'Submit additions'}</button></div></header>
 <div className="builder-workspace"><aside className="builder-sections"><div className="builder-tabs"><button className="active">Editable sections</button><button onClick={()=>setLibrary(true)}>Pages</button></div>{systemPage&&<div className="system-page-note"><LockKeyhole/><div><b>Core page is protected</b><span>Add promotions only in approved positions.</span></div></div>}<div className="section-list">{pageBlocks.length?pageBlocks.map(b=><button className={`section-row ${active?.id===b.id?'selected':''}`} key={b.id} onClick={()=>setBlockId(b.id)}><GripVertical/><span className={`section-thumb ${b.block_type}`}/><span><b>{b.title||nice(b.block_type)}</b><small>{slots.find(x=>x.key===(b.config?.slot??'page_end'))?.label??nice(b.block_type)}</small></span><span className="section-move"><i onClick={e=>{e.stopPropagation();move(b.id,-1)}}><ChevronLeft/></i><i onClick={e=>{e.stopPropagation();move(b.id,1)}}><ChevronRight/></i></span></button>):<div className="empty-sections"><LayoutTemplate/><b>No added sections</b><span>The customer page remains unchanged until you add something.</span></div>}</div><div className="add-section-wrap"><button className="add-section" onClick={openSections}><Plus/>Add section</button></div></aside>
 <main className={`builder-canvas-pane ${device}`}><p className="canvas-device-label">{device} preview · {systemPage?'live customer page':page?status(page.status):'custom page'}</p>{systemPage?<div className="system-preview-frame"><div className="canvas-browser"><i/><i/><i/><span>glonni-affiliate.vercel.app{route}</span></div><iframe key={`${route}-${device}`} src={route} title={`${title} customer preview`}/></div>:<CustomCanvas page={page} blocks={pageBlocks} active={active} select={setBlockId} add={openSections}/>}</main>
 <aside className="builder-inspector">{active&&page?<Inspector block={active} pageId={page.id} slots={slots} save={save} busy={busy}/>:<div className="inspector-empty"><LayoutTemplate/><h2>{systemPage?'Add a safe section':'Select a section'}</h2><p>{systemPage?'The centre shows the real customer page. Add content in one of its approved positions.':'Select a custom section to edit it.'}</p>{systemPage&&<div className="locked-section-list"><b>Protected page areas</b>{systemPage.lockedSections.map(item=><span key={item}><LockKeyhole/>{item}</span>)}</div>}</div>}</aside></div>
 <footer className="builder-status"><span><i/> {busy?'Saving changes…':'Ready'}</span><span><Save/>{systemPage?'Core customer functionality is protected':'Every save creates a version snapshot'}</span><button onClick={()=>setLibrary(true)}>Page library <ChevronDown/></button></footer>
 {library&&<div className="builder-modal-backdrop" onClick={()=>setLibrary(false)}><section className="builder-library" onClick={e=>e.stopPropagation()}><header><div><p>WEBSITE PAGES</p><h2>Page Manager</h2><span>Open an existing customer page or create a separate campaign page.</span></div><button className="publish-button" onClick={()=>{setLibrary(false);setCreate(true)}}><Plus/>Create custom page</button></header><nav className="page-library-tabs"><button className={libraryTab==='system'?'active':''} onClick={()=>setLibraryTab('system')}>Existing website pages <b>{systemPageDefinitions.length}</b></button><button className={libraryTab==='custom'?'active':''} onClick={()=>setLibraryTab('custom')}>Custom pages <b>{customPages.length}</b></button></nav>{libraryTab==='system'?<div className="page-library-grid">{systemPageDefinitions.map(item=><SystemPageCard key={item.key} page={item} backing={pages.find(p=>p.slug===systemPageSlug(item.key))} selected={selection===`system:${item.key}`} choose={()=>choose(`system:${item.key}`)}/>)}</div>:<div className="page-library-grid">{customPages.map(p=><article className={`page-card ${p.id===selection?'active':''}`} key={p.id}><button className="open-page" onClick={()=>choose(p.id)}><span className="page-card-preview"><b>Glonni</b><i/><i/><i/></span><strong>{p.title}</strong><small>/pages/{p.slug}</small><em className={p.status}>{status(p.status)}</em></button><div className="page-card-actions"><button onClick={()=>{setSelection(p.id);setLibrary(false);setPageSettings(true)}}>Settings</button><button onClick={()=>duplicatePage(p.id)}>Duplicate</button><button className="delete-page" onClick={()=>deletePage(p.id)}>Delete</button></div></article>)}{!customPages.length&&<div className="library-empty"><LayoutTemplate/><b>No custom pages yet</b><span>Your existing pages are available in the first tab.</span></div>}</div>}<div className="popup-summary"><b>{popups.length} popup drafts</b><span> can be connected to campaigns after review.</span></div></section></div>}
 {sectionLibrary&&<div className="builder-modal-backdrop" onClick={()=>setSectionLibrary(false)}><section className="section-library" onClick={e=>e.stopPropagation()}><p>SECTION LIBRARY</p><h2>Add to {title}</h2><span>Choose the position and content type.</span><label className="section-slot-label">Display position<select value={slot} onChange={e=>setSlot(e.target.value)}>{slots.map(item=><option value={item.key} key={item.key}>{item.label}</option>)}</select></label><div>{presets.map(([type,label])=><button key={`${type}-${label}`} onClick={()=>add(type)}><i className={`section-thumb ${type}`}/><b>{label}</b><small>Add section</small><Plus/></button>)}</div></section></div>}
 {create&&<div className="builder-modal-backdrop" onClick={()=>setCreate(false)}><form className="create-page-modal" onSubmit={createPage} onClick={e=>e.stopPropagation()}><p>NEW CUSTOM PAGE</p><h2>Create a campaign page</h2><span>This does not alter an existing system page.</span><label>Page name<input required name="title"/></label><label>Page URL<input name="slug"/></label><label>Short introduction<input name="description"/></label><label>Visibility<select name="device"><option value="all">Desktop + mobile</option><option value="desktop">Desktop only</option><option value="mobile">Mobile only</option></select></label><div><button type="button" onClick={()=>setCreate(false)}>Cancel</button><button className="publish-button" disabled={busy}>Create draft</button></div></form></div>}
 {pageSettings&&page&&!systemPage&&<div className="builder-modal-backdrop" onClick={()=>setPageSettings(false)}><form className="create-page-modal" onSubmit={savePage} onClick={e=>e.stopPropagation()}><p>PAGE SETTINGS</p><h2>Edit {page.title}</h2><input type="hidden" name="id" value={page.id}/><label>Page name<input required name="title" defaultValue={page.title}/></label><label>Page URL<input name="slug" defaultValue={page.slug}/></label><label>Short introduction<input name="description" defaultValue={page.description??''}/></label><label>Visibility<select name="device" defaultValue={page.device_visibility}><option value="all">Desktop + mobile</option><option value="desktop">Desktop only</option><option value="mobile">Mobile only</option></select></label><div><button type="button" onClick={()=>setPageSettings(false)}>Cancel</button><button className="publish-button">Save page settings</button></div></form></div>}
 </>;
}
function SystemPageCard({page,backing,selected,choose}:{page:SystemPageDefinition;backing?:Page;selected:boolean;choose:()=>void}){return <article className={`page-card system-page-card ${selected?'active':''}`}><button className="open-page" onClick={choose}><span className="page-card-preview system"><b>Glonni</b><i/><i/><i/></span><strong>{page.title}</strong><small>{page.route}</small><em className={backing?.status??'published'}>{backing?`${status(backing.status)} additions`:'Live · no additions'}</em></button><div className="system-card-lock"><LockKeyhole/>Core sections protected</div></article>}
function CustomCanvas({page,blocks,active,select,add}:{page:Page|null;blocks:Block[];active:Block|null;select:(id:string)=>void;add:()=>void}){return <div className="page-canvas"><div className="canvas-browser"><i/><i/><i/><span>glonni-affiliate.vercel.app{page?`/pages/${page.slug}`:''}</span></div><div className="canvas-header"><b>Glonni</b><div>Search stores, categories or deals</div><nav>Stores　 Deals　 Profile</nav></div><div className="canvas-page-heading"><p>CUSTOM PAGE</p><h1>{page?.title??'Create your first page'}</h1>{page?.description&&<span>{page.description}</span>}</div>{blocks.length?blocks.map(b=><CanvasBlock key={b.id} block={b} selected={active?.id===b.id} select={()=>select(b.id)}/>):<section className="canvas-starter"><LayoutTemplate/><h2>Start with a visual section</h2><p>Add a hero, banner, collection or trust message.</p><button onClick={add}><Plus/>Add a section</button></section>}<div className="canvas-footer">Secure redirects · Clear cashback eligibility · Help when you need it</div></div>}
function CanvasBlock({block,selected,select}:{block:Block;selected:boolean;select:()=>void}){const c=block.config??{},hero=block.block_type==='hero';return <section className={`canvas-section ${block.block_type} ${selected?'selected':''}`} style={{backgroundColor:c.background||'#fff','--accent':c.accent||'#1454d9'} as React.CSSProperties} onClick={select}><div className="canvas-selection-tools"><span><GripVertical/>{nice(block.block_type)}</span><button>Edit</button><button><Copy/></button><button className="danger"><Trash2/></button></div>{hero?<div className="canvas-hero"><div><p>GLONNI SHOPPING DISCOVERY</p><h2>{block.title}</h2><span>{block.body||'Add clear customer-facing campaign copy.'}</span>{block.cta_label&&<button>{block.cta_label}<ChevronRight/></button>}</div><div className="hero-visual"><div className="cashback-bubble">✓ Approved content</div><div className="shopping-bag">G</div></div></div>:<><h2>{block.title}</h2><p className="canvas-copy">{block.body||'Add clear supporting information.'}</p>{block.cta_label&&<button className="canvas-cta">{block.cta_label}</button>}</>}</section>}
function Inspector({block,pageId,slots,save,busy}:{block:Block;pageId:string;slots:{key:string;label:string}[];save:(e:FormEvent<HTMLFormElement>)=>void;busy:boolean}){const c=block.config??{};return <form className="inspector-form" onSubmit={save}><header><div><p>SECTION SETTINGS</p><h2>{block.title||nice(block.block_type)}</h2></div><MoreHorizontal/></header><nav><button type="button" className="active">Content</button><button type="button">Style</button><button type="button">Action</button><button type="button">Visibility</button></nav><input type="hidden" name="id" value={block.id}/><input type="hidden" name="pageId" value={pageId}/><label>Display position<select name="slot" defaultValue={c.slot??'page_end'}>{slots.map(item=><option value={item.key} key={item.key}>{item.label}</option>)}</select></label><label>Heading<input name="title" defaultValue={block.title??''}/></label><label>Supporting copy<textarea name="body" defaultValue={block.body??''} rows={4}/></label><label>Button label<input name="ctaLabel" defaultValue={block.cta_label??''}/></label><label>Internal destination<input name="ctaHref" defaultValue={block.cta_href??''} placeholder="/deals"/></label><label>Campaign image URL<input name="imageUrl" defaultValue={block.image_url??''}/></label><fieldset><legend>Section style</legend><div className="color-pair"><label>Accent<input name="accent" type="color" defaultValue={c.accent||'#1454d9'}/></label><label>Background<input name="background" type="color" defaultValue={c.background||'#ffffff'}/></label></div><label>Layout<select name="layout" defaultValue={c.layout||'standard'}><option value="standard">Standard</option><option value="split">Split visual</option><option value="centered">Centered</option></select></label><label>Button style<select name="buttonStyle" defaultValue={c.buttonStyle||'solid'}><option value="solid">Solid</option><option value="outline">Outline</option><option value="soft">Soft</option></select></label></fieldset><fieldset><legend>Device visibility</legend><label className="radio-row"><input type="radio" name="device" value="all" defaultChecked={block.device_visibility==='all'}/>Desktop + mobile</label><label className="radio-row"><input type="radio" name="device" value="desktop" defaultChecked={block.device_visibility==='desktop'}/>Desktop only</label><label className="radio-row"><input type="radio" name="device" value="mobile" defaultChecked={block.device_visibility==='mobile'}/>Mobile only</label></fieldset><button className="save-section" disabled={busy}><Save/>{busy?'Saving…':'Save section'}</button></form>}
