'use client';

import { FormEvent, useMemo, useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { ChevronDown, ChevronLeft, ChevronRight, Copy, Eye, GripVertical, LayoutTemplate, Monitor, MoreHorizontal, Plus, Save, Smartphone, Tablet, Trash2, Undo2 } from 'lucide-react';
import { addBuilderBlock, createBuilderPage, deleteBuilderPage, duplicateBuilderPage, reorderBuilderBlocks, setBuilderPageStatus, updateBuilderBlock, updateBuilderPage } from '@/app/admin/cms/actions';

type Page={id:string;title:string;slug:string;description:string|null;status:string;device_visibility:string;updated_at:string};
type Block={id:string;page_id:string;block_type:string;title:string|null;body:string|null;cta_label:string|null;cta_href:string|null;image_url:string|null;config:Record<string,string>|null;display_order:number;device_visibility:string;is_active:boolean};
type Popup={id:string;name:string;title:string;status:string;trigger_type:string;target_scope:string;updated_at:string};
const presets=[['hero','Hero banner'],['banner','Brand carousel'],['category_grid','Shop by category'],['store_rail','Shop by stores'],['product_rail','Trending deals'],['product_rail','Price drops'],['trust_strip','Trust strip']];
const nice=(v:string)=>v.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const status=(v:string)=>v==='published'?'Published':v==='pending'?'Awaiting approval':v==='paused'?'Paused':'Draft';

export function WebsiteBuilder({pages,blocks,popups}:{pages:Page[];blocks:Block[];popups:Popup[]}){
 const router=useRouter();const[busy,startTransition]=useTransition();const[pageId,setPageId]=useState(pages[0]?.id??'');const[blockId,setBlockId]=useState<string|null>(null);const[device,setDevice]=useState<'desktop'|'tablet'|'mobile'>('desktop');const[library,setLibrary]=useState(false);const[create,setCreate]=useState(false);const[sectionLibrary,setSectionLibrary]=useState(false);const[pageSettings,setPageSettings]=useState(false);
 const page=pages.find(p=>p.id===pageId)??null;const pageBlocks=useMemo(()=>blocks.filter(b=>b.page_id===pageId&&b.is_active).sort((a,b)=>a.display_order-b.display_order),[blocks,pageId]);const active=pageBlocks.find(b=>b.id===blockId)??pageBlocks[0]??null;
 const run=(fn:()=>Promise<void>)=>startTransition(async()=>{await fn();router.refresh()});
 const add=(type:string)=>{if(!page){setCreate(true);return}const f=new FormData();f.set('pageId',page.id);f.set('type',type);f.set('title',`${nice(type)} section`);run(async()=>{await addBuilderBlock(f);setSectionLibrary(false)})};
 const move=(id:string,delta:number)=>{if(!page)return;const list=[...pageBlocks],from=list.findIndex(b=>b.id===id),to=from+delta;if(to<0||to>=list.length)return;[list[from],list[to]]=[list[to],list[from]];const f=new FormData();f.set('pageId',page.id);f.set('blockIds',JSON.stringify(list.map(b=>b.id)));run(()=>reorderBuilderBlocks(f))};
 const save=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(active&&page)run(()=>updateBuilderBlock(new FormData(e.currentTarget)))};
 const createPage=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();run(async()=>{await createBuilderPage(new FormData(e.currentTarget));setCreate(false)})};
 const savePage=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();run(async()=>{await updateBuilderPage(new FormData(e.currentTarget));setPageSettings(false)})};
 const duplicatePage=(id:string)=>{const f=new FormData();f.set('id',id);run(()=>duplicateBuilderPage(f))};
 const deletePage=(id:string)=>{if(!window.confirm('Delete this page and all of its sections? This cannot be undone.'))return;const f=new FormData();f.set('id',id);run(async()=>{await deleteBuilderPage(f);setPageId('');setBlockId(null);setLibrary(false)})};
 const publish=(action:string)=>{if(!page)return;const f=new FormData();f.set('id',page.id);f.set('action',action);run(()=>setBuilderPageStatus(f))};
 return <>
  <header className="builder-toolbar"><div className="builder-toolbar-title"><LayoutTemplate size={21}/><b>Website Builder</b><button className="page-switch" onClick={()=>setLibrary(true)}>{page?.title??'Choose a page'}<ChevronDown size={15}/></button></div><div className="preview-devices"><button className={device==='desktop'?'selected':''} onClick={()=>setDevice('desktop')}><Monitor size={18}/></button><button className={device==='tablet'?'selected':''} onClick={()=>setDevice('tablet')}><Tablet size={17}/></button><button className={device==='mobile'?'selected':''} onClick={()=>setDevice('mobile')}><Smartphone size={17}/></button></div><div className="builder-toolbar-actions"><button><Undo2 size={18}/></button>{page&&<button className="page-settings-button" onClick={()=>setPageSettings(true)}>Page settings</button>}{page?.status==='published'&&<a href={`/pages/${page.slug}`} target="_blank" className="preview-link"><Eye size={17}/>Preview</a>}<button className="publish-button" disabled={!page||busy} onClick={()=>publish(page?.status==='draft'?'submit':page?.status==='pending'?'publish':page?.status==='published'?'pause':'submit')}>{busy?'Saving…':page?.status==='published'?'Pause':page?.status==='pending'?'Publish':'Submit for approval'}</button></div></header>
  <div className="builder-workspace"><aside className="builder-sections"><div className="builder-tabs"><button className="active">Sections</button><button onClick={()=>setLibrary(true)}>Pages</button></div><div className="section-list">{pageBlocks.length?pageBlocks.map(b=><button className={`section-row ${active?.id===b.id?'selected':''}`} key={b.id} onClick={()=>setBlockId(b.id)}><GripVertical size={16}/><span className={`section-thumb ${b.block_type}`}/><span><b>{b.title||nice(b.block_type)}</b><small>{nice(b.block_type)}</small></span><span className="section-move"><i onClick={e=>{e.stopPropagation();move(b.id,-1)}}><ChevronLeft size={14}/></i><i onClick={e=>{e.stopPropagation();move(b.id,1)}}><ChevronRight size={14}/></i></span></button>):<div className="empty-sections"><LayoutTemplate size={25}/><b>Your canvas is ready</b><span>Add your first visual section below.</span></div>}</div><div className="add-section-wrap"><button className="add-section" onClick={()=>setSectionLibrary(true)}><Plus size={18}/>Add section</button><div className="quick-section-grid">{presets.slice(1,5).map(([type,label])=><button key={label} onClick={()=>add(type)}>{label}</button>)}</div></div></aside>
   <main className={`builder-canvas-pane ${device}`}><p className="canvas-device-label">{device} preview · {page?status(page.status):'new page'}</p><div className="page-canvas"><div className="canvas-browser"><i/><i/><i/><span>glonni-affiliate.vercel.app{page?`/pages/${page.slug}`:''}</span></div><div className="canvas-header"><b>Glonn<span>i</span></b><div>Search stores, categories or deals</div><nav>Stores　 Deals　 Saved</nav></div><div className="canvas-page-heading"><p>GLONNI PAGE</p><h1>{page?.title??'Create your first page'}</h1>{page?.description&&<span>{page.description}</span>}</div>{pageBlocks.length?pageBlocks.map(b=><CanvasBlock key={b.id} block={b} selected={active?.id===b.id} select={()=>setBlockId(b.id)}/>):<section className="canvas-starter"><LayoutTemplate size={31}/><h2>Start with a visual section</h2><p>Add a hero, brand carousel, deal rail or trust strip. Every section can be styled before publishing.</p><button onClick={()=>add('hero')}><Plus size={17}/>Add your hero banner</button></section>}<div className="canvas-footer">Secure redirects · Clear cashback eligibility · Help when you need it</div></div></main>
   <aside className="builder-inspector">{active&&page?<Inspector block={active} pageId={page.id} save={save} busy={busy}/>:<div className="inspector-empty"><LayoutTemplate size={27}/><h2>Select a section</h2><p>Click any section in the canvas to edit content, colours, visibility and buttons.</p></div>}</aside></div>
  <footer className="builder-status"><span><i/> {busy?'Saving changes…':'Draft autosaved'}</span><span><Save size={15}/>Every save creates a version snapshot</span><button onClick={()=>setLibrary(true)}>Page library <ChevronDown size={14}/></button></footer>
  {library&&<div className="builder-modal-backdrop" onClick={()=>setLibrary(false)}><section className="builder-library" onClick={e=>e.stopPropagation()}><header><div><p>WEBSITE PAGES</p><h2>Your page library</h2><span>Open, duplicate, rename or delete your customer pages.</span></div><button className="publish-button" onClick={()=>{setLibrary(false);setCreate(true)}}><Plus size={17}/>Create page</button></header><div className="page-library-grid">{pages.map(p=><article className={`page-card ${p.id===pageId?'active':''}`} key={p.id}><button className="open-page" onClick={()=>{setPageId(p.id);setBlockId(null);setLibrary(false)}}><span className="page-card-preview"><b>Glonni</b><i/><i/><i/></span><strong>{p.title}</strong><small>/pages/{p.slug}</small><em className={p.status}>{status(p.status)}</em></button><div className="page-card-actions"><button onClick={()=>{setPageId(p.id);setLibrary(false);setPageSettings(true)}}>Edit settings</button><button onClick={()=>duplicatePage(p.id)}>Duplicate</button><button className="delete-page" onClick={()=>deletePage(p.id)}>Delete</button></div></article>)}{!pages.length&&<div className="library-empty"><LayoutTemplate size={30}/><b>No custom pages yet</b><span>Create a real customer-facing page from a safe Glonni template.</span></div>}</div><div className="popup-summary"><b>{popups.length} popup drafts</b><span> are ready for campaign setup after a page is created.</span></div></section></div>}
  {sectionLibrary&&<div className="builder-modal-backdrop" onClick={()=>setSectionLibrary(false)}><section className="section-library" onClick={e=>e.stopPropagation()}><p>SECTION LIBRARY</p><h2>Add to {page?.title??'your page'}</h2><span>Choose a visual building block. You can change its content and style after adding it.</span><div>{[...presets,['text','Text & content'],['cta','CTA button'],['faq','FAQs']].map(([type,label])=><button key={`${type}-${label}`} onClick={()=>add(type)}><i className={`section-thumb ${type}`}/><b>{label}</b><small>Add section</small><Plus size={16}/></button>)}</div></section></div>}
  {create&&<div className="builder-modal-backdrop" onClick={()=>setCreate(false)}><form className="create-page-modal" onSubmit={createPage} onClick={e=>e.stopPropagation()}><p>NEW CUSTOMER PAGE</p><h2>Create a page</h2><span>Starts as a private draft. Add visual sections before publishing.</span><label>Page name<input required name="title" placeholder="e.g. Diwali Deals"/></label><label>Page URL<input name="slug" placeholder="e.g. diwali-deals"/></label><label>Short introduction<input name="description" placeholder="Optional page summary"/></label><label>Visibility<select name="device"><option value="all">Desktop + mobile</option><option value="desktop">Desktop only</option><option value="mobile">Mobile only</option></select></label><div><button type="button" onClick={()=>setCreate(false)}>Cancel</button><button className="publish-button" disabled={busy} type="submit">{busy?'Creating…':'Create draft'}</button></div></form></div>}
  {pageSettings&&page&&<div className="builder-modal-backdrop" onClick={()=>setPageSettings(false)}><form className="create-page-modal" onSubmit={savePage} onClick={e=>e.stopPropagation()}><p>PAGE SETTINGS</p><h2>Edit {page.title}</h2><span>Change the page name, URL and customer-facing introduction.</span><input type="hidden" name="id" value={page.id}/><label>Page name<input required name="title" defaultValue={page.title}/></label><label>Page URL<input name="slug" defaultValue={page.slug}/></label><label>Short introduction<input name="description" defaultValue={page.description??''}/></label><label>Visibility<select name="device" defaultValue={page.device_visibility}><option value="all">Desktop + mobile</option><option value="desktop">Desktop only</option><option value="mobile">Mobile only</option></select></label><div><button type="button" onClick={()=>setPageSettings(false)}>Cancel</button><button className="publish-button" disabled={busy} type="submit">{busy?'Saving…':'Save page settings'}</button></div></form></div>}
 </>
}
function CanvasBlock({block,selected,select}:{block:Block;selected:boolean;select:()=>void}){const c=block.config??{},hero=block.block_type==='hero',rail=['banner','category_grid','store_rail','product_rail'].includes(block.block_type);return <section className={`canvas-section ${block.block_type} ${selected?'selected':''}`} style={{backgroundColor:c.background||'#fff','--accent':c.accent||'#1454d9'} as React.CSSProperties} onClick={select}><div className="canvas-selection-tools"><span><GripVertical size={14}/>{nice(block.block_type)}</span><button>Edit</button><button><Copy size={13}/></button><button className="danger"><Trash2 size={13}/></button></div>{hero?<div className="canvas-hero"><div><p>GLONNI SHOPPING DISCOVERY</p><h2>{block.title}</h2><span>{block.body||'Find genuine deals, compare prices and see cashback only where eligible.'}</span>{block.cta_label&&<button>{block.cta_label}<ChevronRight size={16}/></button>}</div><div className="hero-visual"><div className="cashback-bubble">✓ Eligible cashback<br/>on selected offers</div><div className="shopping-bag">G</div></div></div>:rail?<><div className="canvas-section-title"><h2>{block.title}</h2><a>View all</a></div>{block.body&&<p className="canvas-copy">{block.body}</p>}<div className={`canvas-items ${block.block_type}`}>{Array.from({length:block.block_type==='category_grid'?7:4}).map((_,i)=><div className="canvas-item" key={i}><i/><b>{block.block_type==='category_grid'?['Mobiles','Fashion','Beauty','Home','Sports','Groceries','Travel'][i]:block.block_type==='store_rail'?['Amazon','Myntra','Nykaa','Flipkart'][i]:['Best deal','Smart choice','Trending','Price drop'][i]}</b><small>{block.block_type.includes('rail')?'Up to 8% cashback':'Explore'}</small></div>)}</div></>:<><h2>{block.title}</h2><p className="canvas-copy">{block.body||'Add clear supporting information for this section.'}</p>{block.cta_label&&<button className="canvas-cta">{block.cta_label}</button>}</>}</section>}
function Inspector({block,pageId,save,busy}:{block:Block;pageId:string;save:(e:FormEvent<HTMLFormElement>)=>void;busy:boolean}){const c=block.config??{};return <form className="inspector-form" onSubmit={save}><header><div><p>SECTION SETTINGS</p><h2>{block.title||nice(block.block_type)}</h2></div><MoreHorizontal size={19}/></header><nav><button type="button" className="active">Content</button><button type="button">Style</button><button type="button">Action</button><button type="button">Visibility</button></nav><input type="hidden" name="id" value={block.id}/><input type="hidden" name="pageId" value={pageId}/><label>Heading<input name="title" defaultValue={block.title??''}/></label><label>Supporting copy<textarea name="body" defaultValue={block.body??''} rows={4}/></label><label>Button label<input name="ctaLabel" defaultValue={block.cta_label??''} placeholder="e.g. Explore deals"/></label><label>Internal destination<input name="ctaHref" defaultValue={block.cta_href??''} placeholder="/deals"/><small>Only safe Glonni destinations are accepted here.</small></label><label>Campaign image URL <input name="imageUrl" defaultValue={block.image_url??''} placeholder="Paste a hosted image URL"/><small>Image upload will be connected to approved Storage next; this field lets you change the image now.</small></label><fieldset><legend>Section style</legend><div className="color-pair"><label>Accent<input name="accent" type="color" defaultValue={c.accent||'#1454d9'}/></label><label>Background<input name="background" type="color" defaultValue={c.background||'#ffffff'}/></label></div><label>Layout<select name="layout" defaultValue={c.layout||'standard'}><option value="standard">Standard</option><option value="split">Split visual</option><option value="centered">Centered</option></select></label><label>Button style<select name="buttonStyle" defaultValue={c.buttonStyle||'solid'}><option value="solid">Solid</option><option value="outline">Outline</option><option value="soft">Soft</option></select></label></fieldset><fieldset><legend>Device visibility</legend><label className="radio-row"><input type="radio" name="device" value="all" defaultChecked={block.device_visibility==='all'}/>Desktop + mobile</label><label className="radio-row"><input type="radio" name="device" value="desktop" defaultChecked={block.device_visibility==='desktop'}/>Desktop only</label><label className="radio-row"><input type="radio" name="device" value="mobile" defaultChecked={block.device_visibility==='mobile'}/>Mobile only</label></fieldset><button className="save-section" disabled={busy} type="submit"><Save size={16}/>{busy?'Saving…':'Save section'}</button></form>}
