import { AdminSidebar } from '@/components/admin-sidebar';
import { OwnerAiChat } from '@/components/owner-ai-chat';
import { addOwnerInstruction } from '../ai-actions';
import { cancelAiJob, retryAiJob, runAiJob } from '../ai-job-actions';
import { createClient } from '@/lib/supabase/server';
import { AlertTriangle, Bell, Bot, BriefcaseBusiness, Building2, CircleDollarSign, FileSearch, Megaphone, PauseCircle, PenTool, ShieldCheck, ShoppingBag, UsersRound } from 'lucide-react';

const managerDisplay = {
  ceo_operations: [Building2,'blue'], affiliate_partnerships: [BriefcaseBusiness,'purple'], provider_compliance: [FileSearch,'violet'],
  catalogue_merchandising: [ShoppingBag,'orange'], content_experience: [PenTool,'cyan'], marketing: [Megaphone,'green'],
  finance_cashback_risk: [CircleDollarSign,'gold'], fraud_security: [ShieldCheck,'red'], customer_operations: [UsersRound,'indigo'],
} as const;
const managerKeys = Object.keys(managerDisplay);
const label = (value: string) => value.replaceAll('_',' ');
const formatTime = (value?: string | null) => value ? new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)) : 'Never run';
const stateLabel = (agent: any) => agent.runtime_status === 'not_connected' ? 'Not connected' : agent.runtime_status === 'disabled' ? 'Disabled' : agent.runtime_status === 'running' ? 'Running' : agent.runtime_status === 'failed' ? 'Failed' : 'Idle';

export default async function AiCommandCenter({ searchParams }: { searchParams: Promise<{ error?: string; success?: string }> }) {
  const supabase = await createClient();
  const [{ data: work }, { data: instructions }, { data: agentRows }, { data: jobs }] = await Promise.all([
    supabase.from('ai_work_items').select('*').order('created_at',{ascending:false}),
    supabase.from('ai_owner_instructions').select('*').eq('status','active').order('created_at',{ascending:false}).limit(3),
    supabase.from('ai_agents').select('*').in('key',managerKeys).order('name'),
    supabase.from('ai_jobs').select('*').order('created_at',{ascending:false}).limit(20),
  ]);
  const query = await searchParams;
  const pending = (work ?? []).filter(x=>x.status==='pending_approval');
  const agents = (agentRows ?? []).sort((a,b)=>managerKeys.indexOf(a.key)-managerKeys.indexOf(b.key));
  const operational = agents.filter(a=>a.capability_status==='operational').length;
  const partial = agents.filter(a=>a.capability_status==='partial').length;
  const failures = agents.filter(a=>a.runtime_status==='failed').length;
  return <main className="admin-v2 ai-admin"><AdminSidebar/><section className="admin-main"><header className="admin-top"><Building2 size={21}/><b>AI Company</b><span className="dashboard-date">Runtime control centre</span><Bell size={19}/><span className="avatar">SR</span></header><main className="ai-command">
    <div className="ai-command-head"><div><p>GLONNI AI COMPANY</p><h1>AI Agent Control Centre</h1><span>Live execution health, capabilities and owner-controlled work</span></div><a className="add-store" href="/admin/approvals">Open Approval Inbox</a></div>
    {query.error && <p className="preview-note">{query.error}</p>}{query.success && <p className="preview-note">{query.success}</p>}
    <section className="ai-summary"><article><Bot/><div><b>{operational + partial}</b><span>Connected capabilities</span></div></article><article><AlertTriangle/><div><b>{pending.length}</b><span>Pending approvals</span></div></article><article><ShieldCheck/><div><b className={failures ? 'stopped':'safe'}>{failures ? `${failures} failed` : 'Healthy'}</b><span>Runtime health</span></div></article><article><PauseCircle/><div><b className="stopped">Paused</b><span>External automation</span></div></article></section>
    <section className="ai-layout"><div><article className="ai-panel"><header><div><b>Agent Operations</b><span>Status comes from the runtime database—not decorative labels</span></div><small>{operational} operational · {partial} partial · {agents.length-operational-partial} not connected</small></header><div className="manager-grid">{agents.map(agent=>{const [Icon,color]=managerDisplay[agent.key as keyof typeof managerDisplay]; const total=Number(agent.success_count)+Number(agent.failure_count); const successRate=total?Math.round(Number(agent.success_count)/total*100):null; return <article className="manager-card" key={agent.key}><div className={`manager-icon ${color}`}><Icon/></div><span className={`agent-state state-${agent.runtime_status}`}><i/>{stateLabel(agent)}</span><em>{label(agent.capability_status)}</em><h2>{agent.name}</h2><p>{agent.description}</p><dl className="agent-metrics"><div><dt>Last run</dt><dd>{formatTime(agent.last_run_at)}</dd></div><div><dt>Next run</dt><dd>{agent.next_run_at ? formatTime(agent.next_run_at) : 'Manual only'}</dd></div><div><dt>Success rate</dt><dd>{successRate===null?'No runs':`${successRate}%`}</dd></div></dl>{agent.latest_error && <p className="agent-error" title={agent.latest_error}>Latest error: {agent.latest_error}</p>}<a href="/admin/approvals">View related work →</a></article>})}</div></article>
      <article className="ai-panel ai-run-console"><header><div><b>Run an AI job</b><span>All research is saved as review-only output</span></div><small>Duplicate protection · maximum 3 attempts</small></header><div className="ai-run-grid"><form action={runAiJob}><input type="hidden" name="jobType" value="owner_daily_brief"/><b>Owner Daily Brief</b><span>Summarise current approvals, risks and blockers.</span><button>Run now</button></form><form action={runAiJob}><input type="hidden" name="jobType" value="product_enrichment"/><b>Product Enrichment</b><span>Research one exact product for an editable draft.</span><input name="query" required minLength={3} placeholder="e.g. Apple iPhone 16 128GB"/><button>Run research</button></form><form action={runAiJob}><input type="hidden" name="jobType" value="product_discovery"/><b>Product Discovery</b><span>Find review candidates; never publish automatically.</span><input name="query" required minLength={3} placeholder="e.g. Top 25 Crocs sandals"/><button>Run discovery</button></form></div></article>
      <article className="ai-panel ai-job-history"><header><div><b>Execution history</b><span>Every attempt, result and failure is retained</span></div><small>{jobs?.length??0} recent jobs</small></header><div className="ai-job-table"><table><thead><tr><th>JOB</th><th>AGENT</th><th>STATUS</th><th>ATTEMPTS</th><th>STARTED</th><th>RESULT / ERROR</th><th>ACTION</th></tr></thead><tbody>{(jobs??[]).map(job=><tr key={job.id}><td><b>{label(job.job_type)}</b><small>{String(job.input?.query??'System brief')}</small></td><td>{label(job.agent_key)}</td><td><em className={`job-${job.status}`}>{job.status}</em></td><td>{job.attempt_count}/{job.max_attempts}</td><td>{formatTime(job.started_at??job.scheduled_for)}</td><td><span>{job.latest_error??job.output?.summary??'Waiting to run'}</span>{Array.isArray(job.sources)&&job.sources.length>0&&<small>{job.sources.length} sources saved</small>}</td><td>{job.status==='failed'&&job.attempt_count<job.max_attempts?<form action={retryAiJob}><input type="hidden" name="jobId" value={job.id}/><button>Retry</button></form>:['queued','scheduled'].includes(job.status)?<form action={cancelAiJob}><input type="hidden" name="jobId" value={job.id}/><button>Cancel</button></form>:<small>Recorded</small>}</td></tr>)}{!jobs?.length&&<tr><td colSpan={7}>No AI jobs have run yet.</td></tr>}</tbody></table></div></article>
      <article className="ai-panel daily-brief"><header><div><b>CEO Daily Brief</b><span>What needs the owner’s attention today</span></div><a href="/admin/approvals">Review all →</a></header><div className="brief-grid">{pending.slice(0,4).map(item=><p key={item.id}><strong>{label(item.area)}</strong>{item.title}: {item.summary}</p>)}{pending.length===0 && <p><strong>All clear</strong>No owner decisions are waiting.</p>}</div></article></div>
      <aside className="ai-rail"><article className="ai-panel approval-preview"><header><div><b>Approval Inbox</b><span>Owner decisions</span></div><strong>{pending.length}</strong></header>{pending.slice(0,3).map(item=><section key={item.id}><div><b>{item.title}</b><span>{item.summary}</span><em>{item.risk_level} risk</em></div><a href="/admin/approvals">Review</a></section>)}{pending.length===0 && <p className="preview-note">No pending approvals.</p>}</article><OwnerAiChat/><article className="ai-panel owner-chat"><header><div><b>Owner Instructions</b><span>Set rules for future AI workflows</span></div></header><form action={addOwnerInstruction}><select name="scope" defaultValue="all_agents"><option value="all_agents">All AI managers</option><option value="marketing">Marketing</option><option value="content">Content</option><option value="provider_policy">Provider policy</option><option value="finance">Finance</option><option value="security">Security</option></select><textarea name="instruction" placeholder="Example: Do not propose ad spend above ₹500/day without my written approval." required minLength={3}/><button type="submit">Save instruction</button></form>{(instructions ?? []).map(item=><p className="owner-question" key={item.id}><b>{label(item.scope)}:</b> {item.instruction}</p>)}</article></aside></section>
    <section className="emergency-bar"><div><AlertTriangle/><span><b>Emergency Controls</b><small>Controls remain inactive until the matching live connection exists.</small></span></div><button disabled className="danger">STOP ALL ADS</button><button disabled>Pause Publishing</button><button disabled>Lock Cashback Credits</button><button disabled>Pause All Managers</button></section>
  </main></section></main>;
}
