import { AdminSidebar } from "@/components/admin-sidebar";
import { Bell, Cable, CloudCog, FileSpreadsheet, Link2, PlugZap, ShieldCheck, Store } from 'lucide-react';

const providers = [
  ['Glonni Manual Links', 'manual', 'Manual', 'Ready for configuration', 'No credentials required', 'Active'],
  ['Admitad', 'admitad', 'Approval required', 'Awaiting partnership approval', 'Not stored', 'Pending'],
  ['Cuelinks', 'cuelinks', 'Approval required', 'Awaiting partnership approval', 'Not stored', 'Pending'],
  ['Impact', 'impact', 'API / feed', 'Not connected', 'Not stored', 'Paused'],
];

export default function ProvidersPage() {
  return <main className="admin-v2"><AdminSidebar/><section className="admin-main"><header className="admin-top"><CloudCog size={21} /><b>Affiliate Providers</b><span className="dashboard-date">Provider-neutral integration hub · preview mode</span><Bell size={19} /><span className="avatar">SR</span></header><main className="admin-content"><div className="admin-title"><div><p>PROVIDER REGISTRY</p><h1>Affiliate Providers</h1><span>Define how each approved affiliate partner supplies merchant offers and conversion updates.</span></div><button className="add-store" disabled>＋ Add provider</button></div><p className="preview-note">Credentials, tokens and webhooks are intentionally locked. Add a live provider only after agreement, secure admin roles, and the provider’s approved integration method.</p><section className="admin-stats"><article><CloudCog /><div><small>Provider records</small><b>4</b><em>Preview registry</em></div></article><article><ShieldCheck /><div><small>Approved connections</small><b>0</b><em>None connected</em></div></article><article><Link2 /><div><small>Manual link source</small><b>1</b><em>Safe mock mode</em></div></article><article><FileSpreadsheet /><div><small>Feed imports</small><b>0</b><em>Awaiting provider access</em></div></article><article><PlugZap /><div><small>API credentials</small><b>0</b><em>Never exposed to browser</em></div></article></section><section className="admin-grid"><article className="store-table"><div className="table-head"><div><a className="current">All providers</a><a>Manual</a><a>Awaiting approval</a><a>Paused</a></div></div><div className="table-scroll"><table><thead><tr><th>PROVIDER</th><th>ADAPTER KEY</th><th>INTEGRATION MODE</th><th>CONNECTION STATUS</th><th>CREDENTIAL STATUS</th><th>RECORD STATUS</th></tr></thead><tbody>{providers.map((provider) => <tr key={provider[1]}><td><span><strong>{provider[0]}</strong><small>Provider adapter configuration</small></span></td><td>{provider[1]}</td><td>{provider[2]}</td><td>{provider[3]}</td><td>{provider[4]}</td><td><em className={provider[5] === 'Active' ? 'status-active' : 'status-paused'}>{provider[5]}</em></td></tr>)}</tbody></table></div><footer>Providers are interchangeable adapters. Products and merchants remain owned by Glonni’s normalized catalogue.</footer></article><aside className="admin-right"><article><h2>Before activation</h2><p>Commercial approval <span>Required</span></p><p>Secure credential storage <span>Required</span></p><p>Test conversion event <span>Required</span></p></article><article><h2>Architecture rule</h2><p className="activity">No provider hard-coding<small>Adding a provider must not require a site rebuild.</small></p><p className="activity">Provider is not the merchant<small>Each provider can serve many merchants and offers.</small></p></article></aside></section></main></section></main>;
}
