'use server';
import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
const msg=(value:string)=>encodeURIComponent(value);
async function owner(next:string){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect(`/login?next=${encodeURIComponent(next)}`);return{supabase,user};}
export async function removeSavedOffer(formData:FormData){const{supabase,user}=await owner('/saved-deals');const offerId=String(formData.get('offerId')||'');if(!offerId)redirect(`/saved-deals?error=${msg('That saved offer could not be identified.')}`);const{error}=await supabase.from('saved_offers').delete().eq('profile_id',user.id).eq('offer_id',offerId);if(error)redirect(`/saved-deals?error=${msg('The saved offer could not be removed. Please try again.')}`);revalidatePath('/saved-deals');revalidatePath('/account');redirect(`/saved-deals?success=${msg('The offer was removed from your saved deals.')}`);}
export async function togglePriceAlert(formData:FormData){const{supabase,user}=await owner('/price-alerts');const id=String(formData.get('id')||''),isActive=formData.get('isActive')==='true';if(!id)redirect(`/price-alerts?error=${msg('That alert could not be identified.')}`);const{error}=await supabase.from('price_alerts').update({is_active:!isActive,updated_at:new Date().toISOString()}).eq('id',id).eq('profile_id',user.id);if(error)redirect(`/price-alerts?error=${msg('The alert could not be updated. Please try again.')}`);revalidatePath('/price-alerts');redirect(`/price-alerts?success=${msg(isActive?'The alert was paused.':'The alert is active again.')}`);}
export async function removePriceAlert(formData:FormData){const{supabase,user}=await owner('/price-alerts');const id=String(formData.get('id')||'');if(!id)redirect(`/price-alerts?error=${msg('That alert could not be identified.')}`);const{error}=await supabase.from('price_alerts').delete().eq('id',id).eq('profile_id',user.id);if(error)redirect(`/price-alerts?error=${msg('The alert could not be removed. Please try again.')}`);revalidatePath('/price-alerts');revalidatePath('/account');redirect(`/price-alerts?success=${msg('The price alert was removed.')}`);}
