'use client';
import { useActionState,useEffect,useMemo,useState } from 'react';
import type { ReactNode } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Archive,ChevronDown,ChevronRight,ChevronsDownUp,ChevronsUpDown,Copy,Download,Eye,FolderTree,GripVertical,ImageIcon,MoreHorizontal,Pencil,Plus,Search,ShieldCheck,Upload } from 'lucide-react';
import { categoryBulkAction,saveCategoryInline,type CategoryActionState } from '../actions';

export type TreeCategory={id:string;name:string;slug:string;parent_id:string|null;level:number;navigation_label:string|null;short_description:string|null;description:string|null;category_type:'department'|'category'|'subcategory'|'collection';image_url:string|null;banner_url:string|null;mobile_banner_url:string|null;icon_name:string|null;seo_title:string|null;seo_description:string|null;seo_keywords:string[];canonical_url:string|null;show_on_homepage:boolean;show_in_navigation:boolean;is_searchable:boolean;sort_mode:string;product_assignment:string;filter_configuration:Record<string,unknown>;display_order:number;is_active:boolean;archived_at:string|null;products:number;children_count:number};
type Editor={mode:'add'|'edit';id?:string;parentId:string|null;templateId?:string}|null;
const mediaAccept='image/png,image/jpeg,image/webp,image/svg+xml,.svg';

function MediaField({name,urlName,label,hint,current}:{name:string;urlName:string;label:string;hint:string;current?:string|null}){const[fileName,setFileName]=useState('');return <label className="taxonomy-media-field"><span className="taxonomy-media-preview">{current?<img src={current} alt=""/>:<ImageIcon/>}</span><span><b>{fileName||label}</b><small>{hint}</small></span><input name={name} type="file" accept={mediaAccept} onChange={e=>setFileName(e.target.files?.[0]?.name??'')}/><input name={urlName} type="hidden" defaultValue={current??''}/></label>}

function InlineCategoryEditor({node,template,parentId,categories,onDone}:{node?:TreeCategory;template?:TreeCategory;parentId:string|null;categories:TreeCategory[];onDone:()=>void}){
 const router=useRouter(),source=node??template,[state,action,pending]=useActionState<CategoryActionState,FormData>(saveCategoryInline,{}),byId=useMemo(()=>new Map(categories.map(c=>[c.id,c])),[categories]);
 const isInside=(candidate:TreeCategory,nodeId:string)=>{let current:TreeCategory|undefined=candidate;while(current){if(current.id===nodeId)return true;current=current.parent_id?byId.get(current.parent_id):undefined}return false};
 const breadcrumb=(id:string|null)=>{const names:string[]=[];let current=id?byId.get(id):undefined;while(current){names.unshift(current.name);current=current.parent_id?byId.get(current.parent_id):undefined}return names.length?names.join(' › '):'Top level'};
 useEffect(()=>{if(state.ok){router.refresh();onDone()}},[state.ok,router,onDone]);
 const title=node?`Edit ${node.name}`:template?`Duplicate ${template.name}`:parentId?`Add subcategory under ${byId.get(parentId)?.name}`:'Create a parent category';
 return <tr className="tree-inline-editor"><td colSpan={6}><form action={action}>{node&&<input type="hidden" name="id" value={node.id}/>} {!node&&<input type="hidden" name="parentId" value={parentId??''}/>}<header className="tree-editor-heading"><span><b>{title}</b><small>{node?'Update its storefront, taxonomy and discovery settings.':`Location: ${breadcrumb(parentId)} · This becomes level ${(byId.get(parentId??'')?.level??0)+1}.`}</small></span><button type="button" onClick={onDone}>Cancel</button></header>{state.message&&!state.ok&&<p className="tree-form-error" role="alert">{state.message}</p>}
 <section className="taxonomy-editor-section"><div className="taxonomy-section-title"><b>Basic information</b><small>The shopper-facing identity and purpose of this category.</small></div><div className="taxonomy-fields taxonomy-fields-3"><label>Category name<input name="name" required defaultValue={template?`Copy of ${template.name}`:source?.name??''} placeholder="e.g. Women’s Footwear"/></label><label>Navigation label<input name="navigationLabel" defaultValue={source?.navigation_label??''} placeholder="Short menu label"/></label><label>Category type<select name="categoryType" defaultValue={source?.category_type??(parentId?'subcategory':'department')}><option value="department">Department</option><option value="category">Category</option><option value="subcategory">Subcategory</option><option value="collection">Collection</option></select></label><label>URL slug<input name="slug" required defaultValue={template?`${template.slug}-copy`:source?.slug??''} placeholder="womens-footwear"/><small>Must be unique across the website.</small></label><label className="span-2">Short description<input name="shortDescription" defaultValue={source?.short_description??''} maxLength={160} placeholder="Short description used on category cards"/></label><label className="span-3">Full description<textarea name="description" rows={3} defaultValue={source?.description??''} placeholder="Explain what shoppers can find in this category."/></label></div></section>
 <section className="taxonomy-editor-section"><div className="taxonomy-section-title"><b>Hierarchy & merchandising</b><small>Choose where it lives and how products are presented.</small></div><div className="taxonomy-parent-card"><FolderTree/><span><small>Current parent</small><b>{breadcrumb(node?node.parent_id:parentId)}</b></span>{!node&&<em>Locked for this new child</em>}</div><div className="taxonomy-fields taxonomy-fields-4">{node&&<label className="span-2">Move to parent<select name="parentId" defaultValue={node.parent_id??''}><option value="">Top level (no parent)</option>{categories.filter(c=>c.id!==node.id&&!isInside(c,node.id)&&!c.archived_at).map(c=><option value={c.id} key={c.id}>{'— '.repeat(Math.max(0,c.level-1))}{c.name}</option>)}</select></label>}<label>Display order<input name="displayOrder" type="number" min="1" defaultValue={source?.display_order??99}/></label><label>Status<select name="status" defaultValue={source?.archived_at?'archived':source?.is_active?'active':'draft'}><option value="active">Active</option><option value="draft">Paused / draft</option>{node&&<option value="archived">Archived</option>}</select></label><label>Default product sort<select name="sortMode" defaultValue={source?.sort_mode??'featured'}><option value="featured">Featured</option><option value="popularity">Popularity</option><option value="newest">Newest</option><option value="price_low_high">Price: low to high</option><option value="price_high_low">Price: high to low</option><option value="discount">Highest discount</option></select></label><label>Product assignment<select name="productAssignment" defaultValue={source?.product_assignment??'manual'}><option value="manual">Manual</option><option value="rules">Automatic rules</option><option value="provider">Provider mapping</option></select></label></div></section>
 <section className="taxonomy-editor-section"><div className="taxonomy-section-title"><b>Images & banners</b><small>Upload safe PNG, JPG, WebP or SVG files, up to 4 MB each.</small></div><div className="taxonomy-media-grid"><MediaField name="imageFile" urlName="imageUrl" label="Category image or icon" hint="Square image recommended" current={source?.image_url}/><MediaField name="bannerFile" urlName="bannerUrl" label="Desktop banner" hint="Wide landscape image" current={source?.banner_url}/><MediaField name="mobileBannerFile" urlName="mobileBannerUrl" label="Mobile banner" hint="Portrait or compact banner" current={source?.mobile_banner_url}/></div><input name="iconName" type="hidden" value={source?.icon_name??''}/></section>
 <section className="taxonomy-editor-section"><div className="taxonomy-section-title"><b>Storefront visibility</b><small>Control where customers can discover this category.</small></div><div className="taxonomy-switches"><label><input name="showInNavigation" type="checkbox" defaultChecked={source?.show_in_navigation??true}/><span><b>Show in navigation</b><small>Display in category menus.</small></span></label><label><input name="showOnHomepage" type="checkbox" defaultChecked={source?.show_on_homepage??false}/><span><b>Show on homepage</b><small>Allow this category in homepage sections.</small></span></label><label><input name="isSearchable" type="checkbox" defaultChecked={source?.is_searchable??true}/><span><b>Include in search</b><small>Make it discoverable in search.</small></span></label></div></section>
 <section className="taxonomy-editor-section"><div className="taxonomy-section-title"><b>SEO & filters</b><small>Optional search-engine metadata and category-specific facets.</small></div><div className="taxonomy-fields taxonomy-fields-2"><label>SEO title<input name="seoTitle" defaultValue={source?.seo_title??''} maxLength={70}/></label><label>Canonical URL<input name="canonicalUrl" type="url" defaultValue={source?.canonical_url??''} placeholder="https://glonni.com/category/..."/></label><label className="span-2">SEO description<textarea name="seoDescription" rows={2} defaultValue={source?.seo_description??''} maxLength={180}/></label><label className="span-2">SEO keywords<input name="seoKeywords" defaultValue={source?.seo_keywords?.join(', ')??''} placeholder="shoes, women, footwear"/></label><label className="span-2">Filter configuration (advanced)<textarea name="filterConfiguration" rows={3} defaultValue={JSON.stringify(source?.filter_configuration??{},null,2)} spellCheck={false}/><small>JSON defining filters such as brand, size, colour or price.</small></label></div></section>
 <footer className="taxonomy-editor-actions"><button type="button" onClick={onDone}>Cancel</button><button className="tree-save" disabled={pending}>{pending?'Saving…':node?'Save category':template?'Create duplicate':'Create category'}</button></footer></form></td></tr>
}

export function CategoryTreeManager({categories}:{categories:TreeCategory[]}){
 const[expanded,setExpanded]=useState(()=>new Set(categories.map(c=>c.id))),[editor,setEditor]=useState<Editor>(null),[search,setSearch]=useState('');
 const children=useMemo(()=>{const map=new Map<string|null,TreeCategory[]>();for(const c of categories)map.set(c.parent_id,[...(map.get(c.parent_id)??[]),c]);for(const rows of map.values())rows.sort((a,b)=>a.display_order-b.display_order||a.name.localeCompare(b.name));return map},[categories]),byId=useMemo(()=>new Map(categories.map(c=>[c.id,c])),[categories]);
 const path=(c:TreeCategory)=>{const names:string[]=[];let current:TreeCategory|undefined=c;while(current){names.unshift(current.slug);current=current.parent_id?byId.get(current.parent_id):undefined}return `/${names.join('/')}`};
 const visibleIds=useMemo(()=>{if(!search.trim())return null;const result=new Set<string>(),needle=search.toLowerCase();for(const c of categories)if(`${c.name} ${c.slug} ${c.navigation_label??''}`.toLowerCase().includes(needle)){let current:TreeCategory|undefined=c;while(current){result.add(current.id);current=current.parent_id?byId.get(current.parent_id):undefined}}return result},[search,categories,byId]);
 const toggle=(id:string)=>setExpanded(old=>{const next=new Set(old);next.has(id)?next.delete(id):next.add(id);return next}),closeEditor=()=>setEditor(null);
 const rows=(parentId:string|null,depth=0):ReactNode[]=>{const output:ReactNode[]=[];for(const c of children.get(parentId)??[]){if(visibleIds&&!visibleIds.has(c.id))continue;const hasChildren=(children.get(c.id)?.length??0)>0,isOpen=visibleIds?true:expanded.has(c.id),editing=editor?.mode==='edit'&&editor.id===c.id,adding=editor?.mode==='add'&&editor.parentId===c.id&&!editor.templateId,duplicating=editor?.mode==='add'&&editor.templateId===c.id;output.push(<tr className={`tree-node ${editing?'selected':''}`} key={c.id}><td><span className="tree-category" style={{paddingLeft:depth*28}}><GripVertical className="tree-grip"/>{hasChildren?<button type="button" className="tree-toggle" onClick={()=>toggle(c.id)} aria-label={`${isOpen?'Collapse':'Expand'} ${c.name}`}>{isOpen?<ChevronDown/>:<ChevronRight/>}</button>:<i className="tree-branch"/>}<span className="tree-thumb">{c.image_url?<img src={c.image_url} alt=""/>:(c.icon_name||'○')}</span><span><b>{c.name}</b><small>{path(c)} · Level {c.level} · {c.category_type}</small></span></span></td><td>{c.products.toLocaleString('en-IN')}</td><td><span className={`ops-chip ${c.archived_at?'bad':c.is_active?'good':'warn'}`}>{c.archived_at?'Archived':c.is_active?'Active':'Paused'}</span></td><td><button type="button" onClick={()=>{setExpanded(x=>new Set(x).add(c.id));setEditor({mode:'add',parentId:c.id})}}><Plus/> Add child</button></td><td><button type="button" onClick={()=>setEditor({mode:'edit',id:c.id,parentId:c.parent_id})}><Pencil/> Edit</button></td><td><details className="tree-more"><summary aria-label={`More actions for ${c.name}`}><MoreHorizontal/></summary><div><button type="button" onClick={()=>setEditor({mode:'add',parentId:c.parent_id,templateId:c.id})}><Copy/> Duplicate</button><Link href={`/category/${c.slug}`}><Eye/> View storefront</Link><form action={categoryBulkAction}><input type="hidden" name="ids" value={c.id}/><input type="hidden" name="action" value={c.is_active?'pause':'activate'}/><button><Archive/> {c.is_active?'Pause':'Activate'}</button></form>{!c.archived_at&&<form action={categoryBulkAction}><input type="hidden" name="ids" value={c.id}/><input type="hidden" name="action" value="archive"/><button className="danger"><Archive/> Archive</button></form>}</div></details></td></tr>);if(editing)output.push(<InlineCategoryEditor key={`edit-${c.id}`} node={c} parentId={c.parent_id} categories={categories} onDone={closeEditor}/>);if(adding)output.push(<InlineCategoryEditor key={`add-${c.id}`} parentId={c.id} categories={categories} onDone={closeEditor}/>);if(duplicating)output.push(<InlineCategoryEditor key={`duplicate-${c.id}`} template={c} parentId={c.parent_id} categories={categories} onDone={closeEditor}/>);if(hasChildren&&isOpen)output.push(...rows(c.id,depth+1))}return output};
 return <section className="category-tree-workspace"><div className="tree-safety"><ShieldCheck/> Unlimited hierarchy · circular nesting protected</div><header className="tree-toolbar"><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, label or slug…"/></label><span/><button onClick={()=>setExpanded(new Set(categories.map(c=>c.id)))}><ChevronsUpDown/> Expand all</button><button onClick={()=>setExpanded(new Set())}><ChevronsDownUp/> Collapse all</button><a href="?tab=import"><Upload/> Import</a><a href="/admin/categories/export"><Download/> Export</a><button className="tree-add-parent" onClick={()=>setEditor({mode:'add',parentId:null})}><Plus/> Add parent category</button></header><div className="category-tree-card"><header><div><h2>Category taxonomy</h2><p>Add a child to any row to create another level. Parent assignment controls the tree.</p></div><b>{categories.length} categories</b></header><div className="table-scroll"><table className="category-tree-model"><thead><tr><th>CATEGORY & PATH</th><th>DIRECT PRODUCTS</th><th>STATUS</th><th colSpan={3}>ACTIONS</th></tr></thead><tbody>{editor?.mode==='add'&&editor.parentId===null&&!editor.templateId&&<InlineCategoryEditor parentId={null} categories={categories} onDone={closeEditor}/>}{rows(null)}</tbody></table></div></div></section>
}
