'use client';
import { useActionState, useEffect, useMemo, useState } from 'react';
import type { ReactNode } from 'react';
import { useRouter } from 'next/navigation';
import { ChevronDown, ChevronRight, ChevronsDownUp, ChevronsUpDown, Download, GripVertical, ImageIcon, MoreHorizontal, Pencil, Plus, Search, ShieldCheck, Upload } from 'lucide-react';
import { saveCategoryInline, type CategoryActionState } from '../actions';

export type TreeCategory={id:string;name:string;slug:string;parent_id:string|null;level:number;description:string|null;image_url:string|null;icon_name:string|null;seo_title:string|null;seo_description:string|null;show_on_homepage:boolean;display_order:number;is_active:boolean;archived_at:string|null;products:number;children_count:number};
type Editor={mode:'add'|'edit';id?:string;parentId:string|null}|null;

function InlineCategoryEditor({node,parentId,categories,onDone}:{node?:TreeCategory;parentId:string|null;categories:TreeCategory[];onDone:()=>void}){
  const router=useRouter();
  const [state,action,pending]=useActionState<CategoryActionState,FormData>(saveCategoryInline,{});
  const [fileName,setFileName]=useState('');
  const byId=useMemo(()=>new Map(categories.map(c=>[c.id,c])),[categories]);
  const isInside=(candidate:TreeCategory,nodeId:string)=>{let current:TreeCategory|undefined=candidate;while(current){if(current.id===nodeId)return true;current=current.parent_id?byId.get(current.parent_id):undefined;}return false;};
  useEffect(()=>{if(state.ok){router.refresh();onDone();}},[state.ok,router,onDone]);
  return <tr className="tree-inline-editor"><td colSpan={6}><form action={action}>
    {node&&<input type="hidden" name="id" value={node.id}/>} {!node&&<input type="hidden" name="parentId" value={parentId??''}/>}<div className="tree-editor-heading"><span><b>{node?`Edit ${node.name}`:parentId?`Add child under ${byId.get(parentId)?.name}`:'Add parent category'}</b><small>{node?'Change details, image, or move this category to another parent.':'The new category will appear directly in this branch.'}</small></span><button type="button" onClick={onDone}>Cancel</button></div>
    {state.message&&!state.ok&&<p className="tree-form-error" role="alert">{state.message}</p>}
    <label>Category name<input name="name" required defaultValue={node?.name??''} placeholder="Category name"/></label><label>URL slug<input name="slug" required defaultValue={node?.slug??''} placeholder="category-slug"/></label>
    {node&&<label>Parent category<select name="parentId" defaultValue={node.parent_id??''}><option value="">No parent · top level</option>{categories.filter(c=>c.id!==node.id&&!isInside(c,node.id)&&!c.archived_at).map(c=><option value={c.id} key={c.id}>{'— '.repeat(Math.max(0,c.level-1))}{c.name}</option>)}</select></label>}
    <label>Display order<input name="displayOrder" type="number" min="1" defaultValue={node?.display_order??99}/></label><label>Status<select name="status" defaultValue={node?.archived_at?'archived':node?.is_active?'active':'draft'}><option value="active">Active</option><option value="draft">Paused</option>{node&&<option value="archived">Archived</option>}</select></label>
    <label className="tree-file"><ImageIcon/><span><b>{fileName||'Add category image'}</b><small>PNG, JPG, WebP or SVG · up to 4 MB</small></span><input name="imageFile" type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml,.svg" onChange={e=>setFileName(e.target.files?.[0]?.name??'')}/></label><input name="imageUrl" type="hidden" value={node?.image_url??''}/><input name="iconName" type="hidden" value={node?.icon_name??''}/><input name="description" type="hidden" value={node?.description??''}/><input name="seoTitle" type="hidden" value={node?.seo_title??''}/><input name="seoDescription" type="hidden" value={node?.seo_description??''}/><label className="tree-home"><input name="showOnHomepage" type="checkbox" defaultChecked={node?.show_on_homepage??false}/> Homepage</label><button className="tree-save" disabled={pending}>{pending?'Saving…':node?'Save category':'Create category'}</button>
  </form></td></tr>;
}

export function CategoryTreeManager({categories}:{categories:TreeCategory[]}){
  const [expanded,setExpanded]=useState(()=>new Set(categories.map(c=>c.id))),[editor,setEditor]=useState<Editor>(null),[search,setSearch]=useState('');
  const children=useMemo(()=>{const map=new Map<string|null,TreeCategory[]>();for(const c of categories)map.set(c.parent_id,[...(map.get(c.parent_id)??[]),c]);for(const rows of map.values())rows.sort((a,b)=>a.display_order-b.display_order||a.name.localeCompare(b.name));return map;},[categories]);
  const byId=useMemo(()=>new Map(categories.map(c=>[c.id,c])),[categories]);
  const path=(c:TreeCategory)=>{const names:string[]=[];let current:TreeCategory|undefined=c;while(current){names.unshift(current.slug);current=current.parent_id?byId.get(current.parent_id):undefined;}return `/${names.join('/')}`;};
  const visibleIds=useMemo(()=>{if(!search.trim())return null;const result=new Set<string>(),needle=search.toLowerCase();for(const c of categories)if(`${c.name} ${c.slug}`.toLowerCase().includes(needle)){let current:TreeCategory|undefined=c;while(current){result.add(current.id);current=current.parent_id?byId.get(current.parent_id):undefined;}}return result;},[search,categories,byId]);
  const toggle=(id:string)=>setExpanded(old=>{const next=new Set(old);next.has(id)?next.delete(id):next.add(id);return next;});
  const closeEditor=()=>setEditor(null);
  const rows=(parentId:string|null,depth=0):ReactNode[]=>{const output:ReactNode[]=[];for(const c of children.get(parentId)??[]){if(visibleIds&&!visibleIds.has(c.id))continue;const hasChildren=(children.get(c.id)?.length??0)>0,isOpen=visibleIds?true:expanded.has(c.id),editing=editor?.mode==='edit'&&editor.id===c.id,adding=editor?.mode==='add'&&editor.parentId===c.id;output.push(<tr className={`tree-node ${editing?'selected':''}`} key={c.id}><td><span className="tree-category" style={{paddingLeft:depth*28}}><GripVertical className="tree-grip"/>{hasChildren?<button type="button" className="tree-toggle" onClick={()=>toggle(c.id)} aria-label={`${isOpen?'Collapse':'Expand'} ${c.name}`}>{isOpen?<ChevronDown/>:<ChevronRight/>}</button>:<i className="tree-branch"/>}<span className="tree-thumb">{c.image_url?<img src={c.image_url} alt=""/>:(c.icon_name||'○')}</span><span><b>{c.name}</b><small>{path(c)} · Level {c.level-1}</small></span></span></td><td>{c.products.toLocaleString('en-IN')}</td><td><span className={`ops-chip ${c.archived_at?'bad':c.is_active?'good':'warn'}`}>{c.archived_at?'Archived':c.is_active?'Active':'Paused'}</span></td><td><button type="button" onClick={()=>{setExpanded(x=>new Set(x).add(c.id));setEditor({mode:'add',parentId:c.id});}}><Plus/> Add child</button></td><td><button type="button" onClick={()=>setEditor({mode:'edit',id:c.id,parentId:c.parent_id})}><Pencil/> Edit</button></td><td><button type="button" aria-label={`More actions for ${c.name}`}><MoreHorizontal/></button></td></tr>);if(editing)output.push(<InlineCategoryEditor key={`edit-${c.id}`} node={c} parentId={c.parent_id} categories={categories} onDone={closeEditor}/>);if(adding)output.push(<InlineCategoryEditor key={`add-${c.id}`} parentId={c.id} categories={categories} onDone={closeEditor}/>);if(hasChildren&&isOpen)output.push(...rows(c.id,depth+1));}return output;};
  return <section className="category-tree-workspace"><div className="tree-safety"><ShieldCheck/> Unlimited children · protected from circular nesting</div><header className="tree-toolbar"><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search categories…"/></label><span/><button onClick={()=>setExpanded(new Set(categories.map(c=>c.id)))}><ChevronsUpDown/> Expand all</button><button onClick={()=>setExpanded(new Set())}><ChevronsDownUp/> Collapse all</button><a href="?tab=import"><Upload/> Import</a><a href="/admin/categories/export"><Download/> Export</a><button className="tree-add-parent" onClick={()=>setEditor({mode:'add',parentId:null})}><Plus/> Add parent category</button></header><div className="category-tree-card"><h2>Category tree</h2><div className="table-scroll"><table className="category-tree-model"><thead><tr><th>CATEGORY</th><th>PRODUCTS</th><th>STATUS</th><th colSpan={3}>ACTIONS</th></tr></thead><tbody>{editor?.mode==='add'&&editor.parentId===null&&<InlineCategoryEditor parentId={null} categories={categories} onDone={closeEditor}/>}{rows(null)}</tbody></table></div></div></section>;
}
