import Link from 'next/link';
import { AdminSidebar } from '@/components/admin-sidebar';
import { createClient } from '@/lib/supabase/server';
import { AlertTriangle, ArrowRight, Boxes, CheckCircle2, ChevronDown, CircleDot, Download, FolderTree, GripVertical, ImageOff, LayoutTemplate, PackageOpen, Plus, Search, Upload } from 'lucide-react';
import { addCategory, categoryBulkAction, importCategories, reassignCategoryProducts, updateCategory } from '../actions';

export const dynamic='force-dynamic';
type Params={q?:string;level?:string;status?:string;manage?:string;success?:string};
type Category={id:string;name:string;slug:string;parent_id:string|null;level:number;description:string|null;image_url:string|null;icon_name:string|null;seo_title:string|null;seo_description:string|null;show_on_homepage:boolean;display_order:number;is_active:boolean;archived_at:string|null;updated_at:string|null};
const icon=(name:string)=>name==='Electronics'?'▣':name==='Fashion'?'◇':name.includes('Home')?'⌂':name==='Beauty'?'✦':'○';

export default async function CategoriesPage({searchParams}:{searchParams:Promise<Params>}){
  const query=await searchParams,s=await createClient();
  const [{data:categoryData},{data:products},{data:offers},{data:events}]=await Promise.all([
    s.from('categories').select('id,name,slug,parent_id,level,description,image_url,icon_name,seo_title,seo_description,show_on_homepage,display_order,is_active,archived_at,updated_at').order('display_order'),
    s.from('products').select('id,category_id,brand,is_active'),
    s.from('offers').select('id,status,products(category_id)'),
    s.from('audit_events').select('id,event_type,entity_id,source,created_at').eq('entity_type','category').order('created_at',{ascending:false}).limit(10),
  ]);
  const categories=(categoryData??[]) as Category[],productRows=products??[],offerRows=offers??[];
  const children=new Map<string|null,Category[]>();categories.forEach(c=>children.set(c.parent_id,[...(children.get(c.parent_id)??[]),c]));
  const ordered:Category[]=[];const walk=(parent:string|null)=>{(children.get(parent)??[]).sort((a,b)=>a.display_order-b.display_order).forEach(c=>{ordered.push(c);walk(c.id);});};walk(null);categories.filter(c=>!ordered.some(x=>x.id===c.id)).forEach(c=>ordered.push(c));
  const visible=ordered.filter(c=>(!query.q||`${c.name} ${c.slug}`.toLowerCase().includes(query.q.toLowerCase()))&&(!query.level||query.level==='all'||String(c.level)===query.level)&&(!query.status||query.status==='all'||(query.status==='active'?c.is_active&&!c.archived_at:query.status==='inactive'?!c.is_active&&!c.archived_at:!!c.archived_at)));
  const selected=categories.find(c=>c.id===query.manage),validParents=categories.filter(c=>c.level<3&&c.id!==selected?.id),uncategorized=productRows.filter(p=>!p.category_id).length;
  const productCount=(id:string)=>productRows.filter(p=>p.category_id===id).length,brandCount=(id:string)=>new Set(productRows.filter(p=>p.category_id===id).map(p=>p.brand).filter(Boolean)).size,offerCount=(id:string)=>offerRows.filter(o=>(o.products as unknown as {category_id?:string}|null)?.category_id===id&&o.status==='active').length;
  const missing=categories.filter(c=>!c.image_url&&!c.icon_name).length,empty=categories.filter(c=>productCount(c.id)===0&&(children.get(c.id)?.length??0)===0).length,needsAttention=missing+empty+uncategorized;
  const ancestors=(c?:Category)=>{const path:Category[]=[];let current=c;while(current){path.unshift(current);current=categories.find(x=>x.id===current?.parent_id);}return path;};
  return <main className="admin-v2"><AdminSidebar/><section className="admin-main"><main className="admin-content category-admin-page">
    <div className="admin-title category-title"><div><p>CATALOGUE TAXONOMY</p><h1>Categories</h1><span>Organise the shopping hierarchy used across navigation, search and product discovery.</span></div><div><a className="category-import-link" href="#category-import"><Upload/> Import CSV</a><Link className="category-export-link" href="/admin/categories/export"><Download/> Export</Link><a className="add-store" href="#category-editor"><Plus/> Add category</a></div></div>
    {query.success&&<p className="admin-success"><CheckCircle2/>{query.success}</p>}
    <section className="category-kpis"><a href="#hierarchy"><FolderTree/><span>Total categories<b>{categories.length}</b><small>Complete taxonomy</small></span></a><a href="?level=1"><Boxes/><span>Parent categories<b>{categories.filter(c=>c.level===1).length}</b><small>Level one</small></span></a><a href="?level=2"><CircleDot/><span>Subcategories<b>{categories.filter(c=>c.level>1).length}</b><small>Levels two and three</small></span></a><Link href="/admin/products"><PackageOpen/><span>Active products<b>{productRows.filter(p=>p.is_active).length}</b><small>Assigned catalogue</small></span></Link><Link href="/admin/products?category=unassigned"><AlertTriangle/><span>Unassigned products<b>{uncategorized}</b><small>Needs categorisation</small></span></Link><a href="#category-health"><ImageOff/><span>Needs attention<b>{needsAttention}</b><small>Images, products or assignment</small></span></a></section>
    <section className="category-workspace"><form id="hierarchy" action={categoryBulkAction} className="category-tree-card"><header><div><h2>Category hierarchy</h2><p>Maximum three levels · select rows for bulk actions</p></div><div className="category-filters"><label><Search/><input name="q" defaultValue={query.q} placeholder="Search categories…"/></label><select name="level" defaultValue={query.level||'all'}><option value="all">All levels</option><option value="1">Level 1</option><option value="2">Level 2</option><option value="3">Level 3</option></select><select name="status" defaultValue={query.status||'all'}><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="archived">Archived</option></select><button formAction="/admin/categories">Apply</button></div></header><div className="category-bulk"><span>Bulk action</span><select name="action" defaultValue="pause"><option value="activate">Activate selected</option><option value="pause">Pause selected</option><option value="archive">Archive selected</option></select><button>Apply to selected</button><small>Categories with products or children are archived safely, never hard-deleted.</small></div><div className="table-scroll"><table className="category-tree-table"><thead><tr><th><span className="check-space"/></th><th>CATEGORY</th><th>LEVEL</th><th>SUBCATEGORIES</th><th>BRANDS</th><th>PRODUCTS</th><th>ACTIVE OFFERS</th><th>HOMEPAGE</th><th>STATUS</th><th>ACTION</th></tr></thead><tbody>{visible.map(c=><tr key={c.id}><td><input type="checkbox" name="ids" value={c.id} aria-label={`Select ${c.name}`}/></td><td><span className="category-name-cell" style={{paddingLeft:`${(c.level-1)*22}px`}}><GripVertical/><i>{icon(c.name)}</i><span><b>{c.name}</b><small>{ancestors(c).map(x=>x.name).join(' → ')}</small></span></span></td><td><span className="level-chip">Level {c.level}</span></td><td>{children.get(c.id)?.length??0}</td><td>{brandCount(c.id)}</td><td>{productCount(c.id)}</td><td>{offerCount(c.id)}</td><td><span className={`ops-chip ${c.show_on_homepage?'good':'neutral'}`}>{c.show_on_homepage?'Visible':'Hidden'}</span></td><td><span className={`ops-chip ${c.archived_at?'bad':c.is_active?'good':'warn'}`}>{c.archived_at?'Archived':c.is_active?'Active':'Paused'}</span></td><td><Link className="manage-store" href={`?manage=${c.id}#category-editor`}>Manage <ArrowRight/></Link></td></tr>)}</tbody></table></div><footer><span>Showing {visible.length} of {categories.length} categories</span><span>Parent changes automatically update the hierarchy path.</span></footer></form>
      <aside id="category-editor" className="category-editor"><header><div><p>{selected?'CATEGORY SETTINGS':'NEW CATEGORY'}</p><h2>{selected?`Manage ${selected.name}`:'Add category'}</h2></div>{selected&&<Link href="/admin/categories#category-editor">New <Plus/></Link>}</header><form action={selected?updateCategory:addCategory}>{selected&&<input type="hidden" name="id" value={selected.id}/>}<label>Category name *<input name="name" required defaultValue={selected?.name??''} placeholder="e.g. Footwear"/></label><label>Parent category<select name="parentId" defaultValue={selected?.parent_id??''}><option value="">No parent · Level 1</option>{validParents.map(c=><option value={c.id} key={c.id}>{ancestors(c).map(x=>x.name).join(' → ')}</option>)}</select><small>Selecting a Level 2 parent creates a Level 3 category.</small></label><label>URL slug *<input name="slug" required defaultValue={selected?.slug??''} placeholder="footwear"/></label><label>Icon name<input name="iconName" defaultValue={selected?.icon_name??''} placeholder="shoe, mobile, home…"/></label><label>Image URL<input name="imageUrl" type="url" defaultValue={selected?.image_url??''} placeholder="https://…"/></label><label>Description<textarea name="description" defaultValue={selected?.description??''} placeholder="What shoppers will find here"/></label><fieldset><legend>Search &amp; SEO</legend><label>SEO title<input name="seoTitle" defaultValue={selected?.seo_title??''} placeholder="Category title for search"/></label><label>SEO description<textarea name="seoDescription" defaultValue={selected?.seo_description??''} placeholder="Short search description"/></label></fieldset><div className="category-form-row"><label>Display order<input name="displayOrder" type="number" min="1" defaultValue={selected?.display_order??99}/></label><label>Status<select name="status" defaultValue={selected?.archived_at?'archived':selected?.is_active?'active':'draft'}><option value="active">Active</option><option value="draft">Draft / paused</option>{selected&&<option value="archived">Archived</option>}</select></label></div><label className="category-toggle"><input name="showOnHomepage" type="checkbox" defaultChecked={selected?.show_on_homepage??false}/><span/> Show on homepage</label><div className="hierarchy-preview"><span>Hierarchy preview <small>Maximum 3 levels</small></span><b>{selected?ancestors(selected).map(x=>x.name).join(' → '):'Choose a parent → New category'}</b></div><button className="category-save">{selected?'Save category':'Create category'}</button></form></aside>
    </section>
    <section id="category-health" className="category-lower-grid"><article><header><div><h2>Category health</h2><p>Issues that reduce customer discovery quality.</p></div></header><div className="category-health-grid"><Link href="?status=all#hierarchy"><ImageOff/><span>Missing images or icons<b>{missing}</b><small>Add a recognisable visual</small></span></Link><Link href="?status=all#hierarchy"><PackageOpen/><span>Empty leaf categories<b>{empty}</b><small>No products assigned</small></span></Link><Link href="/admin/products?category=unassigned"><AlertTriangle/><span>Unassigned products<b>{uncategorized}</b><small>Move into the hierarchy</small></span></Link></div></article><article><header><div><h2>Recent category activity</h2><p>Latest audited taxonomy changes.</p></div><Link href="/admin/activity">View all <ArrowRight/></Link></header>{(events??[]).map(e=>{const c=categories.find(x=>x.id===e.entity_id);return <Link className="category-event" href={c?`?manage=${c.id}#category-editor`:'/admin/activity'} key={e.id}><i/><span><b>{e.event_type.replaceAll('_',' ')}</b><small>{c?.name||'Multiple categories'} · {e.source}</small></span><time>{new Date(e.created_at).toLocaleDateString('en-IN')}</time></Link>})}{!(events??[]).length&&<p className="empty-admin">No category activity recorded yet.</p>}</article></section>
    <section className="category-operations"><article><div><p>PRODUCT SAFETY</p><h2>Reassign products before archiving</h2><span>Move every directly assigned product from one category to another without breaking product pages.</span></div><form action={reassignCategoryProducts}><select name="from" required><option value="">Move products from…</option>{categories.map(c=><option value={c.id} key={c.id}>{ancestors(c).map(x=>x.name).join(' → ')}</option>)}</select><ChevronDown/><select name="to" required><option value="">Destination category…</option>{categories.filter(c=>!c.archived_at).map(c=><option value={c.id} key={c.id}>{ancestors(c).map(x=>x.name).join(' → ')}</option>)}</select><button>Reassign products</button></form></article><article id="category-import"><div><p>BULK CATALOGUE</p><h2>Import category CSV</h2><span>Columns: name, parent_slug, description. Imports are limited to 500 rows and created as drafts.</span></div><form action={importCategories}><input name="file" type="file" accept=".csv,text/csv" required/><button><Upload/> Import drafts</button></form></article></section>
    <section className="category-navigation-preview"><header><div><p>SHOPPER EXPERIENCE</p><h2>Navigation preview</h2><span>Only active categories marked for the homepage appear in customer navigation.</span></div><Link href="/" target="_blank">Open storefront <ArrowRight/></Link></header><div className="category-preview-canvas"><div className="category-preview-desktop"><b><LayoutTemplate/> Desktop navigation</b><nav>{categories.filter(c=>c.level===1&&c.is_active&&c.show_on_homepage&&!c.archived_at).slice(0,8).map(c=><span key={c.id}>{icon(c.name)} {c.name}</span>)}</nav></div><div className="category-preview-mobile"><b>Mobile menu</b>{categories.filter(c=>c.level===1&&c.is_active&&c.show_on_homepage&&!c.archived_at).slice(0,5).map(c=><span key={c.id}>{icon(c.name)} {c.name}<ArrowRight/></span>)}</div></div></section>
  </main></section></main>;
}
