import { AdminSidebar } from "@/components/admin-sidebar";
import { Bell, FolderTree, LayoutTemplate, ListChecks, Store } from 'lucide-react';
import { createClient } from '@/lib/supabase/server';

export const dynamic = 'force-dynamic';

export default async function CategoriesPage() {
  const supabase = await createClient();
  const { data: categoryData } = await supabase.from('categories').select('id,name,slug,is_active,display_order').order('display_order');
  const categories = categoryData ?? [];
  const active = categories.filter((category) => category.is_active).length;

  return <main className="admin-v2"><AdminSidebar/><section className="admin-main"><header className="admin-top"><FolderTree size={21} /><b>Categories</b><span className="dashboard-date">Catalogue controls · preview mode</span><Bell size={19} /><span className="avatar">SR</span></header><main className="admin-content"><div className="admin-title"><div><p>CATALOGUE MANAGEMENT</p><h1>Categories</h1><span>Organise customer discovery and decide where each category appears.</span></div><button className="add-store" disabled>＋ Add category</button></div><p className="preview-note">Creation, editing and ordering are prepared for secure admin roles. Current records are read from the Glonni catalogue.</p><section className="admin-stats"><article><FolderTree /><div><small>Total categories</small><b>{categories.length}</b><em>Catalogue structure</em></div></article><article><ListChecks /><div><small>Active</small><b>{active}</b><em>Customer visible</em></div></article><article><LayoutTemplate /><div><small>Homepage slots</small><b>{Math.min(active, 8)}</b><em>Category strip</em></div></article><article><Store /><div><small>Store mappings</small><b>Ready</b><em>Per merchant</em></div></article><article><Bell /><div><small>Review queue</small><b>0</b><em>No pending changes</em></div></article></section><section className="admin-grid"><article className="store-table"><div className="table-head"><div><a className="current">All categories</a><a>Homepage</a><a>Inactive</a></div></div><div className="table-scroll"><table><thead><tr><th>ORDER</th><th>CATEGORY</th><th>URL HANDLE</th><th>HOMEPAGE</th><th>STATUS</th><th>ACTION</th></tr></thead><tbody>{categories.map((category, index) => <tr key={category.id}><td>{category.display_order ?? index + 1}</td><td><span><strong>{category.name}</strong><small>Customer discovery category</small></span></td><td>/{category.slug}</td><td>{index < 8 ? 'Category strip' : 'More categories'}</td><td><em className={category.is_active ? 'status-active' : 'status-paused'}>{category.is_active ? 'Active' : 'Inactive'}</em></td><td><a href="#">Preview</a></td></tr>)}</tbody></table></div><footer>Order controls will govern both desktop and mobile category sections.</footer></article><aside className="admin-right"><article><h2>Customer placement</h2><p>Homepage category strip <span>8 slots</span></p><p>Deals filters <span>All active</span></p><p>Store pages <span>Mapped later</span></p></article><article><h2>Launch readiness</h2><p className="activity">Naming and URL handles visible<small>Review before public launch</small></p><p className="activity">No live provider dependency<small>Safe to configure now</small></p></article></aside></section></main></section></main>;
}
