import { AdminSidebar } from "@/components/admin-sidebar";
import { Bell, CheckSquare, FileSpreadsheet, Link2, PlugZap, ShieldCheck, Store, UploadCloud } from 'lucide-react';

const methods = [
  ['Manual affiliate links', 'Direct approved destination URLs', 'Available now', 'No provider credentials'],
  ['Product feed / CSV', 'Normalised product and offer import', 'Awaiting provider approval', 'Validate before publish'],
  ['Affiliate API', 'Scheduled offer and merchant sync', 'Awaiting provider approval', 'Server-only credentials'],
  ['Deep-link API', 'Generate approved merchant URLs', 'Awaiting provider approval', 'Event logging required'],
];

export default function IntegrationsPage() {
  return <main className="admin-v2"><AdminSidebar/><section className="admin-main"><header className="admin-top"><Link2 size={21} /><b>API Integrations</b><span className="dashboard-date">Connection methods · preview mode</span><Bell size={19} /><span className="avatar">SR</span></header><main className="admin-content"><div className="admin-title"><div><p>INTEGRATION WORKBENCH</p><h1>API Integrations</h1><span>Choose an approved method per provider without changing the customer shopping experience.</span></div><button className="add-store" disabled>Configure integration</button></div><p className="preview-note">No endpoint, token, CSV or provider data is connected. Live secrets will be server-side only and never placed in customer-facing environment variables.</p><section className="admin-stats"><article><Link2 /><div><small>Available methods</small><b>4</b><em>Provider-dependent</em></div></article><article><FileSpreadsheet /><div><small>Pending imports</small><b>0</b><em>No feed uploaded</em></div></article><article><CheckSquare /><div><small>Validation rules</small><b>6</b><em>Before catalogue publish</em></div></article><article><ShieldCheck /><div><small>Secret status</small><b>Clean</b><em>Nothing stored</em></div></article><article><UploadCloud /><div><small>Sync jobs</small><b>0</b><em>Not scheduled</em></div></article></section><section className="admin-grid"><article className="store-table"><div className="table-head"><div><a className="current">Integration methods</a><a>Imports</a><a>Validation</a></div></div><div className="table-scroll"><table><thead><tr><th>METHOD</th><th>USE CASE</th><th>READINESS</th><th>SAFETY RULE</th><th>ACTIVATION</th></tr></thead><tbody>{methods.map((method) => <tr key={method[0]}><td><span><strong>{method[0]}</strong><small>Provider adapter option</small></span></td><td>{method[1]}</td><td>{method[2]}</td><td>{method[3]}</td><td><em className="status-paused">Locked</em></td></tr>)}</tbody></table></div><footer>Every import maps into Product → Offer → Merchant → Provider. Invalid, duplicate or incomplete data must enter a review queue.</footer></article><aside className="admin-right"><article><h2>Import safeguards</h2><p>Schema validation <span>Required</span></p><p>Price freshness <span>Required</span></p><p>Merchant mapping <span>Required</span></p><p>Reward terms <span>Required</span></p></article><article><h2>Secure launch order</h2><p className="activity">Approve provider<small>Commercial and technical access</small></p><p className="activity">Add server secret<small>Never browser-visible</small></p><p className="activity">Run a test import<small>Review before publishing</small></p></article></aside></section></main></section></main>;
}
