import Link from 'next/link';
import { AdminSidebar } from '@/components/admin-sidebar';
import { createClient } from '@/lib/supabase/server';
import { AlertTriangle, ArrowLeft, BadgeIndianRupee, Bot, CheckCircle2, ChevronRight, ExternalLink, FolderTree, HeartPulse, Link2, Package, Pause, Plus, Save, Search, Sparkles, Tag, Trash2, TrendingUp, WalletCards } from 'lucide-react';
import { changeStoreStatus, connectStoreCategories, disconnectStoreCategory, updateStore, updateStorePolicies } from '../../actions';
import { reviewDiscoveryCandidates, runProductDiscovery } from '../../products/ai-discovery-actions';

export const dynamic='force-dynamic';
type Tab='overview'|'catalogue'|'financials'|'policies'|'health';
type Props={params:Promise<{slug:string}>;searchParams:Promise<{success?:string;error?:string;tab?:string;q?:string;category?:string;job?:string}>};
const tabs:{key:Tab;label:string}[]=[{key:'overview',label:'Overview'},{key:'catalogue',label:'Categories & Products'},{key:'financials',label:'Financials'},{key:'policies',label:'Policies'},{key:'health',label:'Store Health'}];
const money=(n:number)=>`₹${Math.round(n).toLocaleString('en-IN')}`;
const chip=(v:string)=>['active','approved','confirmed','published'].includes(v.toLowerCase())?'good':['pending','draft'].includes(v.toLowerCase())?'warn':['paused','rejected'].includes(v.toLowerCase())?'bad':'neutral';

export default async function StoreDetail({params,searchParams}:Props){
 const supabase=await createClient(),slug=(await params).slug,query=await searchParams;
 const tab=tabs.some(x=>x.key===query.tab)?query.tab as Tab:'overview';
 const {data:store}=await supabase.from('merchants').select('id,name,slug,logo_url,storefront_url,is_active,approval_status,review_notes,updated_at').eq('slug',slug).maybeSingle();
 if(!store)return <main className="admin-v2"><AdminSidebar/><section className="admin-main"><main className="admin-content"><div className="empty-store"><h1>Store not found</h1><Link href="/admin"><ArrowLeft/> Back to Stores &amp; Brands</Link></div></main></section></main>;
 const [{data:offers},{data:clicks},{data:conversions},{data:faqs},{data:providers},{data:categories}]=await Promise.all([
  supabase.from('offers').select('id,provider_id,current_price,list_price,reward_type,cashback_amount,cashback_percent,cashback_tracking_supported,reward_terms,coupon_code,bank_offer,status,updated_at,products(id,title,slug,brand,image_url,category_id,is_active,categories(id,name,slug))').eq('merchant_id',store.id).order('updated_at',{ascending:false}),
  supabase.from('redirect_events').select('id,created_at').eq('merchant_id',store.id).limit(1000),
  supabase.from('referral_conversions').select('id,status,order_value,commission_amount,cashback_amount,created_at').eq('merchant_id',store.id).order('created_at',{ascending:false}).limit(1000),
  supabase.from('support_faqs').select('id,question,answer,is_active').eq('merchant_id',store.id).order('display_order'),
  supabase.from('affiliate_providers').select('id,name,integration_mode,is_active'),
  supabase.from('categories').select('id,name,slug,parent_id,level,is_active').eq('is_active',true).order('display_order'),
 ]);
 const rows=offers??[],confirmed=(conversions??[]).filter(x=>x.status==='confirmed'),provider=(providers??[]).find(x=>x.id===rows.find(x=>x.provider_id)?.provider_id);
 let noteData:{internalNote?:string;policies?:Record<string,string>;storeCategoryIds?:string[]}={};try{noteData=JSON.parse(store.review_notes||'{}')}catch{noteData={internalNote:store.review_notes||''}}const policies=noteData.policies??{},glonniTerms=policies.glonniTerms??policies.termsConditions??'',storeTerms=policies.storeTerms??[policies.customerNotice,policies.returnsPolicy].filter(Boolean).join('\n\n'),cashbackTerms=policies.cashbackTerms??policies.cashbackRules??'';
 const productMap=new Map<string,any>();for(const offer of rows){const p=Array.isArray(offer.products)?offer.products[0]:offer.products;if(p?.id)productMap.set(p.id,{...p,offer});}
 const counts=new Map<string,number>();for(const p of productMap.values())if(p.category_id)counts.set(p.category_id,(counts.get(p.category_id)||0)+1);
 const hasManagedCategories=Array.isArray(noteData.storeCategoryIds),connectedIds=new Set(hasManagedCategories?(noteData.storeCategoryIds??[]):[...counts.keys()]);const linkedCategories=(categories??[]).filter(c=>connectedIds.has(c.id));
 const descendantIds=(id:string)=>{const result=new Set([id]);let changed=true;while(changed){changed=false;for(const c of categories??[])if(c.parent_id&&result.has(c.parent_id)&&!result.has(c.id)){result.add(c.id);changed=true}}return result};
 const selectedIds=query.category?descendantIds(query.category):null;
 const products=[...productMap.values()].filter(p=>(!selectedIds||selectedIds.has(p.category_id))&&(!query.q||`${p.title} ${p.brand??''}`.toLowerCase().includes(query.q.toLowerCase())));
 const selectedCategory=(categories??[]).find(c=>c.id===query.category);
 const {data:candidates}=query.job?await supabase.from('ai_discovery_candidates').select('id,title,brand,category_id,image_url,confidence,status,missing_fields,product_draft_id').eq('job_id',query.job).order('position'):{data:[]};
 const commission=confirmed.reduce((n,x)=>n+Number(x.commission_amount||0),0),cashback=confirmed.reduce((n,x)=>n+Number(x.cashback_amount||0),0),rate=(clicks?.length??0)?confirmed.length/(clicks?.length??1)*100:0;
 const missingTerms=rows.filter(x=>x.reward_type?.includes('cashback')&&!x.reward_terms).length,missingTracking=rows.filter(x=>x.reward_type?.includes('cashback')&&!x.cashback_tracking_supported).length,inactiveProducts=[...productMap.values()].filter(p=>!p.is_active).length;
 const health=Math.max(0,100-(store.storefront_url?0:25)-(provider?.is_active?0:25)-Math.min(25,missingTerms*5)-Math.min(25,inactiveProducts*2));
 const href=(key:Tab,hash='')=>`/admin/stores/${store.slug}?tab=${key}${hash}`;
 return <main className="admin-v2"><AdminSidebar/><section className="admin-main"><main className="admin-content manage-store-page">
  <div className="store-breadcrumb"><Link href="/admin">Stores &amp; Brands</Link><span>/</span><b>{store.name}</b></div>
  <header className="store-profile-head"><div className="store-identity">{store.logo_url?<img src={store.logo_url} alt=""/>:<i>{store.name.slice(0,1)}</i>}<span><h1>{store.name}</h1><a href={store.storefront_url||'#'} target="_blank" rel="noreferrer">{store.storefront_url?.replace(/^https?:\/\//,'')||'Website not configured'} <ExternalLink/></a></span><em className={`ops-chip ${store.is_active?'good':'bad'}`}>{store.is_active?'Active':'Paused'}</em></div><div className="store-head-actions"><Link href={`/store/${store.slug}`} target="_blank">View customer page <ExternalLink/></Link><form action={changeStoreStatus}><input type="hidden" name="id" value={store.id}/><input type="hidden" name="slug" value={store.slug}/><input type="hidden" name="action" value={store.is_active?'pause':'resume'}/><button><Pause/> {store.is_active?'Pause store':'Resume store'}</button></form><Link className="primary" href={href('overview','#store-details')}><Save/> Edit store details</Link></div></header>
  {query.success&&<p className="admin-success"><CheckCircle2/>{query.success}</p>}
  <nav className="store-detail-tabs">{tabs.map(x=><Link className={tab===x.key?'active':''} href={href(x.key)} key={x.key}>{x.label}{x.key==='health'&&<span className={`tab-health-dot ${health>=80?'good':health>=60?'warn':'bad'}`}/>}</Link>)}</nav>

  {tab==='overview'&&<><section className="store-detail-kpis"><Link href={href('catalogue')}><Package/><span>Products<b>{productMap.size}</b><small>Manage store catalogue</small></span></Link><Link href={href('catalogue')}><Tag/><span>Categories<b>{linkedCategories.length}</b><small>Connected paths</small></span></Link><Link href={href('policies')}><WalletCards/><span>Cashback offers<b>{rows.filter(x=>x.reward_type?.includes('cashback')).length}</b><small>Review store policies</small></span></Link><Link href={href('financials')}><BadgeIndianRupee/><span>Commission<b>{money(commission)}</b><small>Confirmed earnings</small></span></Link><Link href={href('financials')}><TrendingUp/><span>Conversion rate<b>{rate.toFixed(1)}%</b><small>{confirmed.length} conversions</small></span></Link><Link href={href('health')}><HeartPulse/><span>Store health<b>{health}%</b><small>{health>=80?'Healthy':'Needs attention'}</small></span></Link></section>
   <section className="store-overview-grid"><article className="store-console-card health-summary"><header><div><p>STORE HEALTH</p><h2>{health>=80?'Everything looks healthy':'Items need attention'}</h2></div><span className={`health-score ${health>=80?'good':health>=60?'warn':'bad'}`}>{health}%</span></header><div className="health-progress"><i style={{width:`${health}%`}}/></div><p>Provider data, catalogue completeness, cashback terms and customer visibility are checked together.</p><Link className="inline-action" href={href('health')}>Open Store Health</Link></article><article className="store-console-card ai-intake"><header><div><p>AI PRODUCT INTAKE</p><h2>Fetch products for {store.name}</h2></div><Bot/></header><p>Find products sold by this store, then review and connect them to your existing catalogue.</p><div><Link className="console-button" href={href('catalogue','#ai-intake')}><Sparkles/> Fetch with AI</Link><Link className="secondary-action" href={href('catalogue')}>Review products</Link></div></article></section>
   <section id="store-details" className="store-manage-grid overview-details"><article className="store-console-card store-details-card"><header><div><p>STORE IDENTITY</p><h2>Store details</h2></div><span className={`ops-chip ${chip(store.approval_status||'draft')}`}>{store.approval_status||'draft'}</span></header><form action={updateStore} className="store-console-form"><input type="hidden" name="id" value={store.id}/><input type="hidden" name="slug" value={store.slug}/><label>Display name<input name="name" required defaultValue={store.name}/></label><label>Website URL<input name="url" type="url" required defaultValue={store.storefront_url??''}/></label><label className="wide">Internal review notes<textarea name="reviewNotes" defaultValue={noteData.internalNote??''}/></label><button><Save/> Save store details</button></form></article></section></>}

  {tab==='catalogue'&&<section className="store-tab-panel store-catalogue-panel"><PanelHead eyebrow="STORE CATALOGUE" title={`${store.name} categories & products`} copy={`Manage ${store.name} products inside the correct catalogue hierarchy.`}/><div className="store-catalogue-layout"><CategorySidebar store={store} categories={categories??[]} linked={linkedCategories} selected={selectedCategory} products={[...productMap.values()]}/><main className="store-category-content"><header className="selected-category-head"><div><p>{selectedCategory?categoryPath(selectedCategory,categories??[]).join(' / '):'STORE CATALOGUE'}</p><h2>{selectedCategory?.name??'All products'}</h2><span>{products.length} {store.name} products</span></div>{selectedCategory&&connectedIds.has(selectedCategory.id)&&<form action={disconnectStoreCategory}><input type="hidden" name="id" value={store.id}/><input type="hidden" name="slug" value={store.slug}/><input type="hidden" name="categoryId" value={selectedCategory.id}/><button className="remove-store-category"><Trash2/> Remove category</button></form>}</header><p className="store-global-note"><CheckCircle2/> Approved products also appear under All products and Global Products.</p><StoreAiDiscovery store={store} category={selectedCategory} jobId={query.job} candidates={candidates??[]}/><div id="ai-intake" className="store-inline-toolbar"><form><input type="hidden" name="tab" value="catalogue"/>{query.category&&<input type="hidden" name="category" value={query.category}/>}<Search/><input name="q" defaultValue={query.q} placeholder={`Search ${selectedCategory?.name??store.name} products`}/><button>Search</button></form><span>{products.length} products</span></div><div className="table-scroll"><table className="store-inside-table"><thead><tr><th>PRODUCT</th><th>BRAND</th><th>CATEGORY</th><th>PRICE</th><th>OFFER</th><th>STATUS</th><th>ACTION</th></tr></thead><tbody>{products.map(p=><tr id={`product-${p.id}`} key={p.id}><td><span className="store-product-cell">{p.image_url?<img src={p.image_url} alt=""/>:<i><Package/></i>}<b>{p.title}</b></span></td><td>{p.brand||'Not assigned'}</td><td>{p.categories?.name||'Uncategorised'}</td><td>{money(Number(p.offer.current_price||0))}</td><td><span className={`ops-chip ${chip(p.offer.status)}`}>{p.offer.status}</span></td><td><span className={`ops-chip ${p.is_active?'good':'warn'}`}>{p.is_active?'Published':'Draft'}</span></td><td><button className="table-edit-button">Review here</button></td></tr>)}{!products.length&&<tr><td colSpan={7}>No matching products are connected to this category yet.</td></tr>}</tbody></table></div></main></div></section>}

  {tab==='financials'&&<section className="store-tab-panel"><PanelHead eyebrow="STORE FINANCIALS" title={`${store.name} earnings & obligations`} copy="Financial records are filtered to this store only."/><div className="financial-summary"><Metric icon={<BadgeIndianRupee/>} label="Confirmed commission" value={money(commission)}/><Metric icon={<WalletCards/>} label="Cashback liability" value={money(cashback)}/><Metric icon={<Link2/>} label="Tracked clicks" value={String(clicks?.length??0)}/><Metric icon={<CheckCircle2/>} label="Confirmed conversions" value={String(confirmed.length)}/></div><div className="table-scroll"><table className="store-inside-table"><thead><tr><th>DATE</th><th>STATUS</th><th>ORDER VALUE</th><th>COMMISSION</th><th>CUSTOMER CASHBACK</th></tr></thead><tbody>{(conversions??[]).map(r=><tr key={r.id}><td>{new Date(r.created_at).toLocaleDateString('en-IN')}</td><td><span className={`ops-chip ${chip(r.status)}`}>{r.status}</span></td><td>{money(Number(r.order_value||0))}</td><td>{money(Number(r.commission_amount||0))}</td><td>{money(Number(r.cashback_amount||0))}</td></tr>)}{!conversions?.length&&<tr><td colSpan={5}>No conversion records are available for this store.</td></tr>}</tbody></table></div></section>}

  {tab==='policies'&&<section className="store-tab-panel"><PanelHead eyebrow="CUSTOMER TERMS" title={`${store.name} policies`} copy={`Edit the three policy sections shown automatically on the ${store.name} store page and its products.`}/><form action={updateStorePolicies} className="three-policy-editor"><input type="hidden" name="id" value={store.id}/><input type="hidden" name="slug" value={store.slug}/><details open><summary><span><b>1</b><i><strong>Glonni Terms</strong><small>Platform journey, tracking, wallet, withdrawal and coupon rules</small></i></span><ChevronRight/></summary><div><p>These terms explain Glonni's role before the customer continues to the merchant.</p><label>Terms shown to customers<textarea name="glonniTerms" rows={12} defaultValue={glonniTerms} placeholder="Explain affiliate redirection, tracking requirements, confirmation, wallet credit, withdrawals, coupons, account eligibility and misuse rules."/></label></div></details><details><summary><span><b>2</b><i><strong>Store Terms</strong><small>Rules that apply specifically to this merchant</small></i></span><ChevronRight/></summary><div><p>Add only the rules that differ for {store.name}, including exclusions, coupons, returns and purchasing restrictions.</p><label>{store.name} terms shown to customers<textarea name="storeTerms" rows={12} defaultValue={storeTerms} placeholder={`Enter ${store.name}-specific eligibility, category exclusions, coupon rules, returns, cancellations, app or website requirements and claim restrictions.`}/></label></div></details><details><summary><span><b>3</b><i><strong>Cashback Terms</strong><small>Eligibility, tracking stages, confirmation days and payout timing</small></i></span><ChevronRight/></summary><div><p>Explain exactly how this store's cashback progresses from purchase to withdrawal.</p><label>Cashback terms shown to customers<textarea name="cashbackTerms" rows={12} defaultValue={cashbackTerms} placeholder="Explain the cashback rate, tracking time, pending period, confirmation interval, return window, withdrawal availability, claim deadline and rejection reasons."/></label><div className="cashback-term-timeline"><span><b>Day 0</b><small>Purchase</small></span><i/><span><b>Tracking</b><small>Order detected</small></span><i/><span><b>Pending</b><small>Merchant review</small></span><i/><span><b>Confirmed</b><small>Cashback available</small></span></div></div></details><footer><div><CheckCircle2/><span><b>Connected to customer pages</b><small>Saving updates the public store page and product pages carrying this store's offer.</small></span></div><button><Save/> Save all three policy sections</button></footer></form></section>}

  {tab==='health'&&<section className="store-tab-panel"><header className="store-panel-heading"><div><p>OPERATIONAL READINESS</p><h2>{store.name} Store Health</h2><span>Catalogue, rewards, provider data and customer readiness in one place.</span></div><span className={`large-health-score ${health>=80?'good':health>=60?'warn':'bad'}`}>{health}%<small>{health>=80?'Healthy':'Needs attention'}</small></span></header><div className="health-check-grid"><Health title="Provider data" copy={provider?.is_active?`${provider.name} is supplying active store data.`:'No active provider feed is available.'} pass={!!provider?.is_active}/><Health title="Product readiness" copy={inactiveProducts?`${inactiveProducts} products are still drafts.`:'All connected products are published.'} pass={!inactiveProducts}/><Health title="Cashback terms" copy={missingTerms?`${missingTerms} cashback offers are missing terms.`:'All cashback offers have terms.'} pass={!missingTerms}/><Health title="Customer destination" copy={store.storefront_url?'The public store destination is configured.':'The store website is missing.'} pass={!!store.storefront_url}/></div></section>}
 </main></section></main>;
}

function PanelHead({eyebrow,title,copy,action}:{eyebrow:string;title:string;copy:string;action?:string}){return <header className="store-panel-heading"><div><p>{eyebrow}</p><h2>{title}</h2><span>{copy}</span></div>{action&&<button className="primary-panel-action"><Sparkles/>{action}</button>}</header>}
function Empty({icon,title,copy}:{icon:React.ReactNode;title:string;copy:string}){return <div className="store-empty-panel">{icon}<h3>{title}</h3><p>{copy}</p></div>}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <article>{icon}<span>{label}<b>{value}</b></span></article>}
function Health({title,copy,pass}:{title:string;copy:string;pass:boolean}){return <article><span className={pass?'pass':'warn'}>{pass?<CheckCircle2/>:<AlertTriangle/>}</span><div><h3>{title}</h3><p>{copy}</p></div><b>{pass?'Healthy':'Attention'}</b></article>}
function categoryPath(category:any,categories:any[]){const path=[category];let parent=category.parent_id?categories.find(x=>x.id===category.parent_id):null;while(parent){path.unshift(parent);parent=parent.parent_id?categories.find(x=>x.id===parent.parent_id):null}return path.map(x=>x.name)}
function CategorySidebar({store,categories,linked,selected,products}:{store:any;categories:any[];linked:any[];selected?:any;products:any[]}){
 const linkedIds=new Set(linked.map(x=>x.id));for(const item of linked){let parent=item.parent_id?categories.find(x=>x.id===item.parent_id):null;while(parent){linkedIds.add(parent.id);parent=parent.parent_id?categories.find(x=>x.id===parent.parent_id):null}}
 const visible=categories.filter(c=>linkedIds.has(c.id));
 const countFor=(id:string)=>{const ids=new Set([id]);let changed=true;while(changed){changed=false;for(const c of categories)if(c.parent_id&&ids.has(c.parent_id)&&!ids.has(c.id)){ids.add(c.id);changed=true}}return products.filter(p=>ids.has(p.category_id)).length};
 const path=(c:any)=>categoryPath(c,categories).join(' › ');
 return <aside className="store-category-sidebar"><header><div><h3>Categories</h3><p>{store.name} catalogue</p></div><details className="store-category-add"><summary aria-label="Connect catalogue categories"><Plus/></summary><form action={connectStoreCategories}><input type="hidden" name="id" value={store.id}/><input type="hidden" name="slug" value={store.slug}/><header><div><h3>Connect categories</h3><p>Select categories from your existing catalogue.</p></div></header><div className="category-picker-scroll"><CategoryPickerTree categories={categories} parentId={null} linked={linked} path={path}/></div><footer><span>Select one or more categories</span><button>Add categories</button></footer></form></details></header><label className="category-side-search"><Search/><input placeholder="Search categories"/></label><nav><Link className={!selected?'active':''} href={`/admin/stores/${store.slug}?tab=catalogue`}><FolderTree/><span>All products</span><b>{products.length}</b></Link><CategoryNavTree categories={visible} parentId={null} store={store} selected={selected} countFor={countFor}/></nav></aside>
}
function CategoryNavTree({categories,parentId,store,selected,countFor}:{categories:any[];parentId:string|null;store:any;selected?:any;countFor:(id:string)=>number}){
 return <>{categories.filter(c=>c.parent_id===parentId).map(c=>{const children=categories.filter(x=>x.parent_id===c.id);const active=selected?.id===c.id;return children.length?<details className="category-nav-branch" open key={c.id}><summary><ChevronRight/><Tag/><Link className={active?'active':''} href={`/admin/stores/${store.slug}?tab=catalogue&category=${c.id}`}><span>{c.name}</span><b>{countFor(c.id)}</b></Link></summary><div><CategoryNavTree categories={categories} parentId={c.id} store={store} selected={selected} countFor={countFor}/></div></details>:<Link className={`category-nav-leaf ${active?'active':''}`} href={`/admin/stores/${store.slug}?tab=catalogue&category=${c.id}`} key={c.id}><Tag/><span>{c.name}</span><b>{countFor(c.id)}</b></Link>})}</>
}
function CategoryPickerTree({categories,parentId,linked,path}:{categories:any[];parentId:string|null;linked:any[];path:(c:any)=>string}){
 return <>{categories.filter(c=>c.parent_id===parentId).map(c=>{const children=categories.filter(x=>x.parent_id===c.id);return <div className="category-picker-node" key={c.id}><div className="category-picker-row"><label><input type="checkbox" name="categoryId" value={c.id} defaultChecked={linked.some(x=>x.id===c.id)}/><span>{c.name}<small>{path(c)}</small></span></label>{children.length?<details><summary aria-label={`Open ${c.name} subcategories`}><ChevronRight/></summary><div><CategoryPickerTree categories={categories} parentId={c.id} linked={linked} path={path}/></div></details>:null}</div></div>})}</>
}
function StoreAiDiscovery({store,category,jobId,candidates}:{store:any;category?:any;jobId?:string;candidates:any[]}){
 const returnTo=`/admin/stores/${store.slug}?tab=catalogue${category?`&category=${category.id}`:''}`;
 return <section className="store-ai-discovery"><form action={runProductDiscovery} className="store-ai-command"><div><Sparkles/><span><b>Fetch with AI{category?` — ${category.name}`:''}</b><small>Research products sold by {store.name}; every result requires your approval.</small></span></div><input type="hidden" name="merchantId" value={store.id}/><input type="hidden" name="categoryId" value={category?.id??''}/><input type="hidden" name="returnTo" value={returnTo}/><input name="query" required minLength={5} defaultValue={`Fetch top products sold by ${store.name}${category?` in ${category.name}`:''}. Return accurate models, images, brand, category and source links for admin review.`}/><button><Sparkles/> Fetch with AI</button></form>{jobId&&<div className="store-ai-results"><header><div><h3>AI review queue</h3><p>Approval creates a global inactive product draft assigned to this category. It remains unpublished until your final review.</p></div><b>{candidates.length} found</b></header>{candidates.map(item=><article key={item.id}>{item.image_url?<img src={item.image_url} alt=""/>:<span className="candidate-placeholder"><Package/></span>}<div><h4>{item.title}</h4><p>{item.brand||'Brand not verified'} · {Number(item.confidence||0).toFixed(0)}% confidence</p><small>{item.missing_fields?.length?`Missing: ${item.missing_fields.join(', ')}`:'No missing fields reported'}</small></div><em className={`ops-chip ${item.status==='pending_review'?'warn':item.status==='approved_to_draft'?'good':'neutral'}`}>{item.status.replaceAll('_',' ')}</em>{item.status==='pending_review'?<form action={reviewDiscoveryCandidates}><input type="hidden" name="jobId" value={jobId}/><input type="hidden" name="candidateId" value={item.id}/><input type="hidden" name="returnTo" value={`${returnTo}&job=${jobId}`}/><button name="decision" value="reject">Reject</button><button className="approve" name="decision" value="approve">Approve to global draft</button></form>:item.product_draft_id?<span className="draft-created">Global draft created</span>:null}</article>)}{!candidates.length&&<p className="empty-admin">AI returned no reviewable products for this category.</p>}</div>}</section>
}
