import Link from 'next/link';
import { AdminSidebar } from '@/components/admin-sidebar';
import { createClient } from '@/lib/supabase/server';
import { Activity, ArrowLeft, ArrowRight, BadgeIndianRupee, CheckCircle2, ExternalLink, Globe2, Link2, Package, Pause, RefreshCw, Save, ShieldCheck, Tag, TrendingUp, WalletCards } from 'lucide-react';
import { addSupportFaq, changeStoreStatus, updateStore } from '../../actions';

export const dynamic = 'force-dynamic';
type Props={params:Promise<{slug:string}>;searchParams:Promise<{success?:string}>};
const money=(n:number)=>`₹${Math.round(n).toLocaleString('en-IN')}`;
const chip=(value:string)=>['active','approved','confirmed','published'].includes(value.toLowerCase())?'good':['pending','draft'].includes(value.toLowerCase())?'warn':['paused','rejected'].includes(value.toLowerCase())?'bad':'neutral';

export default async function StoreDetail({params,searchParams}:Props){
  const supabase=await createClient(), slug=(await params).slug, notice=(await searchParams).success;
  const {data:store}=await supabase.from('merchants').select('id,name,slug,logo_url,storefront_url,is_active,approval_status,homepage_position,review_notes,created_at,updated_at').eq('slug',slug).maybeSingle();
  if(!store)return <main className="admin-v2"><AdminSidebar/><section className="admin-main"><main className="admin-content"><div className="empty-store"><h1>Store not found</h1><Link href="/admin"><ArrowLeft/> Back to Stores &amp; Brands</Link></div></main></section></main>;
  const [{data:offers},{data:clicks},{data:conversions},{data:faqs},{data:campaigns},{data:events},{data:providers}]=await Promise.all([
    supabase.from('offers').select('id,provider_id,current_price,list_price,reward_type,cashback_amount,cashback_percent,cashback_tracking_supported,reward_terms,status,updated_at,products(title,brand,categories(name))').eq('merchant_id',store.id).order('updated_at',{ascending:false}),
    supabase.from('redirect_events').select('id,created_at').eq('merchant_id',store.id).order('created_at',{ascending:false}).limit(1000),
    supabase.from('referral_conversions').select('id,status,order_value,commission_amount,cashback_amount,created_at').eq('merchant_id',store.id).order('created_at',{ascending:false}).limit(1000),
    supabase.from('support_faqs').select('id,question,answer,is_active').eq('merchant_id',store.id).order('display_order'),
    supabase.from('homepage_campaigns').select('id,title,placement,status,offer_id').order('display_order'),
    supabase.from('audit_events').select('id,event_type,source,created_at,metadata').eq('entity_type','merchant').eq('entity_id',store.id).order('created_at',{ascending:false}).limit(12),
    supabase.from('affiliate_providers').select('id,name,integration_mode,is_active'),
  ]);
  const offerRows=offers??[], confirmed=(conversions??[]).filter(x=>x.status==='confirmed'), provider=(providers??[]).find(x=>x.id===offerRows.find(x=>x.provider_id)?.provider_id), offerIds=new Set(offerRows.map(x=>x.id));
  const placements=(campaigns??[]).filter(x=>x.offer_id&&offerIds.has(x.offer_id)), commission=confirmed.reduce((n,x)=>n+Number(x.commission_amount||0),0), cashback=confirmed.reduce((n,x)=>n+Number(x.cashback_amount||0),0), rate=(clicks?.length??0)?confirmed.length/(clicks?.length??1)*100:0;
  return <main className="admin-v2"><AdminSidebar/><section className="admin-main"><main className="admin-content manage-store-page">
    <div className="store-breadcrumb"><Link href="/admin">Stores &amp; Brands</Link><span>/</span><b>{store.name}</b></div>
    <header className="store-profile-head"><div className="store-identity">{store.logo_url?<img src={store.logo_url} alt=""/>:<i>{store.name.slice(0,1)}</i>}<span><h1>{store.name}</h1><a href={store.storefront_url||'#'} target="_blank" rel="noreferrer">{store.storefront_url?.replace(/^https?:\/\//,'')||'Website not configured'} <ExternalLink/></a></span><em className={`ops-chip ${store.is_active?'good':'bad'}`}>{store.is_active?'Active':'Paused'}</em><em className={`ops-chip ${provider?'good':'neutral'}`}>{provider?'Connected':'Manual source'}</em></div><div className="store-head-actions"><Link href={`/store/${store.slug}`} target="_blank">View customer page <ExternalLink/></Link><Link href="#connection"><RefreshCw/> Sync details</Link><form action={changeStoreStatus}><input type="hidden" name="id" value={store.id}/><input type="hidden" name="slug" value={store.slug}/><input type="hidden" name="action" value={store.is_active?'pause':'resume'}/><button><Pause/> {store.is_active?'Pause store':'Resume store'}</button></form><a className="primary" href="#store-details"><Save/> Save changes</a></div></header>
    {notice&&<p className="admin-success"><CheckCircle2/>{notice}</p>}
    <nav className="store-detail-tabs"><a href="#overview">Overview</a><a href="#connection">Affiliate connection</a><Link href={`/admin/offers?q=${encodeURIComponent(store.name)}`}>Offers &amp; rewards</Link><Link href={`/admin/products?store=${encodeURIComponent(store.slug)}`}>Products &amp; categories</Link><a href="#rules">Cashback rules</a><Link href={`/admin/wallet?merchant=${encodeURIComponent(store.slug)}`}>Financials</Link><Link href={`/admin/analytics?merchant=${encodeURIComponent(store.slug)}`}>Performance</Link><a href="#placement">Display placement</a><a href="#policy">Policy &amp; compliance</a><a href="#activity">Activity log</a></nav>
    <section id="overview" className="store-detail-kpis"><Link href={`/admin/offers?q=${encodeURIComponent(store.name)}&status=active`}><Tag/><span>Active offers<b>{offerRows.filter(x=>x.status==='active').length}</b><small>View offer inventory</small></span></Link><Link href={`/admin/orders?merchant=${store.slug}`}><Link2/><span>Outbound clicks<b>{clicks?.length??0}</b><small>Tracked referrals</small></span></Link><Link href={`/admin/orders?merchant=${store.slug}`}><CheckCircle2/><span>Conversions<b>{confirmed.length}</b><small>Provider-confirmed</small></span></Link><Link href={`/admin/wallet?merchant=${store.slug}`}><BadgeIndianRupee/><span>Commission<b>{money(commission)}</b><small>Confirmed earnings</small></span></Link><Link href={`/admin/wallet?merchant=${store.slug}`}><WalletCards/><span>Cashback liability<b>{money(cashback)}</b><small>Customer obligation</small></span></Link><Link href={`/admin/analytics?merchant=${store.slug}`}><TrendingUp/><span>Conversion rate<b>{rate.toFixed(1)}%</b><small>Clicks to confirmation</small></span></Link></section>
    <section className="store-manage-grid"><article id="store-details" className="store-console-card store-details-card"><header><div><p>STORE IDENTITY</p><h2>Store details</h2></div><span className={`ops-chip ${chip(store.approval_status||'draft')}`}>{store.approval_status||'draft'}</span></header><form action={updateStore} className="store-console-form"><input type="hidden" name="id" value={store.id}/><input type="hidden" name="slug" value={store.slug}/><label>Display name<input name="name" required defaultValue={store.name}/></label><label>Website URL<input name="url" type="url" required defaultValue={store.storefront_url??''}/></label><label>Homepage display order<input name="homepagePosition" type="number" min="1" defaultValue={store.homepage_position??99}/></label><label className="wide">Internal review notes<textarea name="reviewNotes" defaultValue={store.review_notes??''} placeholder="Provider, reward or publishing notes"/></label><button><Save/> Save store details</button></form></article>
      <article id="connection" className="store-console-card"><header><div><p>DATA SOURCE</p><h2>Affiliate connection</h2></div><Link href="/admin/providers">Configure <ArrowRight/></Link></header><dl className="console-list"><div><dt>Provider</dt><dd>{provider?.name||'Manual catalogue'}</dd></div><div><dt>Integration mode</dt><dd>{provider?.integration_mode?.replaceAll('_',' ')||'Manual'}</dd></div><div><dt>Connection status</dt><dd><span className={`ops-chip ${provider?'good':'neutral'}`}>{provider?'Connected':'Not connected'}</span></dd></div><div><dt>Last store update</dt><dd>{store.updated_at?new Date(store.updated_at).toLocaleString('en-IN'):'Not recorded'}</dd></div><div><dt>API health</dt><dd>{provider?.is_active?'Ready':'No live API'}</dd></div></dl><Link className="console-button" href="/admin/integrations"><RefreshCw/> Open integrations</Link></article>
      <article id="rules" className="store-console-card"><header><div><p>CUSTOMER REWARDS</p><h2>Cashback &amp; offer rules</h2></div><Link href={`/admin/offers?q=${encodeURIComponent(store.name)}`}>Manage <ArrowRight/></Link></header><dl className="console-list"><div><dt>Tracking-supported offers</dt><dd>{offerRows.filter(x=>x.cashback_tracking_supported).length}</dd></div><div><dt>Cashback offers</dt><dd>{offerRows.filter(x=>x.reward_type?.includes('cashback')).length}</dd></div><div><dt>Approved rule text</dt><dd>{offerRows.filter(x=>x.reward_terms).length} / {offerRows.length}</dd></div><div><dt>Customer FAQs</dt><dd>{faqs?.length??0}</dd></div></dl><details><summary>Store cashback FAQs</summary>{(faqs??[]).map(f=><p className="console-faq" key={f.id}><b>{f.question}</b><span>{f.answer}</span></p>)}<form action={addSupportFaq} className="console-faq-form"><input type="hidden" name="scope" value="merchant"/><input type="hidden" name="merchantId" value={store.id}/><input name="question" required minLength={5} placeholder="Customer question"/><textarea name="answer" required minLength={10} placeholder="Approved answer"/><input name="keywords" placeholder="Search keywords"/><button>Add FAQ</button></form></details></article>
      <article id="placement" className="store-console-card"><header><div><p>STOREFRONT</p><h2>Display placement</h2></div><Link href="/admin/offers?tab=placement">Manage <ArrowRight/></Link></header>{placements.length?placements.map(x=><Link className="placement-row" href={`/admin/offers?tab=placement#${x.id}`} key={x.id}><span><b>{x.title}</b><small>{x.placement.replaceAll('_',' ')}</small></span><em className={`ops-chip ${chip(x.status)}`}>{x.status}</em></Link>):<p className="empty-admin">No published homepage placement uses this store yet.</p>}<p className="placement-note"><Globe2/> Public store page: <b>/store/{store.slug}</b></p></article>
      <article id="policy" className="store-console-card"><header><div><p>GOVERNANCE</p><h2>Policy &amp; compliance</h2></div><Link href={`/admin/offers?q=${encodeURIComponent(store.name)}`}>Review <ArrowRight/></Link></header><p className="policy-check"><CheckCircle2/> Approved destination configured <span>{store.storefront_url?'Passed':'Missing'}</span></p><p className="policy-check"><CheckCircle2/> Offer reward terms <span>{offerRows.every(x=>!x.reward_type?.includes('cashback')||x.reward_terms)?'Passed':'Needs review'}</span></p><p className="policy-check"><ShieldCheck/> Cashback tracking claim <span>{offerRows.every(x=>!x.reward_type?.includes('cashback')||x.cashback_tracking_supported)?'Passed':'Needs review'}</span></p><p className="policy-check"><Package/> Public visibility <span>{store.is_active?'Enabled':'Paused'}</span></p></article>
    </section>
    <section id="activity" className="store-activity-card"><header><div><Activity/><span><h2>Recent store activity</h2><p>Store-specific changes recorded in the audit history.</p></span></div><Link href={`/admin/activity?entity=${store.id}`}>View full activity <ArrowRight/></Link></header><div className="table-scroll"><table><thead><tr><th>DATE &amp; TIME</th><th>ACTIVITY</th><th>SOURCE</th><th>DETAILS</th></tr></thead><tbody>{(events??[]).map(event=><tr key={event.id}><td>{new Date(event.created_at).toLocaleString('en-IN')}</td><td><span className="event-name"><i/>{event.event_type.replaceAll('_',' ')}</span></td><td>{event.source}</td><td>Store record {event.event_type.includes('update')?'updated':'reviewed'}</td></tr>)}{!(events??[]).length&&<tr><td colSpan={4}>No store-specific activity recorded yet.</td></tr>}</tbody></table></div></section>
  </main></section></main>;
}
