import { AdminSidebar } from '@/components/admin-sidebar';
import { BarChart3, Bell, CirclePause, Megaphone, MousePointerClick, ShieldCheck, Target } from 'lucide-react';

const campaigns = [
  ['Festive deals discovery', 'Google Ads', 'Search', 'Draft', '₹0', 'Awaiting platform connection'],
  ['Beauty price-drop picks', 'Meta Ads', 'Instagram', 'Draft', '₹0', 'Creative approval required'],
  ['Top deals retargeting', 'Meta Ads', 'Facebook', 'Draft', '₹0', 'Audience policy review required'],
];

export default function AdsPage() { return <main className="admin-v2"><AdminSidebar/><section className="admin-main"><header className="admin-top"><Megaphone size={21}/><b>Ads Manager</b><span className="dashboard-date">Campaign control · preview mode</span><Bell size={19}/><span className="avatar">SR</span></header><main className="admin-content"><div className="admin-title"><div><p>PAID GROWTH</p><h1>Ads Manager</h1><span>Plan, approve and monitor paid campaigns without activating spend until you connect an approved ad platform.</span></div><button className="add-store" disabled>＋ Create campaign</button></div><p className="preview-note">No ad account is connected and no spend can occur. Every future campaign requires an approved platform, budget cap, final destination and owner approval.</p><section className="admin-stats"><article><Megaphone/><div><small>Campaigns</small><b>3</b><em>Draft only</em></div></article><article><CirclePause/><div><small>Active spend</small><b>₹0</b><em>All ads paused</em></div></article><article><Target/><div><small>Budget limit</small><b>Not set</b><em>Required before launch</em></div></article><article><MousePointerClick/><div><small>Ad clicks</small><b>0</b><em>No tracking active</em></div></article><article><ShieldCheck/><div><small>Approval status</small><b>Locked</b><em>Owner approval required</em></div></article></section><section className="admin-grid"><article className="store-table"><div className="table-head"><div><a className="current">Campaigns</a><a>Drafts</a><a>Approval queue</a><a>Archived</a></div></div><div className="table-scroll"><table><thead><tr><th>CAMPAIGN</th><th>PLATFORM</th><th>CHANNEL</th><th>STATUS</th><th>SPEND</th><th>LAUNCH CHECK</th></tr></thead><tbody>{campaigns.map(row=><tr key={row[0]}><td><strong>{row[0]}</strong></td><td>{row[1]}</td><td>{row[2]}</td><td><em className="status-paused">{row[3]}</em></td><td>{row[4]}</td><td>{row[5]}</td></tr>)}</tbody></table></div><footer>Before a campaign can launch, Glonni will validate the budget, creative, audience, provider rules, destination URL and required owner approval.</footer></article><aside className="admin-right"><article><h2>Launch safeguards</h2><p>Daily budget cap <span>Required</span></p><p>Final URL validation <span>Required</span></p><p>Creative approval <span>Required</span></p><p>Stop-all-ads control <span>Ready</span></p></article><article><h2>What appears here live</h2><p className="activity">Spend and pacing<small>Across each connected ad account</small></p><p className="activity">Clicks and conversions<small>Attributed only when tracking is approved</small></p></article></aside></section></main></section></main>; }
