create table public.cashback_claims (
 id uuid primary key default gen_random_uuid(), profile_id uuid not null references public.profiles(id) on delete cascade, offer_id uuid references public.offers(id) on delete set null, order_reference text not null, purchase_amount numeric(12,2), claimed_amount numeric(12,2), evidence_url text, note text, status text not null default 'submitted' check(status in ('submitted','needs_info','confirmed','rejected','cancelled')), reviewer_note text, reviewed_by uuid references public.profiles(id) on delete set null, reviewed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.wallet_entries (id uuid primary key default gen_random_uuid(), profile_id uuid not null references public.profiles(id) on delete restrict, claim_id uuid references public.cashback_claims(id) on delete set null, entry_type text not null check(entry_type in ('cashback_pending','cashback_confirmed','cashback_reversed','withdrawal_hold','withdrawal_paid','withdrawal_reversed')), amount numeric(12,2) not null check(amount <> 0), note text, created_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now());
create table public.withdrawal_requests (id uuid primary key default gen_random_uuid(), profile_id uuid not null references public.profiles(id) on delete restrict, amount numeric(12,2) not null check(amount >= 100), upi_id text not null, status text not null default 'requested' check(status in ('requested','on_hold','approved','paid','rejected')), reviewer_note text, reviewed_by uuid references public.profiles(id) on delete set null, reviewed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index cashback_claims_profile_status_idx on public.cashback_claims(profile_id,status,created_at desc); create index wallet_entries_profile_created_idx on public.wallet_entries(profile_id,created_at desc); create index withdrawals_profile_status_idx on public.withdrawal_requests(profile_id,status,created_at desc);
alter table public.cashback_claims enable row level security; alter table public.wallet_entries enable row level security; alter table public.withdrawal_requests enable row level security;
revoke all on public.cashback_claims,public.wallet_entries,public.withdrawal_requests from public,anon; grant select,insert,update on public.cashback_claims,public.wallet_entries,public.withdrawal_requests to authenticated;
create policy "customers manage own cashback claims" on public.cashback_claims for all to authenticated using((select auth.uid())=profile_id) with check((select auth.uid())=profile_id);
create policy "customers read own wallet" on public.wallet_entries for select to authenticated using((select auth.uid())=profile_id);
create policy "customers create own withdrawal" on public.withdrawal_requests for insert to authenticated with check((select auth.uid())=profile_id and status='requested');
create policy "customers read own withdrawals" on public.withdrawal_requests for select to authenticated using((select auth.uid())=profile_id);
create policy "admins manage cashback operations" on public.cashback_claims for all to authenticated using((select role from public.profiles where id=(select auth.uid())) in ('owner','admin','editor')) with check((select role from public.profiles where id=(select auth.uid())) in ('owner','admin','editor'));
create policy "admins manage wallet ledger" on public.wallet_entries for all to authenticated using((select role from public.profiles where id=(select auth.uid())) in ('owner','admin')) with check((select role from public.profiles where id=(select auth.uid())) in ('owner','admin'));
create policy "admins manage withdrawals" on public.withdrawal_requests for all to authenticated using((select role from public.profiles where id=(select auth.uid())) in ('owner','admin')) with check((select role from public.profiles where id=(select auth.uid())) in ('owner','admin'));
