create extension if not exists pgcrypto;

create type public.app_role as enum ('customer','editor','admin','owner');
create type public.integration_mode as enum ('manual','approval_required','automatic');
create type public.offer_status as enum ('draft','active','inactive','expired');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text, role public.app_role not null default 'customer', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.affiliate_providers (id uuid primary key default gen_random_uuid(), name text not null unique, adapter_key text not null unique, integration_mode public.integration_mode not null default 'manual', config jsonb not null default '{}'::jsonb, is_active boolean not null default false, created_at timestamptz not null default now());
create table public.merchants (id uuid primary key default gen_random_uuid(), name text not null unique, slug text not null unique, logo_url text, storefront_url text, homepage_position integer, is_active boolean not null default false, created_at timestamptz not null default now());
create table public.categories (id uuid primary key default gen_random_uuid(), name text not null unique, slug text not null unique, image_url text, display_order integer not null default 0, is_active boolean not null default true);
create table public.products (id uuid primary key default gen_random_uuid(), title text not null, slug text not null unique, description text, brand text, image_url text, category_id uuid references public.categories(id) on delete set null, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.offers (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id) on delete cascade, merchant_id uuid not null references public.merchants(id) on delete restrict, provider_id uuid references public.affiliate_providers(id) on delete set null, external_offer_id text, destination_url text not null, current_price numeric(12,2), currency text not null default 'INR', list_price numeric(12,2), cashback_amount numeric(12,2), status public.offer_status not null default 'draft', starts_at timestamptz, ends_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(provider_id, external_offer_id));
create table public.redirect_events (id uuid primary key default gen_random_uuid(), offer_id uuid references public.offers(id) on delete set null, merchant_id uuid references public.merchants(id) on delete set null, visitor_hash text, referrer text, user_agent text, created_at timestamptz not null default now());
create table public.audit_events (id uuid primary key default gen_random_uuid(), actor_id uuid references auth.users(id) on delete set null, event_type text not null, entity_type text not null, entity_id uuid, source text not null default 'app', metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.ai_agents (id uuid primary key default gen_random_uuid(), key text not null unique, name text not null, mode public.integration_mode not null default 'manual', is_enabled boolean not null default false, guardrails jsonb not null default '{}'::jsonb, updated_at timestamptz not null default now());
create index offers_product_id_idx on public.offers(product_id); create index offers_merchant_id_idx on public.offers(merchant_id); create index redirect_events_offer_id_idx on public.redirect_events(offer_id); create index audit_events_entity_idx on public.audit_events(entity_type,entity_id);

alter table public.profiles enable row level security; alter table public.affiliate_providers enable row level security; alter table public.merchants enable row level security; alter table public.categories enable row level security; alter table public.products enable row level security; alter table public.offers enable row level security; alter table public.redirect_events enable row level security; alter table public.audit_events enable row level security; alter table public.ai_agents enable row level security;
create policy "public can view active merchants" on public.merchants for select using (is_active); create policy "public can view active categories" on public.categories for select using (is_active); create policy "public can view active products" on public.products for select using (is_active); create policy "public can view active offers" on public.offers for select using (status='active');
create policy "users can view their own profile" on public.profiles for select to authenticated using ((select auth.uid())=id);
create policy "admins manage profiles" on public.profiles for all to authenticated using ((select role from public.profiles where id=(select auth.uid())) in ('admin','owner')) with check ((select role from public.profiles where id=(select auth.uid())) in ('admin','owner'));
create policy "admins manage providers" on public.affiliate_providers for all to authenticated using ((select role from public.profiles where id=(select auth.uid())) in ('admin','owner')) with check ((select role from public.profiles where id=(select auth.uid())) in ('admin','owner'));
create policy "admins manage merchants" on public.merchants for all to authenticated using ((select role from public.profiles where id=(select auth.uid())) in ('admin','owner')) with check ((select role from public.profiles where id=(select auth.uid())) in ('admin','owner'));
create policy "admins manage categories" on public.categories for all to authenticated using ((select role from public.profiles where id=(select auth.uid())) in ('admin','owner')) with check ((select role from public.profiles where id=(select auth.uid())) in ('admin','owner'));
create policy "admins manage products" on public.products for all to authenticated using ((select role from public.profiles where id=(select auth.uid())) in ('admin','owner')) with check ((select role from public.profiles where id=(select auth.uid())) in ('admin','owner'));
create policy "admins manage offers" on public.offers for all to authenticated using ((select role from public.profiles where id=(select auth.uid())) in ('admin','owner')) with check ((select role from public.profiles where id=(select auth.uid())) in ('admin','owner'));
create policy "admins view audit events" on public.audit_events for select to authenticated using ((select role from public.profiles where id=(select auth.uid())) in ('admin','owner'));
create policy "admins view redirect events" on public.redirect_events for select to authenticated using ((select role from public.profiles where id=(select auth.uid())) in ('admin','owner'));
create policy "admins manage agents" on public.ai_agents for all to authenticated using ((select role from public.profiles where id=(select auth.uid())) in ('admin','owner')) with check ((select role from public.profiles where id=(select auth.uid())) in ('admin','owner'));
insert into public.ai_agents(key,name,mode,is_enabled,guardrails) values ('deal_discovery','Deal Discovery','manual',false,'{"requires_approval":true}'),('product_normalization','Product Normalization','approval_required',false,'{"requires_approval":true}'),('offer_quality','Offer Quality','approval_required',false,'{"requires_approval":true}'),('paid_marketing','Paid Marketing','manual',false,'{"daily_budget_limit":0,"stop_all_ads":true,"requires_approval":true}') on conflict (key) do nothing;
