import Link from 'next/link';
import { ArrowLeft, BadgeCheck, Clock3, FileText, Landmark, ShieldAlert } from 'lucide-react';
import { notFound } from 'next/navigation';
import { AdminSidebar } from '@/components/admin-sidebar';

const statements:Record<string,{name:string;network:string;expected:string;approved:string;pending:string;disputed:string;due:string;status:string}>={
  amazon:{name:'Amazon Associates',network:'Amazon',expected:'₹4,20,000',approved:'₹2,80,000',pending:'₹1,10,000',disputed:'₹30,000',due:'15 Oct 2026',status:'Pending confirmation'},
  flipkart:{name:'Flipkart Affiliate',network:'Flipkart',expected:'₹2,80,000',approved:'₹1,90,000',pending:'₹70,000',disputed:'₹20,000',due:'10 Oct 2026',status:'Approved by provider'},
  myntra:{name:'Myntra Affiliate',network:'Myntra',expected:'₹1,75,000',approved:'₹1,20,000',pending:'₹40,000',disputed:'₹15,000',due:'12 Oct 2026',status:'Payment due'},
  nykaa:{name:'Nykaa Affiliate',network:'Nykaa',expected:'₹1,20,000',approved:'₹80,000',pending:'₹30,000',disputed:'₹10,000',due:'08 Oct 2026',status:'Partially paid'},
  ajio:{name:'AJIO Affiliate',network:'AJIO',expected:'₹95,000',approved:'₹70,000',pending:'₹20,000',disputed:'₹5,000',due:'20 Oct 2026',status:'Paid'},
  'tata-cliq':{name:'Tata CLiQ Affiliate',network:'Tata CLiQ',expected:'₹58,000',approved:'₹40,000',pending:'₹15,000',disputed:'₹3,000',due:'18 Oct 2026',status:'Disputed'},
};
export default async function ProviderStatement({params}:{params:Promise<{provider:string}>}){const {provider}=await params;const s=statements[provider];if(!s)notFound();return <main className="admin-v2"><AdminSidebar/><section className="admin-main"><main className="admin-content wallet-admin-page"><Link className="profile-back" href="/admin/wallet#provider-payments"><ArrowLeft/>Back to provider payments</Link><header className="wallet-page-heading"><div><p>PROVIDER STATEMENT</p><h1>{s.name}</h1><span>{s.network} · September 2026 settlement and reconciliation detail.</span></div><span className={/Paid|Approved/.test(s.status)?'wallet-badge good':/Disputed/.test(s.status)?'wallet-badge bad':'wallet-badge pending'}>{s.status}</span></header><section className="profile-summary-grid"><article><FileText/><span><small>Expected cashback</small><b>{s.expected}</b><em>Provider report total</em></span></article><article><BadgeCheck/><span><small>Approved</small><b>{s.approved}</b><em>Provider validated</em></span></article><article><Clock3/><span><small>Pending</small><b>{s.pending}</b><em>Awaiting validation</em></span></article><article><ShieldAlert/><span><small>Disputed</small><b>{s.disputed}</b><em>Requires reconciliation</em></span></article></section><article className="wallet-table-card"><header><div><h3>Statement summary</h3><p>Provider receivable amounts and settlement readiness.</p></div></header><div className="profile-money-grid"><p><small>Commission period</small><b>Sep 2026</b></p><p><small>Payment due</small><b>{s.due}</b></p><p><small>Source</small><b>Provider statement</b></p><p><small>Reconciliation</small><b>Open</b></p></div><footer><span>No payout action is available here; provider receipts must be reconciled first.</span><Link href="/admin/wallet#reconciliation">Open reconciliation <ArrowLeft/></Link></footer></article><section className="wallet-review-grid"><article><header><h3>Settlement checks</h3></header><p><BadgeCheck/><span><b>Provider statement received</b><small>Source file registered</small></span><strong>Complete</strong></p><p><Clock3/><span><b>Order matching</b><small>Compare reported conversions</small></span><strong>In progress</strong></p></article><article><header><h3>Payment destination</h3></header><p><Landmark/><span><b>Glonni settlement account</b><small>Bank details are masked and access controlled</small></span><strong>Verified</strong></p></article></section></main></section></main>}
