import { redirect } from 'next/navigation';
import { Clock3, Mail, ShieldCheck } from 'lucide-react';
import { Header } from '@/components/header';
import { BrowseNav } from '@/components/browse-nav';
import { createClient } from '@/lib/supabase/server';
import { createSupportTicket } from '../actions';
import { SupportChannelNav } from '@/components/support-channel-nav';
import '../support.css';

export default async function ContactSupportPage() {
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect('/login?next=/support/contact');
  return <><Header/><main className="support-layout"><BrowseNav items={[{ label: 'Profile', href: '/account?section=help' }, { label: 'Help & Legal', href: '/account?section=help' }, { label: 'Email support' }]} fallback="/account?section=help"/><SupportChannelNav active="email"/><div className="support-workspace" style={{ display: 'block' }}><section className="contact-page"><header className="support-page-head"><div><p>HUMAN SUPPORT · EMAIL</p><h1>Send an email support request</h1><span>Your message becomes a tracked support ticket. Replies stay in your Glonni account so nothing gets lost.</span></div></header><div className="contact-grid"><article className="contact-email"><Mail size={30}/><p>TRACKED EMAIL CHANNEL</p><h2>support@glonni.com</h2><span>We usually reply within 24 hours. Never include passwords, OTPs, card details, or full bank details.</span></article><article><Clock3/><h2>Expected response</h2><b>Usually within 24 hours</b><span>A merchant or provider review may take longer.</span></article><article><ShieldCheck/><h2>For your safety</h2><span>Support will never ask for your password, OTP, PIN, card number, or full bank account number.</span></article></div><form className="channel-request-form" action={createSupportTicket}><input type="hidden" name="sourceChannel" value="email"/><label>Category<select name="category" defaultValue="other"><option value="cashback">Cashback or eligibility</option><option value="withdrawal">Withdrawal or wallet</option><option value="order">Order or missing tracking</option><option value="deal">Deal, price or coupon</option><option value="account">Account help</option><option value="security">Security concern</option><option value="other">Something else</option></select></label><label>Subject<input name="subject" required minLength={4} maxLength={180} placeholder="Example: Cashback is still pending"/></label><label>Message<textarea name="message" required minLength={10} maxLength={5000} rows={6} placeholder="Tell us what happened, including the store, order ID if available, and date."/></label><button className="primary" type="submit"><Mail size={16}/>Send to support</button></form><section className="contact-checklist"><h2>To help us resolve an issue faster</h2><div><span>✓ Store or merchant name</span><span>✓ Order ID, if available</span><span>✓ Date of click or order</span><span>✓ Screenshots, if relevant</span></div></section></section></div></main></>;
}
